--[[--------------------------------------------------
003_Alliance_50to60.lua
Authors: mrmr
Version: 1.04.3
------------------------------------------------------
Description: Guide Serie - 003 From Lvl 50 to Lvl 60
    1.04.1
        -- First Release
            Alliance's Guide
            from level 50 to lever 60
    1.04.2
    	-- no changes in here for this revision
	1.04.3
		-- Added color codes
			Fixed various spelling errors
	1.05.0
        -- Added Hunter Sepecfic steps
        -- Still do in this section add numbered steps to rest of this guide, add qoutes to Quests, add COORDS color to travel directions, and check to see if NPC color has been missed used
	1.1.0
		-- Автор перевода и актуализации: Eynschteyn
------------------------------------------------------
Connection:
--]]--------------------------------------------------

Table_003_Alliance_50to60 = {
-----------50-51 Searing Gorge
	--[501] = {
	[5051] = {
		title = "50-51 Searing Gorge",
		--n = "50-51 Searing Gorge",
		--pID = 413, nID = 502,
		--itemCount = 72,
		items = {
			[1] = { str = "1. 50-51 Searing Gorge" },
			[2] = { str = "2. Идите в точку 65,62 у туалета возьмите задание #ACCEPTCaught!#", x = 65, y = 62, zone = "Searing Gorge" },
			[3] = { str = "3. Спуститесь с горки и убивайте геологов для задания #DOQUESTCaught!#" },
			[4] = { str = "4. Уничтожте всех мобов и в яме возьмите задание #ACCEPTSuntara Stones pt.1#, сопроводите до точки 74,19 и когда он умрет возьмите записку и примите задание #ACCEPTSuntara Stones pt.2#", x = 74, y = 19, zone = "Searing Gorge" },
			[5] = { str = "5. Спуститесь снова от туалета в точку 65,62 и убейте последних геологов если они вам нужны и сдайте задание #TURNINCaught!#, возьмите задание #ACCEPTLedger From Tanaris# и возьмите книгу которую он подсунет вам под дверь", x = 65, y = 62, zone = "Searing Gorge" },
			[6] = { str = "6. Идите в точку 71,72 и убейте #NPCMargol the Rager# и заберите у него Margol's Horn который дает задание #ACCEPTThe Horn of the Beast# это даст вам ключ searing gorge key бесполезный сейчас, откройте полетчика в точке 38,30", x = 71, y = 72, zone = "Searing Gorge" },
			[7] = { str = "7. Идите в точку 39,38 возьмите задание #ACCEPTDivine Retribution# говорите с НПС пока не выполните задание потом возьмите следующее задание #ACCEPTThe Flawless Flame#", x = 39, y = 38, zone = "Searing Gorge" },
			[8] = { str = "8. Поднимитесь на верх в Thorium Point в точке 38,26", x = 38, y = 26, zone = "Searing Gorge" },
			[9] = { str = "9. Возьмите задания с таблички #ACCEPTWANTED: Overseer Maltorius#, (для этого потребуется группа) #ACCEPTSTOLEN: Smithing Tuyere and Lookout's Spyglass# и #ACCEPTJOB OPPORTUNITY: Culling the Competition#" },
			[10] = { str = "10. Возьмите задания #ACCEPTCurse These Fat Fingers#, #ACCEPTFiery Menace!#, #ACCEPTIncendosaurs? Whateverosaur is More Like It# около башни" },
			[11] = { str = "11. Под шатрром возьмите задание #ACCEPTWhat The Flux?#" },
			[12] = { str = "12. Откройте полетчика и летите в IF" },
			[13] = { str = "13. Идите в точку 71,16 и сдайте задание #TURNINSuntara Stones pt.2#, возьмите следующее #ACCEPTDwarven Justice#", x = 71, y = 16, zone = "Searing Gorge" },
			[14] = { str = "14. Летите в Thelsamar" },
			[15] = { str = "15. Идите в точку 18,83 и сдайте задание #TURNINThe Horn of the Beast#, возьмите следующее #ACCEPTProof of Deed#", x = 18, y = 83, zone = "Searing Gorge" },
			[16] = { str = "16. Жмите Hearth в IF" },
			[17] = { str = "17. Идите в точку 69,11 и сдайте задание #TURNINProof of Deed#, и возьмите следующее #ACCEPTAt Last!#", x = 69, y = 11, zone = "Searing Gorge" },
			[18] = { str = "18. Идите в точку 75,23 и возьмите задание #ACCEPTA Little Slime Goes A Long Way#", x = 75, y = 23, zone = "Searing Gorge" },
			[19] = { str = "19. Летите в Thelsamar и бегите в точку 18,83", x = 18, y = 83, zone = "Searing Gorge" },
			[20] = { str = "20. Сдайте задание #TURNINAt Last!# и прикрепите ключ к брелку. Легко получите 12 000 опыта" },
			[21] = { str = "21. Теперь самое интересное - выполнение всех этих заданий некоторые монстры находятся на обширной территории по этому я не буду указывать их координаты" },
			[22] = { str = "22. Спуститесь южнее и убивайте пауков glassweb spiders для задания #DOQUESTLedger From Tanaris#" },
			[23] = { str = "23. Убивайте всех големов которых видите для задания #DOQUESTThe Flawless Flame#" },
			[24] = { str = "24. Обойдите южную часть котла (яму) и вернитесь к TP затем выполните следующие действия:" },
			[25] = { str = "25. Убивайте heavy war golems и infernal elementals (кроме magma elementals для задания #DOQUESTThe Flawless Flame# и heavy war golems для задания #DOQUESTCurse These Fat Fingers#" },
			[26] = { str = "26. Бейте dark iron lookouts и steamsmiths (Их всего 6, так что если не упадет вернитесь если ничего не выпадет с них падает ключ от туалета) для задания #DOQUESTSTOLEN: Smithing Tuyere and Lookout's Spyglass#" },
			[27] = { str = "27. Сдайте задание #TURNINThe Flawless Flame# и возьмите задание #ACCEPTForging the Shaft# когда снова окажетесь рядом с TB (как я понял это туалет)." },
			[28] = { str = "28. Бейте greater lava spiders (не searing) для задания #DOQUESTFiery Menace!# на юго-западе" },
			[29] = { str = "29. Если вам выпал Grimesilt Outhouse Key используйте его и возьмите задание #ACCEPTThe Key to Freedom# и сдайте его в точке 65,62", x = 65, y = 62, zone = "Searing Gorge" },
			[30] = { str = "30. Идите в точку 63,38 и спуститесь в котлован", x = 63, y = 38, zone = "Searing Gorge" },
			[31] = { str = "31. Бейте dark iron taskmasters и slavers внутри пещеры если увидите их для задания #DOQUESTJOB OPPORTUNITY: Culling the Competition and Forging the Shaft#" },
			[32] = { str = "32. Вход в пещеру находится в точке 41,54", x = 41, y = 54, zone = "Searing Gorge" },
			[33] = { str = "33. Идите в пещеру по координатам 41,25 пройдите через дверь с решоткой и сдайте задание #TURNINDwarven Justice# и возьмите #ACCEPTRelease Them#", x = 41, y = 25, zone = "Searing Gorge" },
			[34] = { str = "34. Поднимитесь по пандусу и держитесь правее пока не дойдете до точки 40,35, убейте босса для задания #DOQUESTWANTED: Overseer Maltorius# и заюзайте чертежи для задания #DOQUESTWhat The Flux?# это задание можно сделать в 2ем но сложно", x = 40, y = 35, zone = "Searing Gorge" },
			[35] = { str = "35. Идите по танелю который ведет наружу и поворачивает снова внутрь пещеры идите туда и убивайте Incendosaur для задания #DOQUESTIncendosaurs? Whateverosaur is More Like It# Собивайте чащуйки они пригодятся позже" },
			[36] = { str = "36. Гриндите пока не останется до следующего уровня около 36 000 опыта" },
			[37] = { str = "37. Умрите специально и реснитесь на кладбоне идите сдайте выполненные задания" },
			[38] = { str = "38. Сдайте задание #TURNINWANTED: Overseer Maltorius#" },
			[39] = { str = "39. С права от башни поверните и сдайте #TURNINCurse These Fat Fingers#, #TURNINFiery Menace!# и #TURNINIncendosaurs? Whateverosaur is More Like It#" },
			[40] = { str = "40. Идите в палатку позади и сдайте #TURNINSTOLEN: Smithing Tuyere and Lookout's Spyglass# и #TURNINJOB OPPORTUNITY: Culling the Competition#" },
			[41] = { str = "41. Идите к следующей палатке и сдайте #TURNINWhat The Flux?#" },
			[42] = { str = "42. После того как выполните все задания, вы можете делать эти задания повторно получая немного опыта и репутицию у TB. Сохронять чашуйки нужно было для того что бы:" },
			[43] = { str = "43. Сейчас вам осталось совсем не много до 51 уровня, идите на юг от базы в точку 38,38", x = 38, y = 38, zone = "Searing Gorge" },
			[44] = { str = "44. Сдайте задание #TURNINForging the Shaft# и возьмите #ACCEPTThe Flame’s Casing#" },
			[45] = { str = "45. Сейчас у вас должно не хватать 1 или 2 клеток до 51 уровня" },
			[46] = { str = "46. Идите по тропе в гору в точку 24,32", x = 24, y = 32, zone = "Searing Gorge" },
			[47] = { str = "47. Убивайте элитных мобов по одному на пути к лавовой яме в точке 29,25, зачистите мобов вокруг нее, idolators не нападают если вы стоите на камне в центре. Запрыгивайте на камень используя маунта. Откройте и возьмите задание #ACCEPTRelease Them#", x = 29, y = 25, zone = "Searing Gorge" },
			[48] = { str = "47. Убивая этих мобов вокруг бассейна вы должны были найти символ рагнороса Symbol of Ragnaros для задания #DOQUESTThe Flame’s Casing# если нет убивайте пока не найдете его" },
			[49] = { str = "49. Поговорите с НПС в клетке он даст задание #ACCEPTPrayer to Elune pt.1# прослкшайте рассказ и сдайте задание, берите следующее #ACCEPTPrayer to Elune pt.2# сейчас нужно бить существ что бы получить Rag и Prayer of Elune, это легко получить" },
			[50] = { str = "50. Идите в точку 38,38 и сдайте #TURNINThe Flame’s Casing# и возьмите следующее #ACCEPTThe Torch of Retribution pt.1#, сдайте его обратно. Возьмите задание #ACCEPTThe Torch of Retribution pt.2# затем возьмите факел перед ним и завершите задание. Берите следующее #ACCEPTSquire Maltrake# сдайте его и берите следующее #ACCEPTSet Them Ablaze!#", x = 38, y = 38, zone = "Searing Gorge" },
			[51] = { str = "51. Наденьте посох вместо нормального оружия и бегите к каждой башни 4 башен по координатам: 33,53; 36,60; 44,61; 50,54 убейте дворфов внизу (если сможете) поднимитесь на башню и зажгите чашки" },
			[52] = { str = "52. Когда найдете все башни найтите безопасное место что бы спрыгнуть вниз и зайьти в пещеру в точке 41,54 и через дверь тюремной решетки по координатам 37,44 и бегите до комнаты с големом в точке 41,25 коснитесь камня со свечами и сдайте задание. Следующее задание ПРОПУСТИТЕ если у вас нет группы там нужно убить 2 элитных моба golem и dwarf", x = 41, y = 54, zone = "Searing Gorge" },
			[53] = { str = "53. Специально умри что бы оказаться в TP и идите в точку 29,38 сдайте задание #TURNINSet Them Ablaze!#, посмотри сцену где он превращается в дракона", x = 29, y = 38, zone = "Searing Gorge" },
			[54] = { str = "54. Откройте сундук на земле и возьмите задание #ACCEPTTrinkets...# затем откройте его снова и завершите задание. Откройте его и сохраните the Black Dragonflight Molt она пргодится в Burning Steppes." },
			[55] = { str = "55. Летите в Blasted Lands и бегите в Swamp of Sorrows" },
			[56] = { str = "56. Идите в точку 81,91 и найдите мурлока #NPCJarquia# для задания #DOQUESTLedger From Tanaris#", x = 81, y = 91, zone = "Swamp of Sorrows" },
			[57] = { str = "57. После того как вы его убьете вернитесь в IF затем используйте портал в Darnassus или летите Menethil и плывите на коробле в Auberdine и летите в Darnassus" },
			[58] = { str = "58. Поднимитесь на вершину холма в точке 38,80 и сдайте задание #TURNINPrayer to Elune pt.2#", x = 38, y = 80, zone = "darnassus" },
			[59] = { str = "59. Идите выше и сдайте задание #TURNINRise of the Silithid# и возьмите новое #ACCEPTMarch of the Silithid#" },
			[60] = { str = "60. Идите в точку 34,9 на вершине башни сдайте задание #TURNINAssisting Arch Druid Staghelm# и возьмите #ACCEPTUn'Goro Soil#", x = 34, y = 9, zone = "darnassus" },
			[61] = { str = "61. Сделайте Darnassus своим домом в точке 67,15", x = 67, y = 15, zone = "darnassus" },
			[62] = { str = "62. Теперь летите в Theramore или садитесь на корабль до Menethil затем плывите в Theramore" },
			[63] = { str = "63. Если у вас нет еще навыка первой помощи 290 приобретите heavy runecloth bandages" },
			[64] = { str = "64. Идите в точку 54,55 к затонувшему караблю и заберите overdue package для задания #DOQUESTLedger From Tanaris#", x = 54, y = 55, zone = "Duskwallow Marsh" },
			[65] = { str = "65. Идите в пещеру в точке 31,66 и коснитесь свитка в конце пещеры и сдайте задание #TURNINCortello's Riddle pt.2#, берите следующее #ACCEPTCortello's Riddle pt.3#", x = 31, y = 66, zone = "Duskwallow Marsh" },
			[66] = { str = "66. натравите на себя рапторов сто бы умереть и оказаться в Theramore" },
			[67] = { str = "67. Летите в Gadgetzan" },
			[68] = { str = "68. На входе в Gadgetzanсдайте задание #TURNINLedger From Tanaris#" },
			[69] = { str = "69. Достаньте свои перчатки 52 уровня и отправьте их по почте что бы получить их позже" },
			[70] = { str = "70. Между двумя северными воротами возьмите задание #ACCEPTSuper Sticky#" },
			[71] = { str = "71. Идте к хижине на западе и сдайте #TURNINMarch of the Silithid#, возьмите #ACCEPTBungle in the Jungle#" },
			[72] = { str = "72. Спуститесь в кратер Un’Goro в точке 26,52", x = 26, y = 52, zone = "Tanaris" },
		}
	},

-----------51-52 Un’Goro Crater
	--[502] = {
	[5152] = {
		title = "51-52 Un’Goro Crater",
		--n = "51-52 Un’Goro Crater",
		--pID = 501, nID = 503,
		--itemCount = 60,
		items = {
			[1] = { str = "1. 51-52 Un’Goro Crater" },
			[2] = { str = "2. Начинайте собирать предметы для заданий сразу вам понадобится: Power Crystals (нужно по 7 штук красных, голубых, зеленых, желтых), Так же собирайте кучи земли Un’Goro (соберите как можно больше), и Bloodpetal Sprouts соберите по 15 штук" },
			[3] = { str = "3. Гриндите птеродактелей что бы получить предмет #NPCA Mangled Journal# (шанс выпадения низкий) как только вы его найдете вам больше не придется их гриндить" },
			[4] = { str = "4. Идите к водопаду в точку 71,75 и возьмите задания #ACCEPTThe Apes of Un'Goro# и #ACCEPTThe Fare of Lar'Korwi#", x = 71, y = 75, zone = "Un’Goro Crater" },
			[5] = { str = "5. Гриндите до точки 62,68 и нажмите на утонувшую лодку и возьмите задание #ACCEPTIt's A Secret to Everybody pt.1# недалеко отсюда под водой сдайте задание и возьмите следующее #ACCEPTIt's A Secret to Everybody pt.2#", x = 62, y = 68, zone = "Un’Goro Crater" },
			[6] = { str = "6. Гриндите до точки 68,56 и убейте огромного динозавра для задания #DOQUESTThe Fare of Lar'Korwi#", x = 68, y = 56, zone = "Un’Goro Crater" },
			[7] = { str = "7. Вернитесь в точку 71,75 и сдайте задание #TURNINThe Fare of Lar'Korwi#, берите следующее #ACCEPTThe Scent of Lar'Korwi#", x = 71, y = 75, zone = "Un’Goro Crater" },
			[8] = { str = "8. Гриндите до точки 67,63 там будет 2 места с яйцами уничтожте всех raptors вокруг яиц и встаньте на яйца что бы появился нужный моб для задания #DOQUESTThe Scent of Lar'Korwi#", x = 67, y = 63, zone = "Un’Goro Crater" },
			[9] = { str = "9. Идите назад в точку 71,75 и сдайте задание #TURNINThe Scent of Lar'Korwi#, возьмите следующее #ACCEPTThe Bait For Lar'Korwi# к этому моменту вы должны дневник jornal если нет продолжайте убивать raptors пока выполняете задание в этом месте. Если журнал выпал возьмите задание #ACCEPTWilliden’s Journal#", x = 71, y = 75, zone = "Un’Goro Crater" },
			[10] = { str = "10. Идите в точку 79,49 на востоке между гор увидите большой скелет рядом есть плоский камень встаньте на него и используйте meat и phermone из сумки. Это призавет Lar’Korwi для задания #DOQUESTThe Bait For Lar'Korwi# его довольно легко убить", x = 79, y = 49, zone = "Un’Goro Crater" },
			[11] = { str = "11. Идите в точку 46,13 и возьмите задание #ACCEPTChasing A-Me 01# и бегите позади нее в убежище маршала Marshal’s Refuge.", x = 46, y = 13, zone = "Un’Goro Crater" },
			[12] = { str = "12. С лева возьмите задание #ACCEPTShizzle's Flyer#" },
			[13] = { str = "13. Дальше в лева чуть позади возьмите задание #ACCEPTMuigin and Larion#" },
			[14] = { str = "14. Далее возьмите задания #ACCEPTLost!# и #ACCEPTBeware of Pterrordax#" },
			[15] = { str = "15. Перед пещерой возьмите задание #ACCEPTRoll the Bones#" },
			[16] = { str = "16. Если у вас есть 15 bloodpetal sprouts, сдайте их для задания дейлика #ACCEPTDadanga is Hungry!# вы можете получить редкий и дорогой предмет по этому стоит попробовать" },
			[17] = { str = "17. Справа от пещеры возьмите задание #ACCEPTAlien Ecology#" },
			[18] = { str = "18. Снова поверните на право и сдайте #TURNINWilliden’s Journal# и возьмите #ACCEPTExpedition Salvation#" },
			[19] = { str = "19. Пройдите на юг и вы найдете Linken прямо возле полуполого дерева. Сдайте задание #TURNINIt's A Secret to Everybody pt.2# и возьмите следующее #ACCEPTIt's A Secret to Everybody pt.3#" },
			[20] = { str = "20. Откройте полетчика справа от пещеры потом зайдите в пещеру пройдите до конца и возьмите задание #ACCEPTCrystals of Power# и сдайте его. Возьмите 3 задания #ACCEPTThe Northern Pylon#, #ACCEPTThe Eastern Pylon# и #ACCEPTThe Western Pylon#" },
			[21] = { str = "21. При появлении следующих мобов сразу убивайте их при первой же возможности пока не завершится связанное с ним задание" },
			[22] = { str = "22. Убивайте bloodpetals для задания #DOQUESTMuigin and Larion#" },
			[23] = { str = "23. Убивайте diametradons и pterrodaxes для заданий #DOQUESTShizzle's Flyer# и #DOQUESTRoll the Bones#" },
			[24] = { str = "24. Убивайте pterrodaxes и frenzied pterrodaxes для задания #DOQUESTBeware of Pterrordax#" },
			[25] = { str = "25. Идите на восток вдоль гор в точку 54,13 поднимитесь и исследуйте  пилон pylon для задания #DOQUESTThe Northern Pylon# и идите на север там должны быть pterrodaxes.", x = 54, y = 13, zone = "Un’Goro Crater" },
			[26] = { str = "26. Идите на восток в товку 63,16 и убивайте gorillas для задания #DOQUESTThe Apes of Un'Goro# затем войдите в пещеру и держитесь правее что бы сдать задание #TURNINChasing A-Me 01# следующую часть задания ПРОПУСТИТЕ", x = 63, y = 16, zone = "Un’Goro Crater" },
			[27] = { str = "27. На черных озерах в точке 52,23 бейте monsters для задания #DOQUESTSuper Sticky#, в 3х озерах к югу от гарилл в точке 61,27 обитают такие же монстры более низкого уровня. Так же тут встречаются bloodpetals для задания #DOQUESTMuigin and Larion# тут рядом обитают diametradons и pterrodaxes для задания #DOQUESTShizzle's Flyer# running around", x = 61, y = 27, zone = "Un’Goro Crater" },
			[28] = { str = "28. Идите в точку 68,36 и возьмите ящик с продуктами для задания #DOQUESTExpedition Salvation#", x = 68, y = 36, zone = "Un’Goro Crater" },
			[29] = { str = "29. Постарайтесь собрать все предметы для задания #DOQUESTShizzle's Flyer# если вы не просто ходите ии щите их в одиночку. Мне кажется я всегда нахожу их раньше чем заканчиваю собирать bloodpetals." },
			[30] = { str = "30. Идите в точку 76,51 следуйте по тропе к пилону для задания #DOQUESTThe Eastern Pylon# южнее должны быть pterrodaxes в точке 75,61", x = 76, y = 51, zone = "Un’Goro Crater" },
			[31] = { str = "31. Идите в точку 71,75 и сдайте задания #TURNINThe Bait For Lar'Korwi# и #TURNINThe Apes of Un'Goro# следующее задание пока ПРОПУСТИТЕ", x = 71, y = 75, zone = "Un’Goro Crater" },
			[32] = { str = "32. Если вы много гриндили растений и динозавров вы должны быть близки к 52 уровню, если уже не получили его" },
			[33] = { str = "33. К востоку от вулкана (в середине карты) обитают pterrodaxes они нужны для задания #DOQUESTBeware of Pterrordax# если возникли проблемы с их поиском то 6 штук появлюятся южнее в точке 55,90", x = 55, y = 90, zone = "Un’Goro Crater" },
			[34] = { str = "34. Бегите на запад в точку 55,73 там спавн diametradon 5-6 штук убейте их если они вам все еще для задания #DOQUESTShizzle's Flyer# или #DOQUESTRoll the Bones#", x = 55, y = 73, zone = "Un’Goro Crater" },
			[35] = { str = "35. Идите на запад в точку 50,77 в извилистую пещеру на развилке поверните на лево в большую комнату по середине используйте флакон scraping vial для задания #DOQUESTAlien Ecology#", x = 50, y = 77, zone = "Un’Goro Crater" },
			[36] = { str = "36. Есть еще один респ diametradon camp если они вам еще нужны scales или bones для задания #DOQUESTShizzle's Flyer# или #DOQUESTRoll the Bones#" },
			[37] = { str = "37. Бегите по координатам 38,65 и возьмите research equipment для задания #DOQUESTExpedition Salvation#", x = 38, y = 65, zone = "Un’Goro Crater" },
			[38] = { str = "38. Бейте frenzied pterrodaxes около координат 35,38 в северо-западной части карты для задания #DOQUESTBeware of Pterrordax# а так же тут много diametradons для задания #DOQUESTShizzle's Flyer# или #DOQUESTRoll the Bones#", x = 35, y = 38, zone = "Un’Goro Crater" },
			[39] = { str = "39. Спуститесь в точку 23,59 и коснитесь западного пилона для задания #DOQUESTThe Western Pylon# и убивайте pterrodaxes которые вам нужны за ней", x = 23, y = 59, zone = "Un’Goro Crater" },
			[40] = { str = "40. Идите в точку 30,50 и выполните задание #DOQUESTFinding the Source#", x = 30, y = 50, zone = "Un’Goro Crater" },
			[41] = { str = "41. Идите в точку 51,48 и убивайте елементалей, старайтесь избегать мобов выше 56+ уровня для задания #DOQUESTVolcanic Activity# не трогайте blazing invaders alone", x = 51, y = 48, zone = "Un’Goro Crater" },
			[42] = { str = "42. После того отпустите питомца поднимитесь на маунте на вершину вулкана увидите скалы похожие на камни сумона слезьте с маунта и используйте thermometer" },
			[43] = { str = "43. Если вам не нужен пепел всеравно идите в точку 30,50 и сдайте задание #TURNINFinding the Source# и возьмите задание #ACCEPTThe New Springs#", x = 30, y = 50, zone = "Un’Goro Crater" },
			[44] = { str = "44. Поднимитесь в пещеру тем же способов в точке 51,49 и сдайте задание #TURNINLost!# задем возьмите #ACCEPTA Little Help From My Friends# выходите из пещеры аккуратно что бы не агрить все подряд как только уйдете от вулкана там уже будет легко. Не забывайте охлаждать его время от времени", x = 51, y = 49, zone = "Un’Goro Crater" },
			[45] = { str = "45. Когда приведете его в город подойдите к знаку и задание завершится, затем сдайте задание #TURNINBeware of Pterrordax#" },
			[46] = { str = "46. Сдайте задание #TURNINShizzle's Flyer#" },
			[47] = { str = "47. Сдайте задание #TURNINMuigin and Larion# следующее задание ПРОПУСТИТЕ" },
			[48] = { str = "48. Сдайте задание #TURNINRoll the Bones#" },
			[49] = { str = "49. Сдайте задание #TURNINAlien Ecology#" },
			[50] = { str = "50. Сдайте задание #TURNINExpedition Salvation#" },
			[51] = { str = "51. В пещере сдайте задания #TURNINThe Northern Pylon#, #TURNINThe Eastern Pylon#, #TURNINThe Western Pylon# и возьмите #ACCEPTMaking Sense of It# и сдайте его обратно. Она расскажет о бонусах пилонов" },
			[52] = { str = "52. Идите в точку 29,22 м идите по тропе в Slithus в точку 50,34 откройте полетчика и летите в Gadgetzan.", x = 29, y = 22, zone = "Un’Goro Crater" },
			[53] = { str = "53. Идите в северо-западную часть города и сдайте задание #TURNINBungle in the Jungle#, ПРОПУСТИТЕ следующее задание. Сдайте другое задание #TURNINSuper Sticky# между 2 выходами" },
			[54] = { str = "54. Жмите Hearth в Darnassus и выучите новые навыки у классового тренера" },
			[55] = { str = "55. У вас должно быть более 50 штук земли унгоро" },
			[56] = { str = "56. Идите в точку 31,8 и сдайте задание #TURNINUn'Goro Soil#", x = 31, y = 8, zone = "Darnassus" },
			[57] = { str = "57. Идите на вершину башни и возьмите задание #ACCEPTMorrowgrain Research pt.1# затем спуститесь и сдайте его. Берите следующее #ACCEPTMorrowgrain Research pt.2#" },
			[58] = { str = "58. В зависимости от количества почвенных участков, вам могут понадобиться дополнительные пакетики с семенами. Пакетик можно использовать каждые 10 минут, и урожай не всегда будет достаточным. В любом случае, вам нужно всего 10 пакетиков" },
			[59] = { str = "59. Идите в Rut’theran Village войдите в дом справа возьмите задание #ACCEPTMoontouched Wildkin# это задание в winterspring" },
			[60] = { str = "60. Летите в Astranaar, затем идите в точку 91,46 там мост ведет в Azshara", x = 91, y = 46, zone = "Ashenvale" },
		}
	},

-----------52-53 Azshara
	--[503] = {
	[5253] = {
		title = "52-53 Azshara",
		--n = "52-53 Azshara",
		--pID = 502, nID = 504,
		--itemCount = 10,
		items = {
			[1] = { str = "1. 52-53 Azshara" },
			[2] = { str = "2. Сразу с права в точке 11,77 откройте полетчика", x = 11, y = 77, zone = "Azshara" },
			[3] = { str = "3. За ним возьмите задания #ACCEPTSpiritual Unrest# и #ACCEPTA Land Filled With Hatred#" },
			[4] = { str = "4. Идите на север уничтожать призраков в точку 14,72 и 16,67 бейте их для задания #DOQUESTSpiritual Unrest#", x = 14, y = 72, zone = "Azshara" },
			[5] = { str = "5. Идите севернее в точку 19,61 и бейте satyr’s в этом районе для задания #DOQUESTA Land Filled With Hatred", x = 19, y = 61, zone = "Azshara" },
			[6] = { str = "6. Вернитесь в точку 11,77 и сдайте задания #TURNINSpiritual Unrest# и #TURNINA Land Filled With Hatred#", x = 11, y = 77, zone = "Azshara" },
			[7] = { str = "7. Идите в точку 39,55 и получите оттиск Markri rubbing для задания #DOQUESTArcane Runes#", x = 39, y = 55, zone = "Azshara" },
			[8] = { str = "8. Идите в точку 36,53 и получите оттиск Beth’Amara Rubbing для задания #DOQUESTArcane Runes#", x = 36, y = 53, zone = "Azshara" },
			[9] = { str = "9. Идите в точку 39,50 и получите оттиск Jin’yael rubbing для задания #DOQUESTArcane Runes#", x = 39, y = 50, zone = "Azshara" },
			[10] = { str = "10. Идите в точку 42,42 и сдайте задание #TURNINThe Hunter's Charm#, возьмите следующее #ACCEPTCourser Antlers# это задание является не обязательным и выполняется после получения 53 уровня. Я его выполняю потому что если его не выполнить то немного отстанете от руководства, на сбор этого и следующего задания уходит около 1-2 часов это позволит вам на 20-25% от необходимого уровня", x = 42, y = 42, zone = "Azshara" },
		}
	},

------------53-54 Felwood
	--[504] = {
	[5354] = {
		title = "53-54 Felwood",
		--n = "53-54 Felwood",
		--pID = 503, nID = 505,
		--itemCount = 54,
		items = {
			[1] = { str = "1. 53-54 Felwood" },
			[2] = { str = "2. Stop at 54,86 and accept #ACCEPTCleansing Felwood#", x = 54, y = 86, zone = "Felwood" },
			[3] = { str = "3. Run north a little bit to 51,81 and accept #ACCEPTForces of Jaedenar#", x = 51, y = 81, zone = "Felwood" },
			[4] = { str = "4. Inside the house, accept #ACCEPTThe Corruption of the Jadefire#" },
			[5] = { str = "5. Under the tent accept #ACCEPTVerifying the Corruption# and #ACCEPTTo Winterspring!#" },
			[6] = { str = "6. Just across the road accept #ACCEPTTimbermaw Ally#" },
			[7] = { str = "7. Go just SW of here around 48,91 and kill the Furlbogs until you finish #DOQUESTTimbermaw Ally# Just grind them all for rep until you’re done", x = 48, y = 91, zone = "Felwood" },
			[8] = { str = "8. Go back to 50,85 and turn in #TURNINTimbermaw Ally# accept #ACCEPTSpeak to Nefian# the other is repeatable for rep", x = 50, y = 85, zone = "Felwood" },
			[9] = { str = "9. Go up near the 2 lakes at 40,69 and kill the cursed oozes for the first part of #DOQUESTA Little Slime Goes A Long Way pt.1#", x = 40, y = 69, zone = "Felwood" },
			[10] = { str = "10. Go to the west of here now to 37,69 and kill the jadefire demons for #DOQUESTThe Corruption of the Jadefire# these are good to farm too.", x = 37, y = 69, zone = "Felwood" },
			[11] = { str = "11. Go up to 39,59 and kill the tainted oozes for the second part of #DOQUESTA Little Slime Goes A Long Way pt.1", x = 39, y = 59, zone = "Felwood" },
			[12] = { str = "12. Go just west of here around 37,59 and kill the Jaedenar for #DOQUESTForces of Jaedenar# You don’t have to go in the caves.", x = 37, y = 59, zone = "Felwood" },
			[13] = { str = "13. Go back to 51,82 and turn in #TURNINForces of Jaedenar# accept #ACCEPTCollection of the Corrupt Water#.", x = 51, y = 82, zone = "Felwood" },
			[14] = { str = "14. Inside the house turn in #TURNINThe Corruption of the Jadefire# accept #ACCEPTFurther Corruption#" },
			[15] = { str = "15. Go back up to Jaedenar to the green pool at 35,59 and fill the canteen for #DOQUESTCollection of the Corrupt Water#", x = 35, y = 59, zone = "Felwood" },
			[16] = { str = "16. Go back to 51,82 and turn in #TURNINCollection of the Corrupt Water# accept #ACCEPTSeeking Spiritual Aid#", x = 51, y = 82, zone = "Felwood" },
			[17] = { str = "17. Go up to 42,20 and kill Entropic beasts and horrors and explore the craters for #DOQUESTVerifying the Corruption#.", x = 42, y = 20, zone = "Felwood" },
			[18] = { str = "18. Go up to 46,14 and follow it to the back, killing the demons for #DOQUESTFurther Corruption# When you kill Xavaric he'll drop Flute of Xavaric which starts #ACCEPTFlute of Xavaric# kill the satyr’s to complete this.", x = 46, y = 14, zone = "Felwood" },
			[19] = { str = "19. Run over to Irontree Cavern at 55,17 and kill 15 of the elementals and that should be enough for #DOQUESTCleansing Felwood#", x = 55, y = 17, zone = "Felwood" },
			[20] = { str = "20. Go up to 62,24 and get the FP", x = 62, y = 24, zone = "Felwood" },
			[21] = { str = "21. Go north to 64,8 and turn in #TURNINSpeak to Nefian# accept #ACCEPTDeadwood of the North#", x = 64, y = 8, zone = "Felwood" },
			[22] = { str = "22. Now fall off the cliff to the west and start killing for Deadwood of the North once you’re done you want to kill until you’re 150 rep from the next rank with the timbermaw (put the rep as an xp bar for ease)" },
			[23] = { str = "23. Go back to 64,8 and turn in #TURNINDeadwood of the North# and you should be unfriendly now and not aggro’d any longer. Accept #ACCEPTSpeak to Salfa# and turn in any 5 sets of feathers for extra rep and 550 xp", x = 64, y = 8, zone = "Felwood" },
			[24] = { str = "24. Go through the cave to Winterspring and just outside the cave to the right at 27,34 turn in #TURNINSpeak to Salfa#", x = 27, y = 34, zone = "Winterspring" },
			[25] = { str = "25. Run south to 31,45 and turn in #TURNINThe New Springs# accept #ACCEPTStrange Sources# also turn in #TURNINIt's A Secret to Everybody pt.3# accept #ACCEPTThe Videre Elixir# and #ACCEPTThreat of the Winterfall#", x = 31, y = 45, zone = "Winterspring" },
			[26] = { str = "26. Run back throug the cave and go west at the fork into Moonglade." },
			[27] = { str = "27. Go to 48,67 and grab the FP", x = 48, y = 67, zone = "Moodglade" },
			[28] = { str = "28. You should be very close leveling now. You can grind the rest of the way or wait. #PICTUREHearth to Astranaar and fly to Feralas#" },
			[29] = { str = "29. Go in the Inn, accept #ACCEPTJonespyre's Request#" },
			[30] = { str = "30. Go up to the top of the tower, turn it in, accept #ACCEPTThe Mystery of Morrowgrain# turn it back in unless you’re still making the stuff." },
			[31] = { str = "31. #HUTNERStable your pet# and ride or swim to the mainland"},
			[32] = { str = "32. #HUNTER31) Tame a 48+ Ironfur Patriarch for Claw rank 7#"},
			[33] = { str = "33. Go up to 45,25 and buy a bait and read on how to get the videre elixir", x = 45, y = 25, zone = "Feralas" },
			[34] = { str = "34. At 45,16 you can be put up to the top of the colossal tower and parachute down. Just make sure you unmount!", x = 45, y = 16, zone = "Feralas" },
			[35] = { str = "35. Go up to 44,10 and place the bait on the ground then go loot an everroot", x = 44, y = 10, zone = "Felalas" },
			[36] = { str = "36. Go back south to 45,25 to get your 3 videre elixir", x = 45, y = 25, zone = "Felalas" },
			[37] = { str = "37. #PICTUREHearth# to Astranaar" },
			[38] = { str = "38. #HUTNER37) Get cat back out#"},
			[39] = { str = "39. Run back up into Felwood to 54,86 and turn in #TURNINCleansing Felwood#", x = 54, y = 86, zone = "Felwood" },
			[40] = { str = "40. Now she allows you to get stuff for some neat potions that are on different cooldowns than potions are." },
			[41] = { str = "41. Go up to 51,81 and in the house turn in #TURNINFurther Corruption# and #TURNINFlute of Xavaric# accept #ACCEPTFelbound Ancients#", x = 51, y = 81, zone = "Felwood" },
			[42] = { str = "42. Under the tent, turn in #TURNINVerifying the Corruption#" },
			[43] = { str = "43. Run up to 62,23", x = 62, y = 23, zone = "Felwood" },
			[44] = { str = "44. Go through the cave to Winterfall and just outside the cave accept #ACCEPTWinterfall Activity#" },
			[45] = { str = "45. Go to 31,45 and turn in #TURNINThe Videre Elixir# accept #ACCEPTMeet at the Grave#", x = 31, y = 45, zone = "Winterspring" },
			[46] = { str = "46. Go to 62,36 and grab the FP", x = 62, y = 36, zone = "Winterspring" },
			[47] = { str = "47. Fly to Rachet" },
			[48] = { str = "48. Run west of the dock and turn in #TURNINVolcanic Activity#" },
			[49] = { str = "49. Run down to 65,43 and turn in #TURNINSeeking Spiritual Aid# accept Cleansed Water Returns to Felwood", x = 65, y = 43, zone = "The Barrens" },
			[50] = { str = "50. Fly to Theramore and sail to Menethil then fly to IF" },
			[51] = { str = "51. Just outside the Military Ward there should be a wandering npc, one is near FP too, grab the quest #ACCEPTThe New Frontier pt.1#" },
			[52] = { str = "52. Go to 75,23 and turn in #TURNINA Little Slime Goes A Long Way pt.1# accept #ACCEPTA Little Slime Goes A Long Way pt.2#", x = 75, y = 23, zone = "Ironforge" },
			[53] = { str = "53. Go to 31,4 and turn in #TURNINReturn to Tymor#", x = 31, y = 4, zone = "Ironforge" },
			[54] = { str = "54. Fly to Menethil then sail to Theramore and fly to Gadgetzan" },
		}
	},

-----------54-54 Tanaris
	--[505] = {
	[5453] = {
		title = "54-54 Tanaris",
		--n = "54-54 Tanaris",
		--pID = 504, nID = 506,
		--itemCount = 20,
		items = {
			[1] = { str = "1. 54-54 Tanaris" },
			[2] = { str = "2. Get your mithril casing out of your bank or mailbox" },
			[3] = { str = "3. Go east to the GY at 54,28 and drink your videre elixir", x = 54, y = 28, zone = "Tanaris" },
			[4] = { str = "4. Now you’re gonna die, don’t rez just release and run north to 53,23 and turn in #TURNINMeet at the Grave# accept #ACCEPTA Grave Situation#", x = 53, y = 23, zone = "Tanaris" },
			[5] = { str = "5. Go back and rez at 54,28 and touch the only tombstone there, turn in #TURNINA Grave Situation# accept #ACCEPTLinken's Sword#", x = 54, y = 28, zone = "Tanaris" },
			[6] = { str = "6. Run into Un’Goro, I’d say fly but we have to go way SE" },
			[7] = { str = "7. Run up to 71,75 and accept #ACCEPTThe Mighty U'cha#", x = 71, y = 75, zone = "Un’Goro" },
			[8] = { str = "8. Keep collecting dirt here if you need more morrowgrain" },
			[9] = { str = "9. Now all around the crater is slimes but you can find all the ones you need west of the volcano around 37,37 for #DOQUESTA Little Slime Goes A Long Way pt.2# I think there are more on the west side of the volcano but you can look on both sides they’re scattered. If it says they’re cloning, finish them very fast or stun them. If they clone it’s a full health mob that you can’t scoop up.", x = 37, y = 37, zone = "Un’Goro" },
			[10] = { str = "10. Go to the cave at 64,16 and go to the right, when you see A-Me 01 accept #ACCEPTChasing A-Me 01 pt.1# and turn it back in. Fall over the edge and to the right and up around until you see U’cha for #DOQUESTThe Mighty U'cha#", x = 64, y = 16, zone = "Un’Goro" },
			[11] = { str = "11. Run back to the front and go right again and accept #ACCEPTChasing A-Me 01 pt.2# now escort her out" },
			[12] = { str = "12. Escort A-Me to Marshal’s at 46,13 and turn in #TURNINChasing A-Me 01 pt.2#", x = 46, y = 13, zone = "Un’Goro" },
			[13] = { str = "13. Go into Marshal’s and turn in #TURNINLinken's Sword# accept #ACCEPTA Gnome's Assistance#" },
			[14] = { str = "14. Go to the back of the cave and turn in #TURNINA Gnome's Assistance#  and accept #ACCEPTLinken’s Memory#" },
			[15] = { str = "15. Run down and let the tar monsters kill you so you’re closer to the SE" },
			[16] = { str = "16. Run down to 71,75 and turn in #TURNINThe Mighty U'cha#", x = 71, y = 75, zone = "Un’Goro" },
			[17] = { str = "17. You should be over half way to level 55 now" },
			[18] = { str = "18. Hearth back to Astranaar and fly to Darnassus" },
			[19] = { str = "19. Go in the Temple of the Moon at 39,84 and fill the vial for #DOQUESTFelbound Ancients#", x = 39, y = 84, zone = "Darnassus" },
			[20] = { str = "20. Run into Felwood" },
		}
	},

-----------54-54 Felwood
	--[506] = {
	[5454] = {
		title = "54-54 Felwood",
		--n = "54-54 Felwood",
		--pID = 505, nID = 507,
		--itemCount = 16,
		items = {
			[1] = { str = "1. 54-54 Felwood" },
			[2] = { str = "2. Go to 51,82 and turn in #TURNINCleansed Water Returns to Felwood# accept #ACCEPTDousing the Flames of Protection#", x = 51, y = 82, zone = "Felwood" },
			[3] = { str = "3. Go in the house, turn in #TURNINFelbound Ancients# accept #ACCEPTPurified!# then turn it back in, easy 10k xp. Also turn in #TURNINLinken’s Memory# accept #ACCEPTSilver Heart#" },
			[4] = { str = "4. You should be 70% through now or close to it" },
			[5] = { str = "5. Start killing all the bears and wolves from here north until you have 11 silvery claws for #DOQUESTSilver Heart#" },
			[6] = { str = "6. Go into the cave at 35,58", x = 35, y = 58, zone = "Felwood" },
			[7] = { str = "7. At the first open area with the caged npc at 36,56 is brazier for #DOQUESTDousing the Flames of Protection# the 2nd one is just up the ramp", x = 36, y = 56, zone = "Felwood" },
			[8] = { str = "8. Continue past the room with candles surrounding the hole to the next open room at 36,53 for the 3rd and 4th brazier for #DOQUESTDousing the Flames of Protection#", x = 36, y = 53, zone = "Felwood" },
			[9] = { str = "9. Don’t even bother trying to do the escort unless you get a group, I always skip it even if I find the key." },
			[10] = { str = "10. Run back outside and up to 51,19 and kill the tree elementals for #DOQUESTSilver Heart#", x = 51, y = 19, zone = "Felwood" },
			[11] = { str = "11. If you want to do the escort with the flute I suggest getting a group you get jumped by a lot of mobs." },
			[12] = { str = "12. Run all the way back down to 51,82 (I know no one wants to run back here, why the quest hub is so far from the FP is beyond me)", x = 51, y = 82, zone = "Felwood" },
			[13] = { str = "13. Turn in #TURNINDousing the Flames of Protection# SKIP the next part for now" },
			[14] = { str = "14. In the house turn in #TURNINSilver Heart# accept #ACCEPTAquementas#" },
			[15] = { str = "15. If you have skinning I’m sure you have at least 5 tainted hides, go down to 54,86 and turn them in for #TURNINSalve via Skinning#", x = 54, y = 86, zone = "Felwood" },
			[16] = { str = "16. Hearth to Astranaar and fly to Winterspring" },
		}
	},

--------------54-55 Winterspring
	--[507] = {
	[5455] = {
		title = "54-55 Winterspring",
		--n = "54-55 Winterspring",
		--pID = 506, nID = 508,
		--itemCount = 34,
		items = {
			[1] = { str = "1. 54-55 Winterspring" },
			[2] = { str = "2. Go in Everlook accept #ACCEPTEnraged Wildkin pt.1#" },
			[3] = { str = "3. Go in the Inn, make it your home" },
			[4] = { str = "4. Accept #ACCEPTThe Everlook Report# #ACCEPTDuke Nicholas Zverenhoff# and #ACCEPTSister Pamela#" },
			[5] = { str = "5. On the other side of town accept #ACCEPTAre We There, Yeti? pt.1#" },
			[6] = { str = "6. Keep your eye out for those blue moonkin feathers to finish up #DOQUESTMoontouched Wildkin#" },
			[7] = { str = "7. Run all the way south to 60,73 to complete #ACCEPTStrange Sources#", x = 60, y = 73, zone = "Winterspring" },
			[8] = { str = "8. Hearth back to Everlook, if it’s not up die on purpose" },
			[9] = { str = "9. Go to 65,45 and kill yeti’s for #DOQUESTAre We There, Yeti? pt.1#", x = 65, y = 45, zone = "Winterspring" },
			[10] = { str = "10. Run back to Everlook and turn in #TURNINAre We There, Yeti? pt.1# accept #ACCEPTAre We There, Yeti? pt.2#" },
			[11] = { str = "11. Go back to 65,45 and kill matriarch’s and patriarch’s for #DOQUESTAre We There, Yeti? pt.2# there are a lot in the cave at 67,42", x = 67, y = 42, zone = "Winterspring" },
			[12] = { str = "12. Run back to Everlook and turn in #TURNINAre We There, Yeti? pt.2# accept #ACCEPTAre We There, Yeti? pt.3#" },
			[13] = { str = "13. Go just east of the Inn and scare Legacki for #DOQUESTAre We There, Yeti? pt.3#" },
			[14] = { str = "14. Go east of Winterspring to 66,34 and kill the furlbogs there for #DOQUESTWinterfall Activity# and part of #DOQUESTThreat of the Winterfall#", x = 66, y = 34, zone = "Winterspring" },
			[15] = { str = "15. Hopefully you’ll find an #NPCEmpty Firewater Flask# on one of them which starts #ACCEPTWinterfall Firewater#" },
			[16] = { str = "16. Run up to Starfall Village at 51,30 and turn in #TURNINTo Winterspring!# accept #ACCEPTThe Ruins of Kel'Theril#", x = 51, y = 30, zone = "Winterspring" },
			[17] = { str = "17. Turn in #TURNINEnraged Wildkin pt.1# SKIP part 2 for now also turn in #TURNINThe Ruins of Kel'Theril# accept #ACCEPTTroubled Spirits of Kel'Theril#" },
			[18] = { str = "18. Grab the relic at 55,42 for #DOQUESTTroubled Spirits of Kel'Theril# dismiss pet before you open them then run and FD. 2nd relic is at 53,43. 3rd at 52,41 4th at 50,41" },
			[19] = { str = "19. Go west to 39,43 and kill furlbog here for #DOQUESTThreat of the Winterfall# also make sure you have your 10 feathers for #DOQUESTMoontouched Wildkin#", x = 39, y = 43, zone = "Winterspring" },
			[20] = { str = "20. Go to 31,45 and turn in #TURNINStrange Sources# #TURNINThreat of the Winterfall# and #TURNINWinterfall Firewater# accept #ACCEPTFalling to Corruption#", x = 31, y = 45, zone = "Winterspring" },
			[21] = { str = "21. Run to 27,34 and turn in #TURNINWinterfall Activity#", x = 27, y = 34, zone = "Winterspring" },
			[22] = { str = "22. You should now be 25-30% into level 55" },
			[23] = { str = "23. Run through the tunnel to Felwood" },
			[24] = { str = "24. Go to 60,5 and touch the cauldron at the camp which turns in #TURNINFalling to Corruption# accept #ACCEPTMystery Goo#", x = 60, y = 5, zone = "Winterspring" },
			[25] = { str = "25. Hearth to Everlook then fly to Darnassus" },
			[26] = { str = "26. In Rut’theran Village turn in #TURNINMoontouched Wildkin# 55,92 accept #ACCEPTFind Ranshalla#", x = 55, y = 92, zone = "Darnassus" },
			[27] = { str = "27. Go into Darnassus up to 34,8 in the big tower and turn in #TURNINThe New Frontier pt.1# accept #ACCEPTThe New Frontier pt.2# go down 1 floor and turn that in, accept #ACCEPTRabine Saturna#", x = 34, y = 8, zone = "Darnassus" },
			[28] = { str = "28. Fly to Moonglade to 51,45 and turn in #TURNINRabine Saturna# accept #ACCEPTWasteland#", x = 51, y = 45, zone = "Moonglade" },
			[29] = { str = "29. Fly to Auberdine, sail to Menethil and fly to IF, make it your home. Make sure you have your black dragonflight molt" },
			[30] = { str = "30. Go to 75,23 and turn in #TURNINA Little Slime Goes A Long Way pt.2#", x = 75, y = 23, zone = "Ironforge" },
			[31] = { str = "31. Go to 38,55 in the throne room and accept #ACCEPTThe Smoldering Ruins of Thaurissan pt.1# then click on her and listen to the story and turn it back in, accept #ACCEPTThe Smoldering Ruins of Thaurissan pt.2#", x = 38, y = 55, zone = "Ironforge" },
			[32] = { str = "32. In front of the FP accept #ACCEPTTaking Back Silithus#" },
			[33] = { str = "33. Fly to Lakeshire" },
			[34] = { str = "34. Run north to 46,6 and enter the Burning Steppes", x = 46, y = 6, zone = "Redridge Mountains" },
		}
	},

-----------55-56 Burning Steppes
	--[508] = {
	[5556] = {
		title = "55-56 Burning Steppes",
		--n = "55-56 Burning Steppes",
		--pID = 507, nID = 509,
		--itemCount = 29,
		items = {
			[1] = { str = "1. 55-56 Burning Steppes" },
			[2] = { str = "2. Go to 83,63 and follow the path up and grab the FP", x = 83, y = 63, zone = "Burning Steps" },
			[3] = { str = "3. Accept #ACCEPTExtinguish the Firegut# and #ACCEPTFIFTY! YEP!#" },
			[4] = { str = "4. In front of the broken house, accept #ACCEPTDragonkin Menace# This is the start of the Onyxia key chain" },
			[5] = { str = "5. Start killing ogres all over the mountain at 81,42 for #DOQUESTExtinguish the Firegut# then run back to 84,68 and turn it in, accept #ACCEPTGor'tesh the Brute Lord#", x = 81, y = 42, zone = "Burning Steps" },
			[6] = { str = "6. Go NW to around 66,40 and collect the ruins that look like tombstones for #DOQUESTThe Smoldering Ruins of Thaurissan pt.2#", x = 66, y = 40, zone = "Burning Steps" },
			[7] = { str = "7. Run up to 65,24 and go in the cave, turn in #TURNINYuka Screwspigot# SKIP the rest", x = 65, y = 24, zone = "Burning Steps" },
			[8] = { str = "8. Outside accept #ACCEPTTablet of the Seven# and #ACCEPTBroodling Essence#" },
			[9] = { str = "9. Go to 54,40 and touch the dwarf statue for #DOQUESTTablet of the Seven#", x = 54, y = 40, zone = "Burning Steps" },
			[10] = { str = "10. Go west to 43,46 to blackrock stronghold or south to 49,55 the pillar of ash and kill the orcs for #DOQUESTFIFTY! YEP!# they drop in large amounts", x = 43, y = 46, zone = "Burning Steps" },
			[11] = { str = "11. While in the pillar of ash at 40,56 you should kill Gor’tesh for #DOQUESTGor'tesh the Brute Lord#", x = 40, y = 56, zone = "Burning Steps" },
			[12] = { str = "12. Get a group if you can for #DOQUESTDragonkin Menace# and then kill the mobs for it just NE of the camp along the east wall. It’s soloable but cutting it Also get 8 of the broodlings for #DOQUESTBroodling Essence# by using the device on them before you attack them." },
			[13] = { str = "13. Go to the cave at 94,31 and accept #ACCEPTA Taste of Flame# then give him the molt and hand the quest back in. SKIP the next part", x = 94, y = 31, zone = "Burning Steps" },
			[14] = { str = "14. Run back up to 65,23 and turn in #TURNINTablet of the Seven# and #TURNINBroodling Essence# accept #ACCEPTFelnok Steelspring#", x = 65, y = 23, zone = "Burning Steps" },
			[15] = { str = "15. Ride back to 84,68 and next to the griffin turn in #TURNINFIFTY! YEP!# and #TURNINGor'tesh the Brute Lord# accept #ACCEPTOgre Head On A Stick = Party#", x = 84, y = 68, zone = "Burning Steps" },
			[16] = { str = "16. In front of the broken house, turn in #TURNINDragonkin Menace# accept #ACCEPTThe True Masters pt.1#" },
			[17] = { str = "17. Run up to the top of the mountin at 80,45 and click the soft dirt pile for #DOQUESTOgre Head On A Stick = Party# then run back to 84,68 and turn it in", x = 80, y = 45, zone = "Burning Steps" },
			[18] = { str = "18. Fly to Lakeshire and run to the town hall at 29,44 and turn in #TURNINThe True Masters pt.1# accept #ACCEPTThe True Masters pt.2#", x = 29, y = 44, zone = "Redridge Mountains" },
			[19] = { str = "19. Fly to SW" },
			[20] = { str = "20. Go to 78,18 into the SW keep and turn in #TURNINThe True Masters pt.2# accept #ACCEPTThe True Masters pt.3# then talk to the lady and then turn it back in and accept #ACCEPTThe True Masters pt.4#", x = 78, y = 18, zone = "Stormwind City" },
			[21] = { str = "21. Fly back to Lakeshire and go to the townhall at 29,44 and turn in #TURNINThe True Masters pt.4# accept #ACCEPTThe True Masters pt.5#", x = 29, y = 44, zone = "Redridge Mountains" },
			[22] = { str = "22. Fly to the Burning Steppes and turn in #TURNINThe True Masters pt.5# when you land and accept #ACCEPTThe True Masters pt.6#" },
			[23] = { str = "23. Run up to 64,23 and listen to ragged john then run back to 84,68 and turn in #TURNINThe True Masters pt.6# I SKIP the next part, do it later if you’re worried about speed leveling. That was an easy 30k xp for doing nothing and your ony key chain is started.", x = 64, y = 23, zone = "Burning Steps" },
			[24] = { str = "24. You should be about 10k from level 56, go grind until 5k on the orcs at 49,55", x = 49, y = 55, zone = "Burning Steps" },
			[25] = { str = "25. Hearth to IF" },
			[26] = { str = "26. Go to the throne room at 38,55 and turn in  #TURNINThe Smoldering Ruins of Thaurissan pt.2#", x = 38, y = 55, zone = "Ironforge" },
			[27] = { str = "27. You should now be level 56, get new skills" },
			[28] = { str = "28. Fly to Menethil and sail to Theramore" },
			[29] = { str = "29. Fly to Gadgetzan" },
		}
	},

-----------56-56 Tanaris
	--[509] = {
	[5655] = {
		title = "56-56 Tanaris",
		--n = "56-56 Tanaris",
		--pID = 508, nID = 510,
		--itemCount = 9,
		items = {
			[1] = { str = "1. 56-56 Tanaris" },
			[2] = { str = "2. Go to the NW side of town and scare sprinkle for #DOQUESTAre We There, Yeti? pt.3#" },
			[3] = { str = "3. Make Gadgetzan your home" },
			[4] = { str = "4. To the south of lost rigger cove at 70,49 is a bunch of stones in a circle, Loot the stuff from the blue backpack and use the book to summon Aquementas. He’s a level 54 water elemental", x = 70, y = 49, zone = "Tanaris" },
			[5] = { str = "5. Hearth to Gadgetzan or die if it’s not up yet." },
			[6] = { str = "6. Fly to Un’goro" },
			[7] = { str = "7. Find Quixxil and scare him for #DOQUESTAre We There, Yeti? pt.3#" },
			[8] = { str = "8. Go to the back of the cave and turn in #TURNINAquementas# accept #ACCEPTLinken's Adventure# and turn it in just outside the cave by the big tree SKIP the next part" },
			[9] = { str = "9. Fly to Silithus" },
		}
	},

-----------56-56 Silithus
	--[510] = {
	[5656] = {
		title = "56-56 Silithus",
		--n = "56-56 Silithus",
		--pID = 509, nID = 511,
		--itemCount = 42,
		items = {
			[1] = { str = "1. 56-56 Silithus" },
			[2] = { str = "2. Near the moonwell accept #ACCEPTThe Twilight Mystery#" },
			[3] = { str = "3. In front of the Inn, turn in #TURNINTaking Back Silithus# accept #ACCEPTSecuring the Supply Lines#" },
			[4] = { str = "4. SKIP the quest on the sign unless you get a group" },
			[5] = { str = "5. Make Cenarion Hold your home" },
			[6] = { str = "6. Upstairs accept #ACCEPTDeadly Desert Venom#" },
			[7] = { str = "7. There seems to be a lot of white quests because there's many AQ quests that you don’t have to worry about yet." },
			[8] = { str = "8. Go do #DOQUESTSecuring the Supply Lines# and #DOQUESTDeadly Desert Venom# North and NE of town all around 55,24 the dredges, scorpids, and skitterers for these 2 quests are all over this area.", x = 55, y = 24, zone = "Silithus" },
			[9] = { str = "9. Run up to 81,18 and turn in #TURNINWasteland# accept #ACCEPTThe Spirits of Southwind#", x = 81, y = 18, zone = "Silithus" },
			[10] = { str = "10. Run up NW to around 22.9 and pick up the twilight tablet fragments for #DOQUESTThe Twilight Mystery# They litter this spot", x = 22, y = 9, zone = "Silithus" },
			[11] = { str = "11. Hearth to Cenarion Hold" },
			[12] = { str = "12. Up stairs turn in #TURNINDeadly Desert Venom# accept #ACCEPTNoggle's Last Hope#" },
			[13] = { str = "13. In front of the Inn, turn in #TURNINSecuring the Supply Lines# accept #ACCEPTStepping Up Security#" },
			[14] = { str = "14. Go next to the moonwell and turn in #TURNINThe Twilight Mystery# accept #ACCEPTThe Deserter#" },
			[15] = { str = "15. You should be about 30-35% into level 56" },
			[16] = { str = "16. Go SE to 62,53 and kill the undead mobs here for #DOQUESTThe Spirits of Southwind# be careful when they die they spawn 1-2 bugs", x = 62, y = 53, zone = "Silithus" },
			[17] = { str = "17. Kill the pincers for #DOQUESTNoggle's Last Hope# and drudges for #DOQUESTThe Deserter# south of here around 56,58", x = 56, y = 58, zone = "Silithus" },
			[18] = { str = "18. Go to the cave at 67,69 and turn in #TURNINThe Deserter# accept #ACCEPTThe Twilight Lexicon#", x = 67, y = 69, zone = "Silithus" },
			[19] = { str = "19. You can find flayers and stalkers outside of the cave for #DOQUESTNoggle's Last Hope# they are also both around 43,72 on the other side of the hive", x = 43, y = 72, zone = "Silithus" },
			[20] = { str = "20. Hearth back to Cenarion Hold or die so you end up there" },
			[21] = { str = "21. Go upstairs and turn in for #TURNINNoggle's Last Hope# accept #ACCEPTNoggle's Lost Satchel#" },
			[22] = { str = "22. Outside the Inn, turn in #TURNINStepping Up Security#" },
			[23] = { str = "23. Go to 29,35 and kill Twilight Keeper Manya for #DOQUESTThe Twilight Lexicon# she fears a bit. She’s at the SE corner of came", x = 29, y = 35, zone = "Silithus" },
			[24] = { str = "24. Go to 41,41 and kill Twilight Keeper Havanuth for #DOQUESTThe Twilight Lexicon# he’s on the east side of camp, he has a nasty aoe", x = 41, y = 41, zone = "Silithus" },
			[25] = { str = "25. Go all the way down south to the little camp at 42,90 and go up the hill behind it, you’ll find Deathclasp, in the middle of the path on the wall is a pouch, grab it when deathclasp is in the back for #DOQUESTNoggle's Lost Satchel#", x = 42, y = 90, zone = "Silithus" },
			[26] = { str = "26. Head to the SW to 16,87 and kill Twilight Keeper Exeter for #DOQUESTThe Twilight Lexicon# he’s at the SW corner of camp", x = 16, y = 87, zone = "Silithus" },
			[27] = { str = "27. Go back to the cave at 67,69 and turn in #TURNINThe Twilight Lexicon# accept #ACCEPTA Terrible Purpose# He also offers another quest for 10 twilight texts, this is more for cen circle rep later on", x = 67, y = 69, zone = "Silithus" },
			[28] = { str = "28. Run up to 81,18 and turn in #TURNINThe Spirits of Southwind# accept #ACCEPTHive in the Tower#", x = 81, y = 18, zone = "Silithus" },
			[29] = { str = "29. Go to the top of the tower at 61,52 Be careful 3 bugs spawn when you enter. Shift right click the pod because as soon as you open it some amushers spawn. Kill at least 1 and loot it for #DOQUESTHive in the Tower#", x = 61, y = 52, zone = "Silithus" },
			[30] = { str = "30. Go up to 81,18 and turn in #TURNINHive in the Tower# accept #ACCEPTUmber, Archivist#", x = 81, y = 18, zone = "Silithus" },
			[31] = { str = "31. Hearth to Cenarion Hold" },
			[32] = { str = "32. ......." },
			[33] = { str = "33. Go upstairs and turn in #TURNINNoggle's Lost Satchel#" },
			[34] = { str = "34. Go into the long building and turn in #TURNINA Terrible Purpose#" },
			[35] = { str = "35. Fly to Moonglade" },
			[36] = { str = "36. Go to 44,35 and turn in #TURNINUmber, Archivist# accept #ACCEPTUncovering Past Secrets#", x = 44, y = 35, zone = "Moonglade" },
			[37] = { str = "37. Run over to 51,44 and turn in #TURNINUncovering Past Secrets#", x = 44, y = 35, zone = "Moonglade" },
			[38] = { str = "38. You should now be 80-85% into leveling" },
			[39] = { str = "39. Fly to Auberdine and sail to Menethil then fly to IF" },
			[40] = { str = "40. Make IF your home, then find the wandering commander dwarf and accept  #ACCEPTA Call To Arms: The Plaguelands!#" },
			[41] = { str = "41. Fly to Southshore" },
			[42] = { str = "42. Run north into Alterac Mountains and over NE to 80,34 and run into Western Plaguelands (WPL)", x = 80, y = 34, zone = "Alterac Mountains" },
		}
	},

------------56-57 Western Plaguelands
	--[511] = {
	[5657] = {
		title = "56-57 Western Plaguelands",
		--n = "56-57 Western Plaguelands",
		--pID = 510, nID = 512,
		--itemCount = 44,
		items = {
			[1] = { str = "1. 56-57 Western Plaguelands" },
			[2] = { str = "2. Next to the shack accept #ACCEPTA Plague Upon Thee pt.1#" },
			[3] = { str = "3. Grab the FP" },
			[4] = { str = "4. Whenever you come back to camp here always check the vendor for the stormshroud pants recipe. It’s like 1.3g and you can easily sell it for 10 or 20g+ It’s a limited recipe that restocks 1 every hour." },
			[5] = { str = "5. Go to the tent and turn in #TURNINA Call To Arms: The Plaguelands!#, accept #ACCEPTClear The Way#" },
			[6] = { str = "6. Go to the 3 Argent Dawn people near the other tent and turn in #TURNINThe Everlook Report# and also complete #ACCEPTArgent Dawn Commission# it’s not a quest you had she just uses it to give you the trinket which you should always wear when in WPL and EPL because it gives you AD rep and allows the scourge tokens to drop, which she also has 3 new quests on those for turn ins. You most likely won’t get anything past the first quest as the rest are mainly in the instances." },
			[7] = { str = "7. Save the tokens until I say to hand them in" },
			[8] = { str = "8. Go NE to around 51,78 and grind the ghouls here until you got enough for #DOQUESTClear The Way#", x = 51, y = 78, zone = "Western Plaguelands" },
			[9] = { str = "9. Go back to Chillwind Camp at 42,84 and turn in #TURNINClear The Way# accept #ACCEPTAll Along the Watchtowers# and #ACCEPTThe Scourge Cauldrons#", x = 42, y = 84, zone = "Western Plaguelands" },
			[10] = { str = "10. Turn around and turn in #TURNINThe Scourge Cauldrons# accept #ACCEPTTarget: Felstone Field#" },
			[11] = { str = "11. You should now be about 5-10k from level 57" },
			[12] = { str = "12. Go back NE to 48,72 and go over the bridge", x = 48, y = 72, zone = "Western Plaguelands" },
			[13] = { str = "13. Just in the town on the left at 47,71 is the 4th tower for #DOQUESTAll Along the Watchtowers#, there are elites inside but you can stand out of LOS on the edge and mark the doors easily. 1st tower West of here at 40,71. 2nd tower NE of here at 42,66. 3rd tower NE of here at 44,63. Just behind this tower.", x = 47, y = 71, zone = "Western Plaguelands" },
			[14] = { str = "14. Go NW to 37,56 to Felstone field, kill #NPCCauldron Lord Bilemaw# for his cauldron key. Then go right click the cauldron and turn in #TURNINTarget: Felstone Field# accept #ACCEPTReturn to Chillwind Camp#", x = 37, y = 56, zone = "Western Plaguelands" },
			[15] = { str = "15. Theres 2 houses on the NE side of the field at 38,54, enter the northern house and go upstairs. Accept #ACCEPTBetter Late Than Never pt.1#", x = 38, y = 54, zone = "Western Plaguelands" },
			[16] = { str = "16. Go in the barn next door and grab the box on the floor and turn in #TURNINBetter Late Than Never pt.1# accept #ACCEPTBetter Late Than Never pt.2#" },
			[17] = { str = "17. Run back to Chillwind Camp at 42,84 and turn in #TURNINAll Along the Watchtowers#, accept #ACCEPTScholomance# SKIP the other unless you get about 10-20 people.", x = 42, y = 84, zone = "Western Plaguelands" },
			[18] = { str = "18. Turn in #TURNINScholomance# just behind him, accept #ACCEPTSkeletal Fragments Bones# for this will take a while and drop off any skeletons." },
			[19] = { str = "19. Near the FP turn in #TURNINReturn to Chillwind Camp# accept #ACCEPTTarget: Dalson's Tears#" },
			[20] = { str = "20. Go up to 46,52 to Dalson’Tears, kill #NPCCauldron Lord Malvinious# for his cauldron key. Then go right click the cauldron and turn in #TURNINTarget: Dalson's Tears# accept #ACCEPTReturn to Chillwind Camp#", x = 46, y = 52, zone = "Western Plaguelands" },
			[21] = { str = "21. Enter the barn here at 47,50 and touch the diary on the floor and complete it, another quest that isn’t a quest.", x = 47, y = 50, zone = "Western Plaguelands" },
			[22] = { str = "22. Go behind the barn and look for a Wandering Skeleton and get Dalson Outhouse Key off of him. Use this to open the outhouse back here and kill Farmer Dalson and get his Dalson Cabinet Key. Use the key on the locked cabinet upsairs in the house now at 47,49 next to the barn and complete the quest #TURNINLocked Away#", x = 47, y = 49, zone = "Western Plaguelands" },
			[23] = { str = "23. Go back to Chillwind Camp at 42,84 and turn in #TURNINReturn to Chillwind Camp# accept #ACCEPTTarget: Writhing Haunt#", x = 42, y = 84, zone = "Western Plaguelands" },
			[24] = { str = "24. Hearth to IF then fly to SW" },
			[25] = { str = "25. Go to the building at 48,30 on the 2nd floor of the cathedral area and turn in #TURNINBetter Late Than Never pt.2# accept #ACCEPTGood Natured Emma#", x = 48, y = 30, zone = "Stormwind" },
			[26] = { str = "26. Emma travels between the cathedral and the trade district, find her and turn in #TURNINGood Natured Emma# accept #ACCEPTGood Luck Charm#" },
			[27] = { str = "27. Go into the keep at 78,17 and accept #ACCEPTThe First and the Last#", x = 78, y = 17, zone = "Stormwind" },
			[28] = { str = "28. Go to 75,79 and turn in #TURNINThe First and the Last# accept #ACCEPTHonor the Dead# then turn it right back in, accept #ACCEPTFlint Shadowmore#", x = 75, y = 79, zone = "Stormwind" },
			[29] = { str = "29. Fly back to WPL" },
			[30] = { str = "30. In front of the house turn in #TURNINFlint Shadowmore# accept #ACCEPTThe Eastern Plagues#" },
			[31] = { str = "31. Go back to Felstone field to the house upstairs at 38,54 and turn in #TURNINGood Luck Charm# accept #ACCEPTTwo Halves Become One# Go outside and look for a jabbering ghoul. You can’t miss him he carry’s a pitchfork. Keep clearing in front of the house until you find him. This will give you a good time to get those skeletal fragments", x = 38, y = 54, zone = "Western Plaguelands" },
			[32] = { str = "32. Combine the halves and go back upstairs and turn in #TURNINTwo Halves Become One#" },
			[33] = { str = "33. Go SE to 53,65 to Writhing Haunt, kill #NPCCauldron Lord Razarch# for his cauldron key. Then go right click the cauldron and turn in #TURNINTarget: Writhing Haunt# accept #ACCEPTReturn to Chillwind Camp#", x = 53, y = 65, zone = "Western Plaguelands" },
			[34] = { str = "34. In the house at 54,65 accept #ACCEPTThe Wildlife Suffers Too pt.1# now go north of the haunt and kill the diseased wolves. Don’t go any farther east to find these just go North, maybe NW some.", x = 54, y = 65, zone = "Western Plaguelands" },
			[35] = { str = "35. Go back to 54,65 and turn in #TURNINThe Wildlife Suffers Too pt.1# accept #ACCEPTThe Wildlife Suffers Too pt.2#", x = 54, y = 65, zone = "Western Plaguelands" },
			[36] = { str = "36. Go back to Chillwind Camp at 42,84 and turn in #TURNINReturn to Chillwind Camp# accept #ACCEPTTarget: Gahrron's Withering#", x = 42, y = 84, zone = "Western Plaguelands" },
			[37] = { str = "37. Go just north of the Writhing Haunt between the mountains on the map at, 52,56 and kill diseased grizzleys on your way down to 62,58 for #DOQUESTThe Wildlife Suffers Too pt.2#", x = 52, y = 56, zone = "Western Plaguelands" },
			[38] = { str = "38. Go NE to 62,58 to Gahrron’s Withering, kill #NPCCauldron Lord Soulwrath# for his cauldron key. Then go right click the cauldron and turn in #TURNINTarget: Gahrron's Withering# accept #ACCEPTReturn to Chillwind Camp#", x = 62, y = 58, zone = "Western Plaguelands" },
			[39] = { str = "39. Go back to 54,65 and turn in #TURNINThe Wildlife Suffers Too pt.2# accept #ACCEPTGlyphed Oaken Branch#", x = 54, y = 65, zone = "Western Plaguelands" },
			[40] = { str = "40. If you haven’t finished Skeletal Fragments yet go to the crypt at 54,79 and kill the skeletons until you have 15 fragments", x = 54, y = 79, zone = "Western Plaguelands" },
			[41] = { str = "41. Go back to Chillwind Camp at 42,84 and turn in #TURNINReturn to Chillwind Camp#", x = 42, y = 84, zone = "Western Plaguelands" },
			[42] = { str = "42. Turn around to the guy in front of the tent, and complete the quest #TURNINMission Accomplished!# no link for it cuz it’s not a quest again lol. Now see that running back and forth seemed out of the way but there was a huge xp boost at the end, and nice xp throughout." },
			[43] = { str = "43. To your right turn in #TURNINSkeletal Fragments# SKIP the next part unless you want to start on your scholo key." },
			[44] = { str = "44. Run east to 70,50 and enter the Eastern Plaguelands (EPL)", x = 70, y = 50, zone = "Western Plaguelands" },
		}
	},

-----------57-58 Eastern Plaguelands
	--[512] = {
	[5758] = {
		title = "57-58 Eastern Plaguelands",
		--n = "57-58 Eastern Plaguelands",
		--pID = 511, nID = 513,
		--itemCount = 21,
		items = {
			[1] = { str = "1. 57-58 Eastern Plaguelands" },
			[2] = { str = "2. Run up the west coast to 67,4 and accept the 3 quests #ACCEPTDemon Dogs# #ACCEPTBlood Tinged Skies# and #ACCEPTCarrion Grubbage#", x = 67, y = 4, zone = "Eastern Plaguelands" },
			[3] = { str = "3. These are annoying quests that can take a while. Anytime from now until these are done, kill any plaguehound runts, carrion worms, or plaguebats." },
			[4] = { str = "4. From here on down to the bigger area, kill any dogs, worms, and bats. Focus on them while you head to the next step" },
			[5] = { str = "5. Keep killing the dogs and bats and head over to the skeleton at 28,74 open it and grab the insignia for #DOQUESTThe Eastern Plagues# then run up a bit further to the next skeleton at 27,74 and grab the insignia, it’s practically right in front of him and you will also get the blightcaller found complete message. Now go down near the road to 28,79 and loot the last insignia off the skeleton", x = 28, y = 74, zone = "Eastern Plaguelands" },
			[6] = { str = "6. Focus on the dogs and bats while you head to Darrowshire at 36,90 in the broken down house. Turn in #TURNINSister Pamela# accept #ACCEPTPamela's Doll# then head towards the houses here, in any of the houses can be any of the 3 doll parts. They are random. Ghosts spawn when you get near the parts so be aware. Once you have all 3 parts combine them and go back to 36,90 and turn in #TURNINPamela's Doll# accept #ACCEPTAuntie Marlene# and #ACCEPTUncle Carlin#", x = 36, y = 90, zone = "Eastern Plaguelands" },
			[7] = { str = "7. Look on your map at 48,76 This lines up with that middle ridge mountain. Don’t go past this spot east until you have your plaguehound runt kills for #DOQUESTDemon Dogs# and plaguebats for #DOQUESTBlood Tinged Skies# because there is none past that point.", x = 48, y = 76, zone = "Eastern Plaguelands" },
			[8] = { str = "8. Don’t forget to kill the grubs along the way too for #DOQUESTCarrion Grubbage#, they’re not as important because they’re all over." },
			[9] = { str = "9. Kill Plaguehounds for Demon Dogs all around 56,57 this is north of the scar and south of blackwood lake. Don’t forget the grubs", x = 56, y = 57, zone = "Eastern Plaguelands" },
			[10] = { str = "10. Kill Frenzied Plaguehounds for #DOQUESTDemon Dogs#  all around 61,41 this is north of blackwood lake but now west of it.", x = 61, y = 41, zone = "Eastern Plaguelands" },
			[11] = { str = "11. Head to lights hope chapel at 81,58 if you still need grub meat for #DOQUESTCarrion Grubbage#, then kill them as you", x = 81, y = 58, zone = "Eastern Plaguelands" },
			[12] = { str = "12. Get the FP" },
			[13] = { str = "13. Turn in #TURNINUncle Carlin# accept #ACCEPTDefenders of Darrowshire#" },
			[14] = { str = "14. Turn around and turn in #TURNINDuke Nicholas Zverenhoff#" },
			[15] = { str = "15. Run SW to 79,63 and accept #ACCEPTZaeldarr the Outcast#", x = 79, y = 63, zone = "Eastern Plaguelands" },
			[16] = { str = "16. Fly back to EPL" },
			[17] = { str = "17. In front of the house turn in #TURNINThe Eastern Plagues# accept #ACCEPTThe Blightcaller Cometh#" },
			[18] = { str = "18. If you’re within 6,600 to level then Hearth to IF and fly to SW, if not then grind until you’re within range." },
			[19] = { str = "19. Go to 78,18 in the keep and turn in #TURNINThe Blightcaller Cometh# now I SKIP the next part but it’s a good quest to do at 60", x = 78, y = 18, zone = "Eastern Plaguelands" },
			[20] = { str = "20. Go get new skills" },
			[21] = { str = "21. Fly back to WPL" },
		}
	},

-----------58-58 Western Plaguelands
	--[513] = {
	[5857] = {
		title = "58-58 Western Plaguelands",
		--n = "58-58 Western Plaguelands",
		--pID = 512, nID = 514,
		--itemCount = 9,
		items = {
			[1] = { str = "1. 58-58 Western Plaguelands" },
			[2] = { str = "2. Go NE to the house at 49,78 and go upstairs. Turn in #TURNINPamela's Doll# accept #ACCEPTA Strange Historian#", x = 49, y = 78, zone = "Western Plaguelands" },
			[3] = { str = "3. Just north of the house at 49,76 you’ll see an off color gravestone. Loot it and get the wedding ring for #DOQUESTA Strange Historian#", x = 49, y = 76, zone = "Western Plaguelands" },
			[4] = { str = "4. Go in the west entrance to Andorhal at 39,71and you should see the only full building, looks like an Inn at 39,68. Go upstairs and turn in #TURNINA Strange Historian# accept #ACCEPTThe Annals of Darrowshire# also accept #ACCEPTA Matter of Time#", x = 39, y = 68, zone = "Western Plaguelands" },
			[5] = { str = "5. Now look all around the city here for busted up silo’s with a blue light coming out of them. Use the silo horn to summon the worms, it spawns 1-3 mobs for #DOQUESTA Matter of Time#. Once you kill the last one they have a tendency to spawn another. They’re more on the East side of town" },
			[6] = { str = "6. Go to the Town Hall near all the mobs in the middle of town, you can sneak in from the SW side. Grab the books on the floor until you get the #ACCEPTThe Annals of Darrowshire# Some will spawn mobs" },
			[7] = { str = "7. Go back to the Inn at 39,68 and to the top floor, turn in #TURNINA Matter of Time# accept #ACCEPTCounting Out Time# also turn in #TURNINThe Annals of Darrowshire# accept #ACCEPTBrother Carlin#", x = 39, y = 68, zone = "Western Plaguelands" },
			[8] = { str = "8. Go outside and look around the busted houses for little metal lunchboxes for #DOQUESTCounting Out Time#" },
			[9] = { str = "9. Go back to the Inn at 39,68 and turn in #TURNINCounting Out Time# you can now repeat this quest for a dampener. This is used vs the 61 elite", x = 39, y = 68, zone = "Western Plaguelands" },
		}
	},

-----------58-58 Eastern Plaguelands
	--[514] = {
	[5858] = {
		title = "58-58 Eastern Plaguelands",
		--n = "58-58 Eastern Plaguelands",
		--pID = 513, nID = 515,
		--itemCount = 18,
		items = {
			[1] = { str = "1. 58-58 Eastern Plaguelands" },
			[2] = { str = "2. Run out of here and into EPL up to the NW at 7,43 and turn in the 3 quests #TURNINDemon Dogs# #TURNINBlood Tinged Skies# and #TURNINCarrion Grubbage# accept #ACCEPTRedemption# then listen to him and turn it back in. Then accept #ACCEPTOf Forgotten Memories#", x = 7, y = 43, zone = "Eastern Plaguelands" },
			[3] = { str = "3. Go to the Undercroft at 28,86 and run behind it. Touch the dirt pile to summon Mercutio and 3 guards. Easiest way to do this is to kite him away from his buddies or get a group. Loot his body for the hammer for #DOQUESTOf Forgotten Memories#", x = 28, y = 86, zone = "Eastern Plaguelands" },
			[4] = { str = "4. Now go to the bottom of the crypt and kill the very big troll for #DOQUESTZaeldarr the Outcast# Only grab the scroll on the floor if u want" },
			[5] = { str = "5. Go back to 7,43 and turn in #TURNINOf Forgotten Memories# accept #ACCEPTOf Lost Honor#", x = 7, y = 43, zone = "Eastern Plaguelands" },
			[6] = { str = "6. Either Run to Light’s Hope Chapel or back to Chillwind and fly there" },
			[7] = { str = "7. Turn in #TURNINBrother Carlin# accept #ACCEPTVillains of Darrowshire#" },
			[8] = { str = "8. Go down to 79,63 and turn in #TURNINZaeldarr the Outcast#", x = 79, y = 63, zone = "Eastern Plaguelands" },
			[9] = { str = "9. Go down just North of Corin’s Crossing to 53,65 and grab the sword for #DOQUESTVillains of Darrowshire# It’s down in the scar. Don’t forget to do some of #DOQUESTDefenders of Darrowshire# at Corin’s Just get what you can", x = 53, y = 65, zone = "Eastern Plaguelands" },
			[10] = { str = "10. Go north to Blackwood Lake at 51,49 and grab the skull under the water for #DOQUESTVillains of Darrowshire#", x = 51, y = 49, zone = "Eastern Plaguelands" },
			[11] = { str = "11. Go NE to around 65,41 and kill the zombies for part of #DOQUESTDefenders of Darrowshire# there are quite a lot here you could probably finish", x = 65, y = 41, zone = "Eastern Plaguelands" },
			[12] = { str = "12. Go to the lake at 71,33 and grab the flag next to the cage, it’s hard to see and is laying flat for #DOQUESTOf Lost Honor#", x = 71, y = 33, zone = "Eastern Plaguelands" },
			[13] = { str = "13. Go NW to the tower at 56,24 and turn in #TURNINTroubled Spirits of Kel'Theril# SKIP the next part", x = 56, y = 24, zone = "Eastern Plaguelands" },
			[14] = { str = "14. Run West to 45,34 and loot the termite mounds here for #DOQUESTA Plague Upon Thee pt.1# until you get 100 termites, also kill ghouls to finish up #DOQUESTDefenders of Darrowshire#", x = 45, y = 34, zone = "Eastern Plaguelands" },
			[15] = { str = "15. Run to Lights Hope Chapel now" },
			[16] = { str = "16. Go by the tent and turn in #TURNIN“Defenders of Darrowshire”# and #TURNIN“Villains of Darrowshire”#" },
			[17] = { str = "17. Fly to WPL" },
			[18] = { str = "18. Next to the house turn in #TURNIN“A Plague Upon Thee pt.1”# accept #ACCEPT“A Plague Upon Thee pt.2”#" },
		}
	},

------------58-59 Western Plaguelands
	--[515] = {
	[5859] = {
		title = "58-59 Western Plaguelands",
		--n = "58-59 Western Plaguelands",
		--pID = 514, nID = 516,
		--itemCount = 19,
		items = {
			[1] = { str = "1. 58-59 Western Plaguelands" },
			[2] = { str = "2. Run up to 51,28 and accept #ACCEPT“Unfinished Business pt.1”#", x = 52, y = 30, zone = "Western Plaguelands" },
			[3] = { str = "3. Start heading back SW around 47,32 and clear your way into the mill. Right click the box and place the termintes, then click the barrel and turn in #TURNIN“A Plague Upon Thee pt.2”# accept #ACCEPT“A Plague Upon Thee pt.3”#", x = 47, y = 32, zone = "Western Plaguelands" },
			[4] = { str = "4. Go just south of 49,42 and kill 2 knights and mages for #DOQUEST“Unfinished Business pt.1”# then 51,43 for the hunters and medics", x = 49, y = 42, zone = "Western Plaguelands" },
			[5] = { str = "5. Go to 51,28 and turn in #TURNIN“Unfinished Business pt.1”# accept #ACCEPT“Unfinished Business pt.2”#", x = 51, y = 28, zone = "Western Plaguelands" },
			[6] = { str = "6. Go to 57,36 and kill Huntsman Radly for #DOQUEST“Unfinished Business pt.2”# then north to the tower at 55,23 and kill Cavalier Durgen at the top", x = 57, y = 36, zone = "Western Plaguelands" },
			[7] = { str = "7. Go straight out of the tower over the mountains to 51,28 and turn in #TURNIN“Unfinished Business pt.2”# doing the 3rd part #DOQUEST“Unfinished Business pt.3”# is optional. Some classes can do it easier than others. You have to run north to hearthglen and run up into the big tower in the center of town at 45,18 and look over the edge until it says complete.", x = 45, y = 18, zone = "Western Plaguelands" },
			[8] = { str = "8. Run back straight south over the mountains to 51,28 and turn in #TURNIN“Unfinished Business pt.3”#", x = 51, y = 28, zone = "Western Plaguelands" },
			[9] = { str = "9. Run into EPL and up to 7,43 and turn in #TURNIN“Of Lost Honor”# accept #ACCEPT“Of Love and Family pt.1”#", x = 7, y = 43, zone = "Eastern Plaguelands" },
			[10] = { str = "10. Go back to WPL and run/swim to the island Scholo is on at 65,75 and turn in #TURNIN“Of Love and Family pt.1”# SKIP the rest until you do strat", x = 65, y = 75, zone = "Western Plaguelands" },
			[11] = { str = "11. Go back to Chillwind Camp at 43,84 and turn in #TURNIN“A Plague Upon Thee pt.3”#", x = 43, y = 84, zone = "Western Plaguelands" },
			[12] = { str = "12. Now you want to do 2 things here. Get friendly with Argent Dawn and get 8-8.5k from leveling. You can do #DOQUEST“Alas, Andorhal”# if you can find a group, it’s not that hard but can take 5-10 people. This will give you an easy 8300 xp instead of grinding." },
			[13] = { str = "13. Now you want to go up to andorhal and just grind until you’re friendly, once you’re friendly go back to Chillwind Camp and turn in all your scourge tokens. This allows you to buy mana biscuits which restore mana and health and more than food can. If you still need to level then go grind on mobs in andorhal again until you’re 8-8.5k from level 59" },
			[14] = { str = "14. Once you’re 8k-8.5k from leveling, fly to Hinterlands and run all the way NE to the waterfall at 80,46 and jump off. Under the water loot the chest and finish #DOQUEST“Cortello’s Riddle pt.3”#", x = 80, y = 46, zone = "The Hinterlands" },
			[15] = { str = "15. Hearth to IF" },
			[16] = { str = "16. Go to the throne room at 43,52 and accept #ACCEPT“An Earnest Proposition”# (pick your class from the list) You have to have your classes tier 0 bracers in order to do this quest. You can buy it on AH", x = 43, y = 52, zone = "Ironforge" },
			[17] = { str = "17. Fly to Menethil and sail to Auberdine, fly to Darnassus" },
			[18] = { str = "18. Go to 35,8 on the 2nd floor and turn in #TURNIN“Glyphed Oaken Branch”#", x = 35, y = 8, zone = "Darnassus" },
			[19] = { str = "19. You should be level 59, fly to Winterspring" },
		}
	},

------------59-60 Winterspring
	--[516] = {
	[5960] = {
		title = "59-60 Winterspring",
		--n = "59-60 Winterspring",
		--pID = 515, nID = 516,
		--itemCount = 35,
		items = {
			[1] = { str = "1. 59-60 Winterspring" },
			[2] = { str = "2. On your left after entering turn in #TURNIN“Are We There, Yeti? pt.3”#" },
			[3] = { str = "3. Near the back are 2 horde, accept #ACCEPT“Luck Be With You”#" },
			[4] = { str = "4. Turn around and turn in #TURNIN“Felnok Steelspring”# accept #ACCEPT“Chillwind Horns”#" },
			[5] = { str = "5. #HUNTER4) Stable your pet#" },
			[6] = { str = "6. #HUNTER5) Run north to frostsaber rock at 51,15 and tame a Frostsaber Stalker for prowl and dash rank 3.#", x = 51, y = 15, zone = "Winterspring" },
			[7] = { str = "7. Do #DOQUEST“An Earnest Proposition”# just kill the sabers until you have 15 blood" },
			[8] = { str = "8. Go just SE of here around 55,18 and kill the chimera’s for #DOQUEST“Chillwind Horns”#", x = 55, y = 18, zone = "Winterspring" },
			[9] = { str = "9. #HUNTER8) Once you got that done, tame a Winterspring Screecher for Claw rank 8#" },
			[10] = { str = "10. Run to Starfall Village at 52,30 and accept #ACCEPT“Enraged Wildkin pt.1”#", x = 52, y = 30, zone = "Winterspring" },
			[11] = { str = "11. Run back to everlook $HUNTERand get your cat back out#" },
			[12] = { str = "12. Turn in #TURNIN“Chillwind Horns”# SKIP the other unless you want to go there" },
			[13] = { str = "13. Go south to 59,59 and touch the crate and turn in #TURNIN“Enraged Wildkin pt.1”# accept #ACCEPT“Enraged Wildkin pt.2”#", x = 59, y = 59, zone = "Winterspring" },
			[14] = { str = "14. Go back to the roat at 61,60 and touch the wagon, turn in #TURNIN“Enraged Wildkin pt.2”# accept #ACCEPT“Enraged Wildkin pt.3”# grab the box in the snow", x = 61, y = 60, zone = "Winterspring" },
			[15] = { str = "15. Run east again to 63,59 and turn in #TURNIN“Find Ranshalla”# accept #ACCEPT“Guardians of the Altar”#", x = 63, y = 59, zone = "Winterspring" },
			[16] = { str = "16. Now protect her while she does her thing. Make sure you get the feather off an owl for #DOQUEST“Enraged Wildkin pt.3”# When she stops in a cave, light the torch for her. If you don’t get the feather before you’re done keep killing until you got it." },
			[17] = { str = "17. Go south to 62,69 and loot the gems for #DOQUEST“Luck Be With You”# hunters and locks can use pet to distract mobs while you loot, other classes will have to group.", x = 62, y = 69, zone = "Winterspring" },
			[18] = { str = "18. Hearth to Everlook" },
			[19] = { str = "19. Turn in #TURNIN“Luck Be With You”# at the 2 horde near the back of everlook" },
			[20] = { str = "20. You should be about 25% into level 59 now." },
			[21] = { str = "21. Accept #ACCEPT“Cache of Mau'Ari”# if you want to. This just gives you an item which allows the mobs here to drop stuff which you can turn in for buffs" },
			[22] = { str = "22. Go up to Starfall Village at 52,30 and turn in #TURNIN“Enraged Wildkin pt.3”#", x = 52, y = 30, zone = "Winterspring" },
			[23] = { str = "23. Run to 31,45 and turn in #TURNIN“Mystery Goo”# accept #ACCEPT“Toxic Horrors”#", x = 31, y = 45, zone = "Winterspring" },
			[24] = { str = "24. Run into Felwood and go to 48,24 and kill toxic horrors for #DOQUEST“Toxic Horrors”# these also drop essence of waters", x = 48, y = 24, zone = "Felwood" },
			[25] = { str = "25. Fly to Rut’theran Village and go to the house at 55,92 and turn in #TURNIN“Guardians of the Altar”# accept #ACCEPT“Wildkin of Elune”#", x = 55, y = 92, zone = "Teldrassil" },
			[26] = { str = "26. Go in Darnassus and up to the top of the tower at 34,8 and turn in #TURNIN“Wildkin of Elune”#", x = 34, y = 8, zone = "Darnassus" },
			[27] = { str = "27. Fly back to Felwood" },
			[28] = { str = "28. Run back up into Winterspring and over to 31,45 turn in #TURNIN“Toxic Horrors”# accept #ACCEPT“Winterfall Runners”#", x = 31, y = 45, zone = "Winterspring" },
			[29] = { str = "29. Now to find the runners. They travel anywhere from the Timbermaw Cave east to 53,34 then up around the mountains north of everlook over to Winterfall Village. If you didn’t see them from the cave to here, head east. You don’t have to kill all 3", x = 53, y = 34, zone = "Winterspring" },
			[30] = { str = "30. Once you get the crate run back to 31,45 Turn in Winterfall Runners an ambush will come from the lake, if you don’t move from the tent they won’t aggro you. SKIP the next part unless you get a group", x = 31, y = 45, zone = "Winterspring" },
			[31] = { str = "31. Hearth to Everlook" },
			[32] = { str = "32. You should be 45-50% through level 59. Now I make sure I got my mana bisquits and I start grinding until im 6600 to level 60.  Anywhere is fine where there is a lot of mobs It’s all a matter of preference. I choose the owl wing thicket at 64,62 or anything north of everlook. I like to kill the furlbogs for timbermaw rep also.", x = 64, y = 62, zone = "Winterspring" },
			[33] = { str = "33. If you don’t want to grind this large amount then do BRD, scholo, or strat. You have a lot of quests in those spots to do" },
			[34] = { str = "34. Once you’re 6600 to 60 go to IF and turn in #TURNINAn Earnest Proposition#" },
			[35] = { str = "35. Grats on 60!" },
		}
	},
}
