--[[--------------------------------------------------
003_Alliance_40to50.lua
Authors: mrmr
Version: 1.04.3
------------------------------------------------------
Description: Guide Serie - 003 From Lvl 40 to Lvl 50
    1.04.1
        -- First Release
            Alliance's Guide
            from level 40 to lever 50
    1.04.2
    	-- no changes in here for this revision
	1.04.3
		-- Added color codes
			Fixed various spelling errors
	1.05.0
        -- Added Hunter Sepecfic steps
        -- Still do in this section add numbered steps to rest of this guide, add qoutes to Quests, add COORDS color to travel directions, and check to see if NPC color has been missed used
------------------------------------------------------
Connection:
--]]--------------------------------------------------

Table_003_Alliance_40to50 = {
-----------40-41 Badlands
	--[401] = {
	[4041] = {
		title = "40-41 Badlands",
		--n = "40-41 Badlands",
		--pID = 312, nID = 402,
		--itemCount = 36,
		items = {
			[1] = { str = "1. 40-41 Badlands" },
			[2] = { str = "2. Идите в точку 53,43 берите задание  #ACCEPT“Fiery Blaze Enchantment”#,  #ACCEPT“Mirages”#,  и  #ACCEPT“A Dwarf and His Tools”#", x = 53, y = 43, zone = "Badlands" },
			[3] = { str = "3. Дойдите до точки 42,52 и сдайте задание  #TURNIN“Martek the Exiled”#  берите следующее  #ACCEPT“Indurium”#", x = 45, y = 52, zone = "Badlands" },
			[4] = { str = "4. Возьмите задание  #ACCEPT“Barbecued Buzzard Wings”#  и  #ACCEPT“Pearl Diving”# (если вы купили ранее на аукционе жемчужины для задания) и сразу сдайте это задание." },
			[5] = { str = "5. Стервятники нужны для выполнения 2х заданий. Паком обитают в точке 16,60 у каргата так что убивайте их всякий раз когда увидите на своем пути." },
			[6] = { str = "6. Идите по координатам 25,44 возьмите задание  #ACCEPT“Study of the Elements: Rock pt.1”#  и  #ACCEPT“Coolant Heads Prevail”#,  задание сдайте  #TURNIN“Coolant Heads Prevail”#  берите следующее  #ACCEPT“Gyro… What?”#  затем сдайте и его (если купили предмет на аукционе).", x = 25, y = 44, zone = "Badlands" },
			[7] = { str = "7. НПС это задание может вам не сразу задание может появиться после выполнения некоторых заданий в этой локации  #ACCEPT“Liquid Stone”#  если есть нужные банки в инвентаре сдайте его обратно." },
			[8] = { str = "8. #HUNTERЗадание для охотников. Идите в точку 20,53 и приручите Ridge Stalker Patriarch и выучите способность питомца dash и prowl 2го ранга.#", x = 20, y = 53, zone = "Badlands"},
			[9] = { str = "9. Задание для охотников. Жмите #PICTUREHearth# в Thelsamar, #HUNTERзаберите кота обратно, НЕ ОТПУСКАЙТЕ ПЕТА идите обратно с катом в badlands#"},
			[10] = { str = "10. Убивайте мобов пока идете в точку 66,21 там откройте ящик для задания  #DOQUEST“Mirages”#", x = 66, y = 21, zone = "Badlands" },
			[11] = { str = "11. Идите к месту раскопок в точку 53,29 и убивайте дворфов для задания  #DOQUEST“A Dwarf and His Tools”#  Справа от ямы в точке 53,33 коснитесь записки в палатке что бы получить задание  #DOQUEST“A Sign of Hope”#", x = 53, y = 29, zone = "Badlands" },
			[12] = { str = "12. Гриндите мобов до точки 53,43 и сдайте задание  #TURNIN“Mirages”#  берите следующее  #ACCEPT“Scrounging”#", x = 53, y = 43, zone = "Badlands" },
			[13] = { str = "13. Так же сдайте задания  #TURNIN“A Dwarf and His Tools”#  и  #TURNIN“A Sign of Hope”#  берите следующую часть в Uldaman'e" },
			[14] = { str = "14. Гриндите мобов до точки 61,54 и возьмите задание  #ACCEPT“Tremors of the Earth”#  огры ходят от точки 62,70  до точки 29,56 босса убить легко либо выманить его с малым количеством охраны.", x = 61, y = 54, zone = "Badlands" },
			[15] = { str = "15. Идите на юг в точку 62,70 и убивайте огров для задания  #DOQUEST“Scrounging”#  тут может появиться босс из предыдущего задания.", x = 62, y = 70, zone = "Badlands" },
			[16] = { str = "16. Гриндите до точки 50,62, сдайте задание  #TURNIN“Find Agmond”#  и возьмите следующее  #ACCEPT“Murdaloc”#", x = 50, y = 62, zone = "Badlands" },
			[17] = { str = "17. Отправляйтесь немного южнее в лагерь гноллов и выполните задание  #DOQUEST“Murdaloc”#  и  #DOQUEST“Indurium”#" },
			[18] = { str = "18. Идите в точку 42,52 и сдайте задание  #TURNIN“Barbecued Buzzard Wings”#  и  #TURNIN“Indurium”#  берите следующее  #ACCEPT“News for Fizzle”#", x = 45, y = 52, zone = "Badlands" },
			[19] = { str = "19. Идите в точку 18,41 и убивайте lesser rock elementals для задания  #DOQUEST“Study of the Elements: Rock pt.1”#  и  #DOQUEST“Badlands Reagent Run”#", x = 18, y = 41, zone = "Badlands" },
			[20] = { str = "20. Вернитесь в точку 26,44 и сдайте задание  #TURNIN“Study of the Elements: Rock pt.1”#  берите следующее  #ACCEPT“Study of the Elements: Rock pt.2”#  и выполните его убивая rock elementals", x = 26, y = 44, zone = "Badlands" },
			[21] = { str = "21. Вернитесь в точку 26,44 и сдайте задание  #TURNIN“Study of the Elements: Rock pt.2”#  берите следующее  #ACCEPT“Study of the Elements: Rock pt.3”#", x = 26, y = 44, zone = "Badlands" },
			[22] = { str = "22. Убивайте Стервятников в точке 15,60 и Койотов в токе 33,62 для задания  #DOQUEST“Badlands Reagent Run”# если они вам еще нужны", x = 33, y = 62, zone = "Badlands" },
			[23] = { str = "23. Гриндите до точки 11,77 и убивайте огров для задания  #DOQUEST“Scrounging”#", x = 11, y = 77, zone = "Badlands" },
			[24] = { str = "24. Убивайте greater rock elementals в точке 14,88 для задлания  #DOQUEST“Study of the Elements: Rock#", x = 14, y = 88, zone = "Badlands" },
			[25] = { str = "25. Идите назад в точку 26,44 сдайте задание  #TURNIN“Study of the Elements: Rock pt.3”#  возьмите следующее  #ACCEPT“This Is Going To Be Hard pt.1”#  повернитесь и сдайте его, возьмите следующее задание  #ACCEPT“This Is Going To Be Hard pt.2”#  повернитесь и снова сдайте его, возьмите следующее задание  #ACCEPT“This Is Going To Be Hard pt.3”#", x = 26, y = 44, zone = "Badlands" },
			[26] = { str = "26. Убейте призванного элементаля он 45 уровня. Затем сдайте его и получите свой Nifty Stopwatch" },
			[27] = { str = "27. Идите в точку 53,43 и сдайте  #TURNIN“Scrounging”#", x = 53, y = 43, zone = "Badlands" },
			[28] = { str = "28. Идите в точку 61,54 и сдайте заадние  #TURNIN“Tremors of the Earth”# следующее задание ПРОПУСТИТЕ", x = 61, y = 54, zone = "Badlands" },
			[29] = { str = "29. Сейчас у вас должен быть 41 уровень, если вы не получили 41 уровень идите на восток и гриндите детенышей драконов the whelps. Если вы получили 41 уровень на велпах то желательно еще погриндить их тут минут 30 что был запас по опыту если вы не выбили с них heart для задания  #DOQUEST“Fiery Blaze Enchantment”#  за это время то бросьте это задание." },
			[30] = { str = "30. Жмите Hearth в Thelsamar" },
			[31] = { str = "31. Идите в дом за гостиницей и сдайте задание  #TURNIN“Badlands Reagent Run”#  берите часть заданий относящиеся к Uldaman" },
			[32] = { str = "32. Бегите в точку 65,65 и сдайте задание  #TURNIN“Murdaloc”#  берите еще задание Uldaman. Сейчас я уже заполнил полоску опыта на 25% до 41 уровня", x = 65, y = 65, zone = "Loch Modan" },
			[33] = { str = "33. #PICTUREЛетите в Duskwood#"},
			[34] = { str = "34. #PICTUREОстановитесь тут в гостинице#."}, 
			[35] = { str = "35. #PICTUREЛетите в SW# и идите в точку 64,20 и возьмите задание  #ACCEPT“In Search of The Temple”#", x = 64, y = 20, zone = "Stormwind" },
			[36] = { str = "36. #PICTUREЛетите назад в Duskwood#, Бегите в Swamp of Sorrows" },
		}
	},

-----------41-41 Swamp of Sorrows
	--[402] = {
	[4141] = {
		title = "41-41 Swamp of Sorrows",
		--n = "41-41 Swamp of Sorrows",
		--pID = 401, nID = 403,
		--itemCount = 28,
		items = {
			[1] = { str = "1. 41-41 Swamp of Sorrows" },
			[2] = { str = "2. Бегите в Swamp of Sorrows, в точку 12,58  и убивайте whelps для задания  #DOQUEST“Dream Dust In the Swamp”#  шанс выпадения квестовых предметов низкий.", x = 12, y = 58, zone = "Swamp of Sorrows" },
			[3] = { str = "3. Идите в точку 26,59 и возьмите задание  #ACCEPT“Enroaching Wildlife”#  и начинайте его выполнять все мобы находятся не далеко отсюда.", x = 26, y = 59, zone = "Swamp of Sorrows" },
			[4] = { str = "4. Идите наверх и найдите Noboru the Cudgel в области 43,38 и получите предмет который начинает задание  #ACCEPT“Noboru the Cudgel”#", x = 43, y = 38, zone = "Swamp of Sorrows" },
			[5] = { str = "5. Вернитесь в точку 26,59 и сдайте задание  #TURNIN“Enroaching Wildlife”#  возьмите следующее  #ACCEPT“The Lost Caravan”#", x = 26, y = 59, zone = "Swamp of Sorrows" },
			[6] = { str = "6. Гриндите мобов по пути в точку 25,31  и сдайте задание  #TURNIN“Noboru the Cudgel”#  возьмите следующее  #ACCEPT“Draenethyst Crystals”#", x = 25, y = 31, zone = "Swamp of Sorrows" },
			[7] = { str = "7. Идите в точку 54,29 и начинайте собирать кристаллы для задания  #DOQUEST“Draenethyst Crystals”#", x = 54, y = 29, zone = "Swamp of Sorrows" },
			[8] = { str = "8. Добравшись до последнего лагеря в точке 65,18 где находится НПС первым делом заберите сундук с повозки с лева это необходимо для выполнения задания  #DOQUEST“The Lost Caravan”#", x = 65, y = 18, zone = "Swamp of Sorrows" },
			[9] = { str = "9. Обязательно зачистите лагерь рядом с НПС в клетке." },
			[10] = { str = "10. Берите задание  #ACCEPT“Galen’s Escape”#  его выполнить просто если вы зачистили лагерь." },
			[11] = { str = "11. Гриндите мобов по пути к точке 48,39 потрепаная палатка, откройте сундук что бы выполнить задание  #DOQUEST“Galen’s Escape”#", x = 48, y = 39, zone = "Swamp of Sorrows" },
			[12] = { str = "12. Вернитесь назад в точку 26,31 и сдайте задание  #TURNIN“Draenethyst Crystals”#", x = 26, y = 31, zone = "Swamp of Sorrows" },
			[13] = { str = "13. Идите в точку 26,59 и сдайте задание  #TURNIN“The Lost Caravan”#  берите следующее задание  #ACCEPT“Driftwood”#", x = 26, y = 59, zone = "Swamp of Sorrows" },
			[14] = { str = "14. Направляйся на юг в Blasted Lands в точку 36,59 к крепости Nethergarde Keep в точку 54,78. Откройте полетчика и летите Darkshire.", x = 54, y = 78, zone = "Blasted Lands" },
			[15] = { str = "15. #HUNTERОставьте кошку в стойле и возьмите другую из Badlands.#" },
			[16] = { str = "16. Возьмите задание  #ACCEPT“Supplies for Nethergarde”# по пути обратно на северо-восток" },
			[17] = { str = "17. #PICTUREЛетите в крепость Nethergarde#, и сдайте задание  #TURNIN“Supplies for Nethergarde”#." },
			[18] = { str = "18. Вернитесь обратно в Swamp of Sorrows." },
			[19] = { str = "19. Бегите к озеру вогруг подземелья Sunken Temple в точке 70,54 и разведайте территорию для задания  #DOQUESTIn Search of The Temple#", x = 70, y = 54, zone = "Swamp of Sorrows" },
			[20] = { str = "20. Идите в точку 76,6 и начинайте убивать crawlers и work для задания  #DOQUEST“… and bugs”# until it’s пока не выполните задание. Ищите деревянные доски на земле для задания  #DOQUEST“Driftwood”#", x = 76, y = 6, zone = "Swamp of Sorrows" },
			[21] = { str = "21. #HUNTERКогда вы выполните предыдущие 2 задания отпустите кошку и приручите silt crawler 40-41 уровня что бы выучить способность claw 6 ранга.#" },
			[22] = { str = "22. Жмите #PICTUREHearth# в Darkshire #HUNTERЗаберите свою кошку обратно из стойла.#" },
			[23] = { str = "23. Летите в Nethergarde и бегите назад в Swamp of Sorrows." },
			[24] = { str = "24. Идите в точку 26,59 и сдайте задание  #TURNIN“Driftwood”#  берите следующее  #ACCEPT“Deliver the Shipment”#.", x = 26, y = 59, zone = "Swamp of Sorrows" },
			[25] = { str = "25. Идите в Blasted Lands и сдайте задание  #TURNIN“Deliver the Shipment”#  в точке 66,21.", x = 66, y = 21, zone = "Blasted Lands" },
			[26] = { str = "25. Летите в Booty Bay и сдайте задание  #TURNIN“Dream Dust In the Swamp”#  возьмите новое задание  #ACCEPT“Rumors for Kravel”#." },
			[27] = { str = "27. Садитесь на корабль до Rachet и летите в Theramore и сдайте задание  #TURNIN“… and bugs”#  в гостинице." },
			[28] = { str = "28. Летите в Desolace." },
		}
	},

-----------41-42 Desolace
	--[403] = {
	[4142] = {
		title = "41-42 Desolace",
		--n = "41-42 Desolace",
		--pID = 402, nID = 404,
		--itemCount = 16,
		items = {
			[1] = { str = "1. 41-42 Desolace" },
			[2] = { str = "2. Сделайте Nijel’s Point вашим домом." },
			[3] = { str = "3. Берите задание  #ACCEPT“Down the Scarlet Path”#." },
			[4] = { str = "4. Спуститесь ниже и возьмите задание  #ACCEPT“Reagents For Reclaimers Inc pt.3”#" },
			[5] = { str = "5. Идите в точку 47,61 и возьмите задание  #ACCEPT“Ghost-O-Plasm Round Up”#.", x = 47, y = 61, zone = "Desolace" },
			[6] = { str = "6. Убивайте демонов в точке 51,75 для задания  #DOQUEST“Reagents For Reclaimers Inc pt.3”#.", x = 51, y = 75, zone = "Desolace" },
			[7] = { str = "7. Убивайте скелетов в точке 61,90 для задания  #DOQUEST“Down the Scarlet Path”#  и  #DOQUEST“Ghost-O-Plasm Round Up”#.", x = 61, y = 90, zone = "Desolace" },
			[8] = { str = "8. Когда вы выполните задания из пункта выше вы должны быть уже 42 уровня. Если нет можете тут его добить гриндя мобов." },
			[9] = { str = "9. Вернитесь в точку 47,61 и сдайте задание  #TURNIN“Ghost-O-Plasm Round Up”#", x = 47, y = 61, zone = "Desolace" },
			[10] = { str = "10. Жмите Hearth в Nijel’s Point" },
			[11] = { str = "11. Сдайте задание  #TURNIN“Down the Scarlet Path”# следующее задание ПРОПУСТИТЕ." },
			[12] = { str = "12. Идите южнее гостиницы поверните и сдайте задание  #TURNIN“Reagents For Reclaimers Inc pt.3”#  возьмите следующее  #ACCEPT“Reagents For Reclaimers Inc pt.4”#." },
			[13] = { str = "13. Летите в Theramore, далее плывите на коробле в Menethil и летите в Ironforge (Стальгорн)." },
			[14] = { str = "14. Сдайте задание  #TURNIN“Reagents For Reclaimers Inc pt.4”# в точке 67,17.", x = 67, y = 17, zone = "Ironforge" },
			[15] = { str = "15. Выучите новые навыки у классового тренера." },
			[16] = { str = "16. Летите в Booty Bay." },
		}
	},
-----------42-43 Stranglethron Vale
	--[404] = {
	[4243] = {
		title = "42-43 Stranglethron Vale",
		--n = "42-43 Stranglethron Vale",
		--pID = 403, nID = 405,
		--itemCount = 29,
		items = {
			[1] = { str = "1. 42-43 Stranglethron Vale" },
			[2] = { str = "2. Зайдите в гостиницу и возьмите задание  #ACCEPT“Tran'Rek”#." },
			[3] = { str = "3. Сделайте Booty Bay своим домом." },
			[4] = { str = "4. Возьмите задания  #ACCEPT“Zanzil's Secret”#  и  #ACCEPT“Whiskey Slim's Lost Grog”#." },
			[5] = { str = "5. Подойдите к банку и возьмите задание  #ACCEPT“Akiris By the Bundle pt.1”#." },
			[6] = { str = "6. Зайдите в дом с полукороблем и возьмите задание  #ACCEPT“Stoley's Debt”#" },
			[7] = { str = "7. Выходите из таверны и поднимитесь на 2й уровень причала и за углом возьмите задание  #ACCEPT“Keep An Eye Out”#" },
			[8] = { str = "8. Выходите из BB и поворачивайте направо и на юг в точке 31,79 и убивайте пиратов для заданий  #DOQUEST“Up To Snuff”#  и  #DOQUEST“Keep An Eye Out”#", x = 31, y = 79, zone = "Stranglethorn Vale" },
			[9] = { str = "9. Убивайте пиратов вокруг 2х лагерей в точке 29,81 и 27,82 для задания  #DOQUEST“The Bloodsail Buccaneers pt.4”#", x = 27, y = 82, zone = "Stranglethorn Vale" },
			[10] = { str = "10. Вернитесь в BB и поверните на лево." },
			[11] = { str = "11. Сдайте задание  #TURNIN“Keep An Eye Out”# около кузнецы." },
			[12] = { str = "12. Идите в гостиницу и сдайте задание  #TURNIN“Up To Snuff”#" },
			[13] = { str = "13. Выйдите на улицу и сдайте задание  #TURNIN“The Bloodsail Buccaneers pt.4”#  и возьмите следующее  #ACCEPT“The Bloodsail Buccaneers pt.5”#" },
			[14] = { str = "14. Отправляйтесь убивать наг в точке 25,63 для задания  #DOQUEST“Akiris By the Bundle pt.1”#", x = 25, y = 63, zone = "Stranglethorn Vale" },
			[15] = { str = "15. Гриндите наг пока у вас не будет хотя бы 50% опыта до 43 уровня." },
			[16] = { str = "16. Поднимитесь к Ruins of Aboraz и убейте #NPCChucky# в точке 40,58 для задания  #DOQUEST“Voodoo Dues”#,  убивайте мобов для задания  #DOQUEST“Zanzil's Secret”# вам нужно только 8-10 штук.", x = 40, y = 58, zone = "Stranglethorn Vale" },
			[17] = { str = "17. Поднимитесь к Ruins of Jubawal и убейте #NPCJon-Jon# в точке 34,51 и #NPCMaury# в точке 35,51 для задания  #DOQUEST“Voodoo Dues”# и доделайте задание  #DOQUEST“Zanzil's Secret”#", x = 35, y = 51, zone = "Stranglethorn Vale" },
			[18] = { str = "18. Убейте #NPCTethis# для задания #DOQUEST“Raptor Mastery pt.4”#  за ареной в точке 31,43 затем сдайте его в лагере nessingways в точке 35,10 и возьмите следующее задание  #ACCEPT“Big Game Hunter”#", x = 31, y = 43, zone = "Stranglethorn Vale" },
			[19] = { str = "19. Идите к лагерю повстанцев в точке 38,3 и возьмите задание  #ACCEPT“Colonel Kurzen”#.", x = 38, y = 3, zone = "Stranglethorn Vale" },
			[20] = { str = "20. Идите в пещеру координаты 45,8 go to the fork and go down once like earlier kill the elites and subchiefs (when they get a red aura stop your pet from hitting them or he’ll get owned) for #DOQUEST“Colonel Kurzen”# Kurzen is at 49,3 ", x = 49, y = 3, zone = "Stranglethorn Vale" },
			[21] = { str = "21. Специально умрите стобы оказаться рядом с лагере повстанцев." },
			[22] = { str = "22. Идите в лагерь повстанцев в точку 38,3 и сдайте задание  #TURNIN“Colonel Kurzen”#.", x = 38, y = 3, zone = "Stranglethorn Vale" },
			[23] = { str = "23. Убивайте тролей в точке 44,34 пока не наберете примерно 9000 опыта до повышения уровня.", x = 44, y = 34, zone = "Stranglethorn Vale" },
			[24] = { str = "24. Жмите Hearth в Booty Bay" },
			[25] = { str = "25. Сдайте задание  #TURNIN“Zanzil's Secret”#" },
			[26] = { str = "26. Спуститесь к банку и сдайте задание  #TURNIN“Akiris By the Bundle pt.1”#  и возьмите следующее  #ACCEPT“Akiris By the Bundle pt.2”#" },
			[27] = { str = "27. Идите к дому около полулодки и сдайте задание  #TURNIN“Voodoo Dues”#  возьмите следующее  #ACCEPT“Cracking Maury's Foot”#" },
			[28] = { str = "28. Плывите на лодке до Rachet затем летите в Theramore." },
			[29] = { str = "29. Сдайте задание  #TURNIN“Akiris By the Bundle pt.2”#  перед собой и летите в Gadgetzan" },
		}
	},

-----------43-43 Tanaris
	--[405] = {
	[4343] = {
		title = "43-43 Tanaris",
		--n = "43-43 Tanaris",
		--pID = 404, nID = 406,
		--itemCount = 34,
		items = {
			[1] = { str = "1. 43-43 Tanaris" },
			[2] = { str = "2. Возьмите задания  #ACCEPT“Wastewander Justice”# и  #ACCEPT“Water Pouch Bounty”#." },
			[3] = { str = "3. Сделайте Gadgetzan своим домом." },
			[4] = { str = "4. Идите в двери клетки и возьмите 2 задания с таблички  #ACCEPT“WANTED: Caliph Scorpidsting”#  и  #ACCEPT“WANTED: Andre Firebeard”#." },
			[5] = { str = "5. Сдайте задание  #TURNIN“Tran'Rek”# следующее задание ПРОПУСТИТЕ." },
			[6] = { str = "6. С левой стороны города на холме возьмите задание  #ACCEPT“Gadgetzan Water Survey”#" },
			[7] = { str = "7. Идите на север в соседнюю локацию The Shimmering Flats в точку 77,77 и сдайте задание  #TURNIN“Rumors for Kravel”#  и возьмите следующее  #ACCEPT“Back to Booty Bay”#", x = 77, y = 77, zone = "Thousand Needles" },
			[8] = { str = "8. Тут рядом сдайте задание  #TURNIN“News for Fizzle”#" },
			[9] = { str = "9. Идите в точку 80,75 и возьмите задание  #ACCEPT“Keeping Pace”#  для этого поговорите с zamek который находится к югу отсюда. У него над головой синий знак #PICTURE?# не идите за ним идите к дому rizzles в точке 77,77 когда он уйдет троньте чертежи и сдайте задание  #TURNIN“Keeping Pace”#  и возьмите следующее  #ACCEPT“Rizzle's Schematics”# и сдайте его в точке 80,75", x = 80, y = 75, zone = "Thousand Needles" },
			[10] = { str = "10. Жмите Hearth в Gadgetzan" },
			[11] = { str = "11. Идите в Steamwheedle Port в точку 59,80", x = 59, y = 80, zone = "Tanaris" },
			[12] = { str = "12. Сдайте задание  #TURNIN“Stoley's Debt”#  в южном доме и возьмите задание  #ACCEPT“Stoley’s Shipment”#  и  #ACCEPT“Southsea Shakedown”#" },
			[13] = { str = "13. Идите к северному дому и возьмите задание  #ACCEPT“Pirate Hats Ahoy!”#  и  #ACCEPT“Screecher Spirits”#" },
			[14] = { str = "14. Идите в точку 63,30 и убивайте там мобов для задания  #DOQUEST“Wastewander Justice”#  и  #DOQUEST“Water Pouch Bounty”#  Выслидите моба #NPCCaliph Scorpidsting# и убейте для задания  #ACCEPT“WANTED: Caliph Scorpidsting”#.  У него 2 охранника в инвизе но убить его всеравно довольно легко.", x = 63, y = 30, zone = "Tanaris" },
			[15] = { str = "15. Бегите до пещеры в точке 68,41 и пройдите через ее в бухту.", x = 68, y = 41, zone = "Tanaris" },
			[16] = { str = "16. Начинайте гиноцид пиратов для заданий  #DOQUEST“Southsea Shakedown”#  и  #DOQUEST“Pirate Hats Ahoy!”#" },
			[17] = { str = "17. Вы можете получить пиратские сундуки в которых могут быть 3 части карты верхняя, средняя и нижняя #NPCShip Schedule# если собрать все берите задание  #ACCEPT“Cuergo’s Gold”#  и  #ACCEPT“Ship Schedules”#.  Выполните их только в том случае если они вам попалиись, если нет то пропустите этот пункт." },
			[18] = { str = "18. Убейте #NPCAndre Firebeard# в точке 73,47 для задания  #ACCEPT“WANTED: Andre Firebeard”#", x = 73, y = 47, zone = "Tanaris" },
			[19] = { str = "19. Идите в двух этажный дом в точке 72,46 и заберите краденное вино для задания  #DOQUEST“Stoley’s Shipment”#. Оно находится на 2м этаже.", x = 72, y = 46, zone = "Tanaris" },
			[20] = { str = "20. Жмите Hearth в Gadgetzan" },
			[21] = { str = "21. Сдайте задание  #TURNIN“Wastewander Justice”#  и возьмите следующее  #ACCEPT“More Wastewander Justice”#" },
			[22] = { str = "22. Сдайте задание  #TURNIN“WANTED: Caliph Scorpidsting”#  и  #TURNIN“Water Pouch Bounty”#" },
			[23] = { str = "23. Вы должны быть близки к 50% опыта до следующего уровня." },
			[24] = { str = "24. Идите на запад по координатам 39,29 и выполните задание  #DOQUEST“Gadgetzan Water Survey”#  сразу после сбора оброзца на вас нападут мобы 47 и 48 уровня, Бегите.", x = 32, y = 29, zone = "Tanaris" },
			[25] = { str = "24. Вернить назад в Gadgetzan и сдай задание  #TURNIN“Gadgetzan Water Survey”#  и возьмите  #ACCEPT“Noxious Lair Investigation”#" },
			[26] = { str = "26. Идите выполнять задание  #DOQUEST“More Wastewander Justice”#  в точке 60,35 убивайте толпу.", x = 60, y = 35, zone = "Tanaris" },
			[27] = { str = "27. Вернитесь в порт Steamweedle Port в точку 59,80 к южному дому и сдайте задание  #TURNIN“Stoley’s Shipment”#  берите следующее  #ACCEPT“Deliver to MacKinley”#", x = 59, y = 80, zone = "Tanaris" },
			[28] = { str = "28. Сдайте  #TURNIN“WANTED: Andre Firebeard”#  и  #TURNIN“Southsea Shakedown”#" },
			[29] = { str = "29. Идите к соседнему дому и сдайте  #TURNIN“Pirate Hats Ahoy!”#" },
			[30] = { str = "30. Жмите Hearth в Gadgetzan" },
			[31] = { str = "31. Сдайте задание  #TURNIN“More Wastewander Justice”#" },
			[32] = { str = "32. Возьмите задание  #ACCEPT“Handle With Care”# в районе северной части города." },
			[33] = { str = "33. У вас должно быть 75% опыта до следующего уровня." },
			[34] = { str = "34. Летите в Feralas." },
		}
	},

-----------43-45 Feralas
	--[406] = {
	[4345] = {
		title = "43-45 Feralas",
		--n = "43-45 Feralas",
		--pID = 405, nID = 407,
		--itemCount = 43,
		items = {
			[1] = { str = "1. 43-45 Feralas" },
			[2] = { str = "2. On the water side of the inn in the gazebo, accept #ACCEPT“The Mark of Quality”#" },
			[3] = { str = "3. Make Feralas your home" },
			[4] = { str = "4. Go into the big building across from the Inn, accept #ACCEPT“The Missing Courier pt.1”# and #ACCEPT“The Ruins of Solarsal”#" },
			[5] = { str = "5. Go to the building just west accept #ACCEPT“In Search of Knowledge”# and #ACCEPT“The High Wilderness”#" },
			[6] = { str = "6. Go upstairs turn in #TURNIN“The Missing Courier pt.1”# accept #ACCEPT“The Missing Courier pt.2”#" },
			[7] = { str = "7. Go to the gazebo at 26,52 and turn in #TURNIN“The Ruins of Solarsal”# accept #ACCEPT“Return to Feathermoon Stronghold”#", x = 26, y = 52, zone = "Feralas" },
			[8] = { str = "8. Go back to Feathermoon to the big building, turn in #TURNIN“Return to Feathermoon Stronghold”# accept #ACCEPT“Against the Hatecrest pt.1”# turn around and hand it in accept #ACCEPT“Against the Hatecrest pt.2”#" },
			[9] = { str = "9. Kill naga around 26,54 for #DOQUEST“Against the Hatecrest pt.2”#", x = 26, y = 54, zone = "Feralas" },
			[10] = { str = "10. I kill the naga until im about 2500 TNL because I’m usually under 15k TNL when I get to this part. They give an average of 250 xp per kill" },
			[11] = { str = "11. Go back to Feathermoon to the big building, turn in #TURNIN“Against the Hatecrest pt.2”# accept #ACCEPT“Against Lord Shalzaru”#" },
			[12] = { str = "12. Go down to the cave at 26,66 and kill #NPCLord Shalzaru# at the end for #DOQUEST“Against Lord Shalzaru”#", x = 26, y = 66, zone = "Feralas" },
			[13] = { str = "13. Die so you end up at Feathermoon" },
			[14] = { str = "14. Go back to Feathermoon to the big building, turn in #TURNIN“Against Lord Shalzaru”# accept #ACCEPT“Delivering the Relic”# go to the other side of the building and turn it in." },
			[15] = { str = "15 .Take the boat to the mainland" },
			[16] = { str = "16. Go south of the dock and kill screechers for #DOQUEST“Screecher Spirits”#" },
			[17] = { str = "17. Go down to 45,65 and touch the wrecked boat to turn in #TURNIN“The Missing Courier pt.2”# accept #ACCEPT“Boat Wreckage”#", x = 45, y = 65, zone = "Feralas" },
			[18] = { str = "18. Hearth to Feathermoon" },
			[19] = { str = "19. Go in the little building across from the Inn on the 2nd floor, turn in #TURNIN“Boat Wreckage”# accept #ACCEPT“The Knife Revealed”#" },
			[20] = { str = "20. Go up top of the big spiral tower, turn in #TURNIN“The Knife Revealed”# accept #ACCEPT“Psychometric Reading”#" },
			[21] = { str = "21. Go in the little building across form the Inn on the 2nd floor, turn in #TURNIN“Psychometric Reading”# accept #ACCEPT“The Woodpaw Gnolls”#" },
			[22] = { str = "22. Take the boat to the mainland" },
			[23] = { str = "23. Go into the yeti cave at 56,56 and kill yeti’s for #DOQUEST“The Mark of Quality”# you can skin them and it’s also a drop.", x = 56, y = 56, zone = "Feralas" },
			[24] = { str = "24. If a #NPCOOX-22/FE Distress Beacon# has fallen accept the quest #ACCEPT“Find OOX-22/FE!”# and turn it in at the back of the cave SKIP the escort. " },
			[25] = { str = "25. Grind east and kill the Brutes around 60,56, and warlocks and shamans around 59,66 for #DOQUEST“The High Wilderness”# I kill any I see", x = 60, y = 56, zone = "Feralas" },
			[26] = { str = "26. Go up to 65,45 and accept #ACCEPT“Freedom For All Creatures”# It’s pretty hidden, just NW of the camp entrance is a path that doesn’t even look like you can walk on it. To do this simply escort her to the cage, open it and kill anything until it says complete. ", x = 65, y = 45, zone = "Feralas" },
			[27] = { str = "27. Hand it back in and accept #ACCEPT“Doling Justice pt.1”# The mobs can be found in this camp." },
			[28] = { str = "27. Turn in #TURNIN“Doling Justice pt.1”#  at 65,45 and accept #ACCEPT“Doling Justice pt.2”#", x = 65, y = 45, zone = "Feralas" },
			[29] = { str = "29. Go down to 73,56 and touch Large Leather Backpacks on the big tree. Turn in #TURNIN“The Woodpaw Gnolls”# accept #ACCEPT“The Writhing Deep”#", x = 73, y = 56, zone = "Feralas" },
			[30] = { str = "30. Right click the Backpack, accept #ACCEPT“Thalanaar Delivery”#" },
			[31] = { str = "31. Grind down to the hive at 73,63 and go all the way down. Go into the southern tunnel and stay right, You’ll see a Zukk’Ash Pod there. Turn in #TURNIN“The Writhing Deep”# accept #ACCEPT“Freed From the Hive”#", x = 73, y = 63, zone = "Feralas" },
			[32] = { str = "32. Hearth to Feathermoon" },
			[33] = { str = "33. On the water side of the Gazebo, turn in #TURNIN“The Mark of Quality”# accept #ACCEPT“Improved Quality”#" },
			[34] = { str = "34. Go in the small house across from the Inn, turn in #TURNIN“The High Wilderness”# then go upstairs and turn in #TURNIN“Freed From the Hive”# accept #ACCEPT“A Hero’s Welcome”#" },
			[35] = { str = "35. Go to the big building next door and turn in #TURNIN“A Hero’s Welcome”# accept #ACCEPT“Rise of the Silithid”#" },
			[36] = { str = "36. Fly out to Thalanaar (spot between 1k needles and here) turn in #TURNIN“Thalanaar Delivery”# at 89,46", x = 89, y = 46, zone = "Feralas" },
			[37] = { str = "37. Fly to Rut'theran Village (Darnassus)" },
			[38] = { str = "38. Follow the dock and go in the house, turn in #TURNIN“Handle With Care”# accept #ACCEPT“Favored of Elune?”#" },
			[39] = { str = "39. Go upstairs, turn in #TURNIN“In Search of Knowledge”# then go to the back of the house on the 2nd floor, open the green book and accept #ACCEPT“Feralas: A History”# turn it back in to her, accept #ACCEPT“The Borrower”#" },
			[40] = { str = "40. Get new skills" },
			[41] = { str = "41. Go to the temple of the moon at 39,86 and up to the 2nd floor, turn in #TURNIN“Rise of the Silithid”# and #TURNIN“Doling Justice pt.2”#", x = 39, y = 86, zone = "Feralas" },
			[42] = { str = "42. Buy 2 Elixir of Fortitude for a later part of this quest" },
			[43] = { str = "43. Hearth to Feathermoon and fly to Gadgetzan and turn in #TURNIN“The Borrower”# accept #ACCEPT“The Super Snapper FX”#" },
		}
	},

-----------45-46 Uldaman
	--[407] = {
	[4546] = {
		title = "45-46 Uldaman",
		--n = "45-46 Uldaman",
		--pID = 406, nID = 408,
		--itemCount = 7,
		items = {
			[1] = { str = "1. 45-46 Uldaman" },
			[2] = { str = "2. Now you can either grind on the gnolls in Feralas around where you found the backpack on the tree, or you can do Uldaman. I highly suggest you do Uldaman. You picked up some quests earlier, there are a few more in IF and in the badlands. If you get a good group build you can easily do just about every quest in there in under 3 hours max. I usually fully do Uldaman inside and out, I don’t finish all the quests unless I have to level. 1 full run inside and out should get you 75-100% through this level. I usually do this in about 3 hours no problem. Plus you can solo all the mobs outside of the instance 3 at a time no problem. The end of Uldaman, after the boss, (mini disks quest) gives about 20k xp between that and talking to the ghostly npc who spawns in there, as well as gives some nice xp for quests later on. And you could miss some xp spots for later quests I do if you skip this." },
			[3] = { str = "3. I don’t list all the quests for Uldaman because there is a good handful and you don’t have to do them all to fully level, and again it is optional. This is much faster than grinding would be. I really hate to do instances when trying for the best time but alliance has less quests than the horde do and I did mention there will be about 10-15% of grinding on your way to 60. If you did do all instances though you would be really slowed down. This isn’t going to put a break in your time with a good group, preferrably guild groups of 45+" },
			[4] = { str = "4. You can stop at about 75% to 46 but again I suggest you level. It’s not as bad as it seems." },
			[5] = { str = "5. A great map of Uldaman and where the parts of most of the quests pieces can be done at is listed here on worldofwar.net" },
			[6] = { str = "6. Once you’re all set, fly to SW and turn in #TURNIN“In Search of The Temple”# at 64,20 and accept #ACCEPT“In Search of The Hinterlands”# get new skills then fly to Southshore.", x = 64, y = 20, zone = "Stormwind" },
			[7] = { str = "7. Run up to the path at 84,33 behind Durnholde Keep (you’ll see 2 griffins) into The Hinterlands", x = 84, y = 33, zone = "Tarren Mill" },
		}
	},

-----------46-47 The Hinterlands
	--[408] = {
	[4647] = {
		title = "46-47 The Hinterlands",
		--n = "46-47 The Hinterlands",
		--pID = 407, nID = 409,
		--itemCount = 29,
		items = {
			[1] = { str = "1. 46-47 The Hinterlands" },
			[2] = { str = "2. Go up to 11,46 and turn in #TURNIN“In Search of The Hinterlands”# accept #TURNIN“Gryphon Master Talonaxe”#", x = 11, y = 46, zone = "The Hinterlands" },
			[3] = { str = "3. Get the FP at 11,46 way up top then go in the cave and turn in  #TURNIN“Gryphon Master Talonaxe”#, accept #ACCEPT“Rhapsody Shindigger”# and #ACCEPT“Witherbark Cages”#", x = 11, y = 46, zone = "The Hinterlands" },
			[4] = { str = "4. Go into the Inn and turn right, accept #ACCEPT“Skulk Rock Clean-Up”# and #ACCEPT“Troll Necklace Bounty”#" },
			[5] = { str = "5. Go way in the back of the Inn up to around 13,41 and make Aerie Peak your home.", x = 13, y = 41, zone = "The Hinterlands" },
			[6] = { str = "6. Grind east to 20,48 to the path while keeping an eye out for feathers on the ground for #DOQUEST“Favored of Elune?”# You don’t need them all yet", x = 20, y = 48, zone = "The Hinterlands" },
			[7] = { str = "7. Follow the path up to 26,48 and turn in #TURNIN“Rhapsody Shindigger”# accept #ACCEPT“Rhapsody's Kalimdor Kocktail”#", x = 26, y = 48, zone = "The Hinterlands" },
			[8] = { str = "8. Go back down and to the troll camp and clear most of them out at 23,58 and open the 2 cages for #DOQUEST“Witherbark Cages”#", x = 23, y = 58, zone = "The Hinterlands" },
			[9] = { str = "9. Grind east to 31,57 and open the 3rd cage for #DOQUEST“Witherbark Cages”#", x = 31, y = 57, zone = "The Hinterlands" },
			[10] = { str = "10. You should also have 5 necklaces for #DOQUEST“Troll Necklace Bounty”# now" },
			[11] = { str = "11. Go NE up to 46,42, collecting feathers if you still need them on the way, and kill the Green Sludges for #DOQUEST“Skulk Rock Clean-Up pt.1”#", x = 46, y = 62, zone = "The Hinterlands" },
			[12] = { str = "12. Go to 49,37 if you found OOX-09/HL Distress Beacon", x = 49, y = 37, zone = "The Hinterlands" },
			[13] = { str = "13. Go to 56,41 and kill Jade Oozes for part 2 of #DOQUEST“Skulk Rock Clean-Up”#", x = 56, y = 41, zone = "The Hinterlands" },
			[14] = { str = "14. Go to the waterfall at 81,46 and dive into the water below, then go south along this shore until you see Gammerita and take her picture for #DOQUEST“The Super Snapper FX”# Also you want to keep an eye out for bottles along the shore for #DOQUEST“Whiskey Slim's Lost Grog”#", x = 81, y = 46, zone = "The Hinterlands" },
			[15] = { str = "15. Hearth to Aerie Peak" },
			[16] = { str = "16. Go to the front of the Inn and turn in #TURNIN“Skulk Rock Clean-Up”# and #TURNIN“Troll Necklace Bounty”# and any extra 5 necklaces you have." },
			[17] = { str = "17. Go up past the FP in the cave at 9,44 and turn in #TURNIN“Witherbark Cages”# accept #ACCEPT“The Altar of Zul”#", x = 9, y = 44, zone = "The Hinterlands" },
			[18] = { str = "18. Go run up top of the Altar of Zul at 48,68 for #DOQUEST“The Altar of Zul”#", x = 48, y = 68, zone = "The Hinterlands" },
			[19] = { str = "19. Now I grind on the trolls and wolves around Zul until I’m 1 bar from level 47. You should be at least half way through level 46 at this point." },
			[20] = { str = "20. Get the quest #ACCEPT“Jammal'an the Prophet”# at 33,75 if you plan to do Sunken Temple later.", x = 33, y = 75, zone = "The Hinterlands" },
			[21] = { str = "21. I’m sure by the time you near level 47 you’re going to find OOX-09/HL Distress Beacon accept #ACCEPT“Find OOX-09/HL”# and turn it in at 49,37 and then accept #ACCEPT“Rescue OOX-09/HL”# and escort it to 78,61 Theres only 2 encounters of 3 mobs, but watch out for the stealthed wolves", x = 49, y = 37, zone = "The Hinterlands" },
			[22] = { str = "22. Once you’re about 6k or 1 bar from level 47 hearth to Aerie Peak" },
			[23] = { str = "23. Turn in any #TURNIN“Troll Necklace Bounty”# you have just before you go out" },
			[24] = { str = "24. Go up past FP to 9,44 and turn in #TURNIN“The Altar of Zul”# accept #ACCEPT“Thadius Grimshade”#", x = 9, y = 44, zone = "The Hinterlands" },
			[25] = { str = "25. Fly to Menethil Harbor and take the boat to Auberdine, then fly to Rut’theran Village" },
			[26] = { str = "26. Run to the house at 55,92 and turn in #TURNIN“Favored of Elune?”#", x = 55, y = 92, zone = "The Hinterlands" },
			[27] = { str = "27. Go upstairs, turn in #TURNIN“The Super Snapper FX”# accept #ACCEPT“Return to Troyas”#" },
			[28] = { str = "27. You should now be level 47 and about 8k into it." },
			[29] = { str = "29. Fly to Feralas" },
		}
	},

-----------47-47 Feralas
	--[409] = {
	[4747] = {
		title = "47-47 Feralas",
		--n = "47-47 Feralas",
		--pID = 408, nID = 410,
		--itemCount = 22,
		items = {
			[1] = { str = "1. 47-47 Feralas" },
			[2] = { str = "2. Make Feathermoon Stronghold your home" },
			[3] = { str = "3. Go across from the Inn to the 2 story house, turn in #TURNIN“Return to Troyas”# accept #ACCEPT“The Stave of Equinex”#" },
			[4] = { str = "4. Accept #ACCEPT“The Sunken Temple”# Next to him" },
			[5] = { str = "5. Swim or sail east to the dock." },
			[6] = { str = "6. Beside the dock at 44,33 accept #ACCEPT“Zapped Giants”# and #ACCEPT“Fuel for Zapping”#", x = 44, y = 33, zone = "Feralas" },
			[7] = { str = "7. Make the Zorbin's Ultra-Shrinker a hotkey. Then go south along the shore and start zapping giants and killing them for #DOQUEST“Zapped Giants”# and kill water elementals for #DOQUEST“Fuel for Zapping”#" },
			[8] = { str = "8. Go back to 44,33 and turn in #TURNIN“Zapped Giants”# and #TURNIN“Fuel for Zapping”# You can now do those again, but I wouldn’t, for about 500 xp per turn in. Now he opens his store to you.", x = 44, y = 33, zone = "Feralas" },
			[9] = { str = "9. Run over to the grimtotem camp at 65,45 and accept #ACCEPT“An Orphan Looking For A Home”#", x = 65, y = 45, zone = "Feralas" },
			[10] = { str = "10. Go down to the yeti cave at 56,56 and do the robot chicken escort if you can, don’t be afraid to ask for help if needed.", x = 56, y = 56, zone = "Feralas" },
			[11] = { str = "11. Grind to the yeti cave at 51,31 on Ironfur Bears and Groddoc Gorillas until you get 3 livers from each of them for #DOQUEST“Rhapsody's Kalimdor Kocktail”#", x = 51, y = 31, zone = "Feralas" },
			[12] = { str = "12. Kill the Rage Scar Yeti’s here for #DOQUEST“Improved Quality”# remember you can skin them for these as well. If a Pristine Yeti Hide drops, accept the quest it gives #ACCEPT“Pristine Yeti Hide”#" },
			[13] = { str = "13. Go to Rockbiter at 42,22 and accept #ACCEPT“The Giant Guardian”#", x = 42, y = 22, zone = "Feralas" },
			[14] = { str = "14. Do #DOQUEST“The Stave of Equinex”# by doing the following. Get the Blytan Essence from the fire at 38,15 #DOQUEST“The Stave of Equinex”# Get the Samha Essence from the fire at 40,12 (atop the ruined arch) to get to it, go around back and hop up the broken rocks (it’s not easily noticed) Go back out the back and Grab the Imbel Essence from the fire at 39,9. Get the Lahassa Essence from the fire at 37,12 under the brown gazebo. Go down to the Equinex Monolith just over the cliff. Use Troya’s Staff next to it. Touch the Monolith and turn in #TURNIN“The Stave of Equinex”#  accept #ACCEPT“The Morrow Stone”#", x = 38, y = 15, zone = "Feralas" },
			[15] = { str = "15. Go back up near the previous flame to 38,10 and turn in #TURNIN“The Giant Guardian”# accept the escort #ACCEPT“Wandering Shay”#", x = 38, y = 10, zone = "Feralas" },
			[16] = { str = "16. Grab the bell from the chest and hotkey it. This is similar to the druid quest back in Darkshore. Run her back to Rockbiter at 42,21 and turn in #TURNIN“Wandering Shay”# (the trick is to keep ahead of her, if she’s with you by your side she will wander off a lot more and the bell has a 1 minute timer.", x = 42, y = 21, zone = "Feralas" },
			[17] = { str = "17. Hearth to Feathermoon Stronghold" },
			[18] = { str = "18. Go to the gazebo near the water beside the hippogryph master, turn in #TURNIN“Pristine Yeti Hide”# and #TURNIN“Improved Quality”#" },
			[19] = { str = "19. Take your 2 Elixirs of Fortitude out of your mailbox if you don’t already have them on you." },
			[20] = { str = "20. Go across to the 2 story house, turn in #TURNIN“The Morrow Stone”#" },
			[21] = { str = "21. You should be close to 70% into 47" },
			[22] = { str = "22. Fly to Gadgetzan" },
		}
	},

-----------47-48 Tanaris
	--[410] = {
	[4748] = {
		title = "47-48 Tanaris",
		--n = "47-48 Tanaris",
		--pID = 409, nID = 411,
		--itemCount = 42,
		items = {
			[1] = { str = "1. 47-48 Tanaris" },
			[2] = { str = "2. Just inside Gadgetzan to the right, accept #ACCEPT“The Thirsty Goblin”#" },
			[3] = { str = "3. Make Gadgetzan your home" },
			[4] = { str = "4. Go behind the Inn, accept #ACCEPT“The Dunemaul Compound”#" },
			[5] = { str = "5. Near the north entrance, accept #ACCEPT“Thistleshrub Valley”#" },
			[6] = { str = "6. Go south to the skeleton in the ground at 49,36 and 44,39 and 47,45 kill Rocs for #DOQUEST“Rhapsody's Kalimdor Kocktail”# If it’s busy just do it later.", x = 49, y = 36, zone = "Tanaris" },
			[7] = { str = "7. Ride over to 52,45 turn in #TURNIN“The Sunken Temple”# and accept #ACCEPT“The Stone Circle”# and #ACCEPT“Gahz'Ridian”#", x = 52, y = 45, zone = "Tanaris" },
			[8] = { str = "8. Now put on the Gahz’Ridian Detector Helm and yellow dots on mini map will show the pieces you need to get for #DOQUEST“Gahz'Ridian”#. It’s up to you if you want to wear this in fights. This stuff is all over" },
			[9] = { str = "9. Run over west to the Dunemaul Compound clear a path to 40,58 and kill Gor’Marok the Ravager for #DOQUEST“The Dunemaul Compound”# You don’t need the 20 ogre kills all from here", x = 40, y = 58, zone = "Tanaris" },
			[10] = { str = "10. Head over to 47,65 and finish killing the ogres for The Dunemaul Compound while gathering the rest of the artifacts for Gahz'Ridian", x = 47, y = 65, zone = "Tanaris" },
			[11] = { str = "11. Grind on the ogres until you’re 10,000 from level 48" },
			[12] = { str = "12. Sneak up the left side of Uldum and go up to the pedestal at 37,81 and turn in #TURNIN“Seeing What Happens”#", x = 37, y = 81, zone = "Tanaris" },
			[13] = { str = "13. Talk to the guy who appears, accept #ACCEPT“The Stone Watcher”# and talk to him until completed. Then touch the pedastal to turn it back in" },
			[14] = { str = "14. Touch the pedastal one more time and accept #ACCEPT“Return to Ironforge”#" },
			[15] = { str = "15. Go west to 29,66 and kill Gnarled Thistlegrub and Thistlegrub Rootshapers for #DOQUEST“Thistleshrub Valley”# and the dew collectors for #DOQUEST“The Thirsty Goblin”# You should hit level 48 here", x = 29, y = 66, zone = "Tanaris" },
			[16] = { str = "16. If you find Tooga, accept #ACCEPT“Tooga’s Quest”# I found him at 29,73 near the zepplin, but you can find him anywhere around this valley. He follows you, you don’t have to follow him ", x = 29, y = 73, zone = "Tanaris" },
			[17] = { str = "17. Go up to the Noxious Lair around 34,46 and kill Centipaar there for #DOQUEST“Noxious Lair Investigation”# If you can’t get them all before tooga has 10 minutes left, go turn that in and then come back.", x = 34, y = 76, zone = "Tanaris" },
			[18] = { str = "18. Turn in #TURNIN“Tooga’s Quest”# near steamwheedle port at 66,25", x = 66, y = 25, zone = "Tanaris" },
			[19] = { str = "19. Accept #ACCEPT“Yuka Screwspigot”#" },
			[20] = { str = "20. Turn in #TURNIN“Screecher Spirits”# at 66,22 SKIP the ZF part", x = 66, y = 22, zone = "Tanaris" },
			[21] = { str = "21. Hearth to Gadgetzan" },
			[22] = { str = "22. Go near the entrance and accept #ACCEPT“The Thirsty Goblin”# back and turn it in accept #ACCEPT“In Good Taste”#" },
			[23] = { str = "23. Go behind the Inn near the fire, turn in #TURNIN“The Dunemaul Compound”#" },
			[24] = { str = "24. Go near the north entrance, hand in #TURNIN“Thistleshrub Valley”#" },
			[25] = { str = "25. Go west to Sprinkle, turn in #TURNIN“In Good Taste”# accept #ACCEPT“Sprinkle's Secret Ingredient”#" },
			[26] = { str = "26. In the building behind her, turn in #TURNIN“Noxious Lair Investigation”#" },
			[27] = { str = "27. Go on the hill behind the building, accept #ACCEPT“The Schrimshank Redemption”#" },
			[28] = { str = "27. Run down to 52,45 and turn in #TURNIN“Gahz'Ridian”#", x = 52, y = 45, zone = "Tanaris" },
			[29] = { str = "29. Run down to the entrance at 55,70 take the spiral down to the entrance that is north. first fork go right. after the circular room at the next fork go right. You will enter a big square room. Go right to 55,71 and grab the survey gear for #DOQUEST“The Schrimshank Redemption”#", x = 55, y = 70, zone = "Tanaris" },
			[30] = { str = "30. Die on purpose so you end up at Gadgetzan" },
			[31] = { str = "31. Go to the hill on the west side of town, turn in #TURNIN“The Schrimshank Redemption”# accept #ACCEPT“Insect Part Analysis pt.1”#" },
			[32] = { str = "32. Go to the house on the NW part of town, turn in #TURNIN“Insect Part Analysis pt.1”# accept #ACCEPT“Insect Part Analysis pt.2”#" },
			[33] = { str = "33. Go back up on the hill, turn in #TURNIN“Insect Part Analysis pt.2”# accept #ACCEPT“Rise of the Silithid”#" },
			[34] = { str = "34. Run up to the Shimmering Flats to 78,74 and turn in #TURNIN“An Orphan Looking For A Home”# accept #ACCEPT“A Short Incubation”# and since you already have this, turn it back in and accept #ACCEPT“The Newest Member of the Family”# now you have 1 hour.", x = 78, y = 74, zone = "Thousand Needles" },
			[35] = { str = "35. Fly to Theramore and get any mageweave you have out and build up first aid as much as you can." },
			[36] = { str = "36. Sail to Menethil and fly to IF" },
			[37] = { str = "37. Make IF your home and get new skills" },
			[38] = { str = "38. Go to 77,11 and turn in #TURNIN“Return to Ironforge”# accept #ACCEPT“A Future Task”# and #ACCEPT“Passing the Burden”#", x = 77, y = 11, zone = "Ironforge" },
			[39] = { str = "39. Turn around to 70,18 and turn in #TURNIN“A Future Task”#", x = 70, y = 18, zone = "Ironforge" },
			[40] = { str = "40. Go to 31,4 and turn in #TURNIN“Passing the Burden”# accept #ACCEPT“Arcane Runes”# and #ACCEPT“An Easy Pickup”#", x = 31, y = 4, zone = "Ironforge" },
			[41] = { str = "41. Go to 70,93, turn in #TURNIN“An Easy Pickup”# accept #ACCEPT“Signal For Pickup”# then turn it back in. Now you got the flare gun to signal later on.", x = 70, y = 93, zone = "Ironforge" },
			[42] = { str = "42. Fly to the Hinterlands" },
		}
	},

-----------48-48 The Hinterlands
	--[411] = {
	[4848] = {
		title = "48-48 The Hinterlands",
		--n = "48-48 The Hinterlands",
		--pID = 410, nID = 412,
		--itemCount = 8,
		items = {
			[1] = { str = "1. 48-48 The Hinterlands" },
			[2] = { str = "2. Go in the base downstairs to 14,43 and turn in #TURNIN“The Newest Member of the Family”# accept #ACCEPT“Food For Baby”#", x = 14, y = 43, zone = "The Hinterlands" },
			[3] = { str = "3. Run up to 26,48 and turn in #TURNIN“Rhapsody's Kalimdor Kocktail”# Accept #ACCEPT“Rhapsody's Tale”#", x = 26, y = 48, zone = "The Hinterlands" },
			[4] = { str = "4. Grind down to the lake at 40,59 and Violet Tragan (Mushroom) from the bottom of the lake for #DOQUEST“Sprinkle's Secret Ingredient”#", x = 40, y = 59, zone = "The Hinterlands" },
			[5] = { str = "5. Grind until you’re east of 57,47 and kill Silvermane Stalkers for #DOQUEST“Food For Baby”#", x = 57, y = 47, zone = "The Hinterlands" },
			[6] = { str = "6. Run back to Aerie Peak and go to the bottom floor of the Inn" },
			[7] = { str = "7. Turn in #TURNIN“Food For Baby”# accept #ACCEPT“Becoming A Parent”# then turn it back in. Cute pet and good xp =)" },
			[8] = { str = "8. Hearth to IF and fly to BB" },
		}
	},

-----------48-49 Stranglethorn Vale
	--[412] = {
	[4849] = {
		title = "48-49 Stranglethorn Vale",
		--n = "48-49 Stranglethorn Vale",
		--pID = 411, nID = 413,
		--itemCount = 27,
		items = {
			[1] = { str = "1. 48-49 Stranglethorn Vale" },
			[2] = { str = "2. Go down to the first floor of the Inn, make it your home" },
			[3] = { str = "3. Turn in #TURNIN“Back To Booty Bay”# and #TURNIN“Whiskey Slim's Lost Grog”#" },
			[4] = { str = "4. Enter the house next to the upside down, half ship, turn in #TURNIN“Deliver to MacKinley”#" },
			[5] = { str = "5. Under that boat outside, accept #ACCEPT“Stranglethorn Fever”#" },
			[6] = { str = "6. Go up the ramp and first house past the bridge, turn in all of the robot chicken escorts you’ve gotten. I didn’t get the Tanaris one while writing this guide so I missed out on the quest to get 7100 extra exp" },
			[7] = { str = "7. Near the boat, accept #ACCEPT“The Captain's Chest”#" },
			[8] = { str = "8. Go kill gorillas around 34,63 for #DOQUEST“Stranglethorn Fever”# then go up into the cave at 35,60 turn it in. the guy in the cave asks for 10 gorilla fangs, then he summons 3 waves of gorillas. Mokk is in the 3rd wave. They’re all around level 42-44 it starts with 3, then 5 then I think 6 or 7. It can get tough. Just kill Mokk first in case you die.", x = 35, y = 60, zone = "Stranglethorn Vale" },
			[9] = { str = "9. Go up to 38,34 and kill #NPCKing Bangalash# for #DOQUEST“Big Game Hunter”# he spawns level 33 minions. You can kill him before a few come out.", x = 38, y = 34, zone = "Stranglethorn Vale" },
			[10] = { str = "10. Run up to 48,25 and kill the elite ogres all around here until Maury’s Key drops for #DOQUEST“Cracking Maury’s Foot”# If you don’t find this after an hour just abandon the quest. It has a low drop rate. I grind until i'm 2 bars from level 49 if I don’t get the key. Usally it’s about an hours worth.", x = 48, y = 25, zone = "Stranglethorn Vale" },
			[11] = { str = "11. Go up to Nessingways at 35,10 and turn in #TURNIN“Big Game Hunter”#", x = 35, y = 10, zone = "Stranglethorn Vale" },
			[12] = { str = "12. Hearth to Booty Bay, run up to the half boat just outside the Inn" },
			[13] = { str = "13. Turn in #TURNIN“Stranglethorn Fever”#" },
			[14] = { str = "14. Run to the shore just east of BB and open blue bottles until you get Carefully Folded Note which starts #ACCEPT“Message in A Bottle pt.1”#" },
			[15] = { str = "15. Go to 36,69 and kill #NPCGorlash# for #DOQUEST“The Captain's Chest”# He’s a 47 elite, it can be tough but I did it. Use everything you have", x = 36, y = 69, zone = "Stranglethorn Vale" },
			[16] = { str = "16. Go to 38,80 and turn in #TURNIN“Message in A Bottle pt.1”# SKIP the next part, unless you can get a group to kill the 51 ape", x = 38, y = 80, zone = "Stranglethorn Vale" },
			[17] = { str = "17. Go down to the pirate ships, 1 is at 33,87 and the other 2 are at 30,88 You want to go to the 2nd floor near the front of the ship and kill the captain of each for #DOQUEST“The Bloodsail Buccaneers pt.5”#", x = 33, y = 87, zone = "Stranglethorn Vale" },
			[18] = { str = "18. Look for a scroll on one of the ships called Cortello's Riddle which starts #ACCEPT“Cortello's Riddle pt.1”#" },
			[19] = { str = "19. If hearth is up, use it, otherwise die so you end up at BB" },
			[20] = { str = "20. Go near the boat, turn in #TURNIN“The Captain's Chest”#" },
			[21] = { str = "21. Go up top of the Inn, turn in #TURNIN“The Bloodsail Buccaneers pt.5”#" },
			[22] = { str = "22. Fly to SW and go to 64,20 turn in #TURNIN“Rhapsody's Tale”# SKIP the rest", x = 64, y = 20, zone = "Stormwind" },
			[23] = { str = "23. From here on, either look at the AH when you go by one, or use your AH char to search for your Beaststalker Bracers. I got mine for 8g also look for a mithril casing for later in Un’Goro" },
			[24] = { str = "24. Fly to Duskwood" },
			[25] = { str = "25. Run east through Deadwind Pass to the Swamp of Sorrows" },
			[26] = { str = "26. Follow the road until it forks and the left fork has a bridge at 22,48 and under it is A Soggy Scroll which turns in #TURNIN“Cortello's Riddle pt.1”# accept #ACCEPT“Cortello's Riddle pt.2”#", x = 22, y = 48, zone = "Swamp of Sorrow" },
			[27] = { str = "27. Run down to the Blasted Lands" },
		}
	},
	
--------49-50 Blasted Lands
	--[413] = {
	[4950] = {
		title = "49-50 Blasted Lands",
		--n = "49-50 Blasted Lands",
		--pID = 412, nID = 501,
		--itemCount = 30,
		items = {
			[1] = { str = "1. 49-50 Blasted Lands" },
			[2] = { str = "2. No need to rush through this zone, so grind on anything you see." },
			[3] = { str = "3. Stop at 50,14 and accept the following 5 quests: #ACCEPT“The Basilisk's Bite”# #ACCEPT“Vulture's Vigor”# #ACCEPT“Snickerfang Jowls”# #ACCEPT“A Boar's Vitality”# and #ACCEPT“The Decisive Striker”#", x = 50, y = 14, zone = "Blasted Lands" },
			[4] = { str = "4. You’re going to need the following amount of items to complete all 5 of these quests. Snickerfang Jowls:5, Blasted Boar Lungs:6, Scorpok Pincers:6, Basilisk Brain:11, Vulture Gizzards:14 It’s going to be like grinding getting all this so you’re killing 2 birds with 1 stone. You’ll most likely gain half a level before you turn these in." },
			[5] = { str = "5. Just circle the center of the map and you’ll find all the stuff you need to kill. I’d mark it with coords but there would be way too many. You might want to avoid anything level 53 and up which are farther to the south. You should make some nice money with skinning here." },
			[6] = { str = "6. You should be close to 3 ½ bars into level 49 now" },
			[7] = { str = "7. Grind down to 51,35 and accept #ACCEPT“Everything Counts In Large Amounts”# If you do find one of these, hand it back in when you pass her, you’re bound to find at least one while here. Don’t even bother with the other quest you’ll Never find it. I’ve been playing WoW since release and never found one. ", x = 51, y = 35, zone = "Blasted Lands" },
			[8] = { str = "8. Go to 50,14 and turn in the 5 quests, #TURNIN“The Basilisk's Bite”# #TURNIN“Vulture's Vigor”# #TURNIN“Snickerfang Jowls”# #TURNIN“A Boar's Vitality”# and #TURNIN“The Decisive Striker”# but turn in the one you want the most last, because you get buffed and get an item as well. These each give 4700 xp", x = 50, y = 14, zone = "Blasted Lands" },
			[9] = { str = "9. Go to Nethergarde Keep to the top of the tall tower at 66,19 and turn in #TURNIN“Thadius Grimshade”# SKIP the next part.", x = 66, y = 19, zone = "Blasted Lands" },
			[10] = { str = "10. You should be close to 70% into level 49 now.  If you don’t want to do ZF to hit 50, grind here until you’re about 13k from level 50. If you want do ZF go to the next step." },
			[11] = { str = "11. Hearth to Booty Bay" },
			[12] = { str = "12. Accept #ACCEPT“Zanzil's Mixture”# and #ACCEPT“A Fool's Stout”#" },
			[13] = { str = "13. Get on the boat to Ratchet" },
			[14] = { str = "14. Accept #ACCEPT“Volcanic Activity”# at the first hut off the dock" },
			[15] = { str = "15. Just outside this hut is a green chest, open it for #DOQUEST“The Stone Circle”#" },
			[16] = { str = "16. Fly to Tanaris" },
			[17] = { str = "17. Go near the NW entrance, turn in #TURNIN“Sprinkle's Secret Ingredient”# accept #ACCEPT“Delivery For Marin”#" },
			[18] = { str = "18. Go back near the South entrance and turn in #TURNIN“Delivery For Marin”# accept #ACCEPT“Noggenfogger Elixir”# then turn it back in. You will recieve 5 elixirs and be able to purchase them." },
			[19] = { str = "19. Run in the Shimmering Flats to 77,77 and turn in #TURNIN“Zanzil's Mixture”# and #TURNIN“A Fool's Stout”# accept #ACCEPT“Get the Goblins Drunk”# go to 79,76 and turn it in.", x = 77, y = 77, zone = "Thousand Needles" },
			[20] = { str = "20. Go back to 77,77 and accept #ACCEPT“Report Back to Fizzlebub”#", x = 77, y = 77, zone = "Thousand Needles" },
			[21] = { str = "21. Go to 52,45 and turn in #TURNIN“The Stone Circle” SKIP the rest unless you plan on doing the Sunken Temple.", x = 52, y = 45, zone = "Thousand Needles" },
			[22] = { str = "22. You should be about 30k from level 50 now, like I said above, either go do ZF or you should have grinded in Blasted Lands." },
			[23] = { str = "23. If you do ZF you only really need to complete at least 2-3 of the following quests #DOQUEST“Troll Temper”# #DOQUEST“Divino-matic Rod”# #DOQUEST“Gahz'rilla”# #DOQUEST“The Prophecy of Mosh'Aru”# I highly suggest getting  #ACCEPT“Divino-matic Rod”# and #ACCEPT“Gahz'rilla”# because you get an awesome ring and a mount speed inscrease trinket." },
			[24] = { str = "24. Now you should be about 1-2 bars into level 50 if you went to ZF. From here on out there is a lot more fresh content, as you seen 45-50 is a pain in the ass. We still have a lot of untouched areas to level in now." },
			[25] = { str = "25. Hearth to BB and turn in #TURNIN“Report Back to Fizzlebub”#" },
			[26] = { str = "26. Fly to IF to get new skills and accept the quest #ACCEPT“The Hunter's Charm”#" },
			[27] = { str = "27. Make sure you get at least 15 Silk Cloth out of the mailbox or AH alt" },
			[28] = { str = "28. Make IF your home and accept #ACCEPT“Assisting Arch Druid Staghelm”#" },
			[29] = { str = "29. Fly to Thelsamar" },
			[30] = { str = "30. Run down into the Badlands all the way west to 1,62 and enter the Searing Gorge", x = 1, y = 62, zone = "Badlands" },
		}
	},
}
