--[[--------------------------------------------------
003_Alliance_40to50.lua
Authors: mrmr
Version: 1.04.3
------------------------------------------------------
Description: Guide Serie - 003 From Lvl 40 to Lvl 50
    1.04.1
        -- First Release
            Alliance's Guide
            from level 40 to lever 50
    1.04.2
    	-- no changes in here for this revision
	1.04.3
		-- Added color codes
			Fixed various spelling errors
	1.05.0
        -- Added Hunter Sepecfic steps
        -- Still do in this section add numbered steps to rest of this guide, add qoutes to Quests, add COORDS color to travel directions, and check to see if NPC color has been missed used
	1.1.0
		-- Автор перевода и актуализации: Eynschteyn
------------------------------------------------------
Connection:
--]]--------------------------------------------------

Table_003_Alliance_40to50 = {
-----------40-41 Badlands
	--[401] = {
	[4041] = {
		title = "40-41 Badlands",
		--n = "40-41 Badlands",
		--pID = 312, nID = 402,
		--itemCount = 39,
		items = {
			[1] = { str = "1. 40-41 Badlands" },
			[2] = { str = "2. Идите в точку 53,43 берите задание  #ACCEPT“Fiery Blaze Enchantment”#,  #ACCEPT“Mirages”#,  и  #ACCEPT“A Dwarf and His Tools”#", x = 53, y = 43, zone = "Badlands" },
			[3] = { str = "3. Дойдите до точки 42,52 и сдайте задание  #TURNIN“Martek the Exiled”#  берите следующее  #ACCEPT“Indurium”#", x = 45, y = 52, zone = "Badlands" },
			[4] = { str = "4. Возьмите задание  #ACCEPT“Barbecued Buzzard Wings”#  и  #ACCEPT“Pearl Diving”# (если вы купили ранее на аукционе жемчужины для задания) и сразу сдайте это задание." },
			[5] = { str = "5. Стервятники нужны для выполнения 2х заданий. Паком обитают в точке 16,60 у каргата так что убивайте их всякий раз когда увидите на своем пути." },
			[6] = { str = "6. Идите по координатам 25,44 возьмите задание  #ACCEPT“Study of the Elements: Rock pt.1”#" },
			[7] = { str = "7. Следующие задания  #ACCEPT“Coolant Heads Prevail”#,  #ACCEPT“Gyro… What?”#  возьмите и сдайте (Если вы ранее приобрели на аукционе необходимые предметы или достали каким то другим способом).", x = 25, y = 44, zone = "Badlands" },
			[7] = { str = "7. Это задание  #ACCEPT“Liquid Stone”#  НПС может дать не сразу, задание может появиться после выполнения задания Study of the Elements: Rock pt.3 в этой локиции если есть необходимые банки в сумке сдайте это задание." },
			[8] = { str = "8. #HUNTERЗадание для охотников. Идите в точку 20,53 и приручите Ridge Stalker Patriarch и выучите способность питомца dash и prowl 2го ранга.#", x = 20, y = 53, zone = "Badlands" },
			[9] = { str = "9. #HUNTERЗадание для охотников. Жмите #PICTUREHearth# в Thelsamar, заберите кота обратно, НЕ ОТПУСКАЙТЕ ПЕТА идите обратно с катом в Badlands.#" },
			[10] = { str = "10. Убивайте мобов пока идете в точку 66,21 там откройте ящик для задания  #DOQUEST“Mirages”#", x = 66, y = 21, zone = "Badlands" },
			[11] = { str = "11. Идите к месту раскопок в точку 53,29 и убивайте дворфов для задания  #DOQUEST“A Dwarf and His Tools”#  Справа от ямы в точке 53,33 коснитесь записки в палатке что бы получить задание  #DOQUEST“A Sign of Hope”#", x = 53, y = 29, zone = "Badlands" },
			[12] = { str = "12. Гриндите мобов до точки 53,43 и сдайте задание  #TURNIN“Mirages”#  берите следующее  #ACCEPT“Scrounging”#", x = 53, y = 43, zone = "Badlands" },
			[13] = { str = "13. Так же сдайте задания  #TURNIN“A Dwarf and His Tools”#  и  #TURNIN“A Sign of Hope”#  берите следующую часть в Uldaman'e" },
			[14] = { str = "14. Гриндите мобов до точки 61,54 и возьмите задание  #ACCEPT“Tremors of the Earth”#  огры ходят от точки 62,70  до точки 29,56 босса убить легко либо выманить его с малым количеством охраны.", x = 61, y = 54, zone = "Badlands" },
			[15] = { str = "15. Идите на юг в точку 62,70 и убивайте огров (убейте всех огров сколько есть) для задания  #DOQUEST“Scrounging”#  тут может проходить босс из предыдущего задания от этой точки идите по югу локации в точку 16,80 убивайте птиц и ищите босса.", x = 62, y = 70, zone = "Badlands" },
			[16] = { str = "16. Гриндите до точки 50,62 сдайте задание  #TURNIN“Find Agmond”#  и возьмите следующее  #ACCEPT“Murdaloc”#", x = 50, y = 62, zone = "Badlands" },
			[17] = { str = "17. Отправляйтесь немного южнее в лагерь гноллов и выполните задание  #DOQUEST“Murdaloc”#  и  #DOQUEST“Indurium”#" },
			[18] = { str = "18. Проверьте если вы выполнили 2 задания из этого пункта идите в точку 42,52 и сдайте  #TURNIN“Barbecued Buzzard Wings”#  и  #TURNIN“Indurium”#  берите следующее  #ACCEPT“News for Fizzle”#", x = 45, y = 52, zone = "Badlands" },
			[19] = { str = "19. Идите в точку 18,41 и убивайте lesser rock elementals для задания  #DOQUEST“Study of the Elements: Rock pt.1”#  и  #DOQUEST“Badlands Reagent Run”#", x = 18, y = 41, zone = "Badlands" },
			[20] = { str = "20. Вернитесь в точку 26,44 и сдайте задание  #TURNIN“Study of the Elements: Rock pt.1”#  берите следующее  #ACCEPT“Study of the Elements: Rock pt.2”#  и выполните его убивая rock elementals", x = 26, y = 44, zone = "Badlands" },
			[21] = { str = "21. Вернитесь в точку 26,44 и сдайте задание  #TURNIN“Study of the Elements: Rock pt.2”#  берите следующее  #ACCEPT“Study of the Elements: Rock pt.3”#", x = 26, y = 44, zone = "Badlands" },
			[22] = { str = "22. Убивайте Стервятников в точке 15,60 и Койотов в токе 33,62 для задания  #DOQUEST“Badlands Reagent Run”# если они вам еще нужны", x = 33, y = 62, zone = "Badlands" },
			[23] = { str = "23. Гриндите до точки 11,77 и убивайте огров для задания  #DOQUEST“Scrounging”#", x = 11, y = 77, zone = "Badlands" },
			[24] = { str = "24. Убивайте greater rock elementals в точке 14,88 для задлания  #DOQUEST“Study of the Elements: Rock#", x = 14, y = 88, zone = "Badlands" },
			[25] = { str = "25. Идите назад в точку 26,44 сдайте задание  #TURNIN“Study of the Elements: Rock pt.3”#" },
			[26] = { str = "26. Сейчас у вас должно открыться задание из 7 шага возьмите его и сдайте если не сдавали его раньше (все необходимое должно быть у вас в инвентаре купленное на ауке)" },
			[27] = { str = "27. Возьмите задание  #ACCEPT“This Is Going To Be Hard pt.1”# и сдайте его рядом, возьмите следующее задание  #ACCEPT“This Is Going To Be Hard pt.2”# и снова сдайте его рядом, возьмите следующее задание  #ACCEPT“This Is Going To Be Hard pt.3”#", x = 26, y = 44, zone = "Badlands" },
			[28] = { str = "28. Убейте призванного элементаля он 45 уровня. Затем сдайте его и получите свой Nifty Stopwatch" },
			[29] = { str = "29. Идите в точку 53,43 и сдайте  #TURNIN“Scrounging”#", x = 53, y = 43, zone = "Badlands" },
			[30] = { str = "30. Идите в точку 61,54 и сдайте заадние  #TURNIN“Tremors of the Earth”# следующее задание ПРОПУСТИТЕ", x = 61, y = 54, zone = "Badlands" },
			[31] = { str = "31. Сейчас у вас должен быть 41 уровень, если вы не получили 41 уровень идите на восток и гриндите детенышей драконов the whelps. Если вы получили 41 уровень на велпах то желательно еще погриндить их тут минут 30 что был запас по опыту если вы не выбили с них heart для задания  #DOQUEST“Fiery Blaze Enchantment”#  за это время то бросьте это задание." },
			[32] = { str = "32. Жмите Hearth в Thelsamar" },
			[33] = { str = "33. Идите в дом за гостиницей и сдайте задание  #TURNIN“Badlands Reagent Run”#  берите часть заданий относящиеся к Uldaman" },
			[34] = { str = "34. Бегите в точку 65,65 и сдайте задание  #TURNIN“Murdaloc”#  берите еще задание Uldaman. Сейчас я уже заполнил полоску опыта на 25% до 41 уровня", x = 65, y = 65, zone = "Loch Modan" },
			[35] = { str = "35. Летите в SW и идите в точку 64,20 и возьмите задание  #ACCEPT“In Search of The Temple”#", x = 64, y = 20, zone = "Stormwind" },
			[36] = { str = "36. Возьмите еще одно задание в башне по координатам 37,81 #ACCEPT“Vital Supplies”#" },
			[37] = { str = "37. Летите в Duskwood и сдайте задание #TURNIN“Vital Supplies”# у дома, следующее задание пока ПРОПУСТИТЕ" },
			[38] = { str = "38. Сделайте Duskwood своим домом" },
			[39] = { str = "39. Бегите в Swamp of Sorrows" },
		}
	},

-----------41-41 Swamp of Sorrows
	--[402] = {
	[4141] = {
		title = "41-41 Swamp of Sorrows",
		--n = "41-41 Swamp of Sorrows",
		--pID = 401, nID = 403,
		--itemCount = 28,
		items = {
			[1] = { str = "1. 41-41 Swamp of Sorrows" },
			[2] = { str = "2. Бегите в Swamp of Sorrows, в точку 12,58  и убивайте whelps для задания  #DOQUEST“Dream Dust In the Swamp”#  шанс выпадения квестовых предметов низкий.", x = 12, y = 58, zone = "Swamp of Sorrows" },
			[3] = { str = "3. Идите в точку 26,59 и возьмите задание  #ACCEPT“Enroaching Wildlife”#  и начинайте его выполнять все мобы находятся не далеко отсюда.", x = 26, y = 59, zone = "Swamp of Sorrows" },
			[4] = { str = "4. Идите в точку 43,38 от этой точки идите на восток и ищите НПС Noboru the Cudgel  и получите предмет который начинает задание  #ACCEPT“Noboru the Cudgel”# для поиска НПС сделайте макрос /tar nobo т.к. моб ходит в той области", x = 43, y = 38, zone = "Swamp of Sorrows" },
			[5] = { str = "5. Вернитесь в точку 26,59 и сдайте задание  #TURNIN“Enroaching Wildlife”#  возьмите следующее  #ACCEPT“The Lost Caravan”#", x = 26, y = 59, zone = "Swamp of Sorrows" },
			[6] = { str = "6. Гриндите мобов по пути в точку 25,31  и сдайте задание  #TURNIN“Noboru the Cudgel”#  возьмите следующее  #ACCEPT“Draenethyst Crystals”#", x = 25, y = 31, zone = "Swamp of Sorrows" },
			[7] = { str = "7. Идите в точку 54,29 и начинайте собирать кристаллы для задания  #DOQUEST“Draenethyst Crystals”#", x = 54, y = 29, zone = "Swamp of Sorrows" },
			[8] = { str = "8. Добравшись до последнего лагеря в точке 65,18 где находится НПС первым делом заберите сундук с повозки с лева это необходимо для выполнения задания  #DOQUEST“The Lost Caravan”#", x = 65, y = 18, zone = "Swamp of Sorrows" },
			[9] = { str = "9. Обязательно зачистите лагерь рядом с НПС в клетке." },
			[10] = { str = "10. Берите задание  #ACCEPT“Galen’s Escape”#  его выполнить просто если вы зачистили лагерь." },
			[11] = { str = "11. Гриндите мобов по пути к точке 48,39 потрепаная палатка, откройте сундук что бы выполнить задание  #DOQUEST“Galen’s Escape”#", x = 48, y = 39, zone = "Swamp of Sorrows" },
			[12] = { str = "12. Вернитесь назад в точку 26,31 и сдайте задание  #TURNIN“Draenethyst Crystals”#", x = 26, y = 31, zone = "Swamp of Sorrows" },
			[13] = { str = "13. Идите в точку 26,59 и сдайте задание  #TURNIN“The Lost Caravan”#  берите следующее задание  #ACCEPT“Driftwood”#", x = 26, y = 59, zone = "Swamp of Sorrows" },
			[14] = { str = "14. Направляйся на юг в Blasted Lands в точку 36,59 к крепости Nethergarde Keep в точку 54,78. Откройте полетчика и летите Darkshire.", x = 54, y = 78, zone = "Blasted Lands" },
			[15] = { str = "15. #HUNTERОставьте кошку в стойле и возьмите другую из Badlands.#" },
			[16] = { str = "16. Возьмите задание  #ACCEPT“Supplies for Nethergarde”#" },
			[17] = { str = "17. Летите в крепость Nethergarde и сдайте задание  #TURNIN“Supplies for Nethergarde”#." },
			[18] = { str = "18. Вернитесь обратно в Swamp of Sorrows." },
			[19] = { str = "19. Бегите к озеру вогруг подземелья Sunken Temple в точке 70,54 и разведайте территорию для задания  #DOQUESTIn Search of The Temple#", x = 70, y = 54, zone = "Swamp of Sorrows" },
			[20] = { str = "20. Идите в точку 76,6 и начинайте убивать крабов и для задания  #DOQUEST“… and bugs”# пока не выполните задание. Ищите сухие деревья на берегу для задания  #DOQUEST“Driftwood”#", x = 76, y = 6, zone = "Swamp of Sorrows" },
			[21] = { str = "21. #HUNTERКогда вы выполните предыдущие 2 задания отпустите кошку и приручите silt crawler 40-41 уровня что бы выучить способность claw 6 ранга.#" },
			[22] = { str = "22. Жмите #PICTUREHearth# в Darkshire #HUNTERЗаберите свою кошку обратно из стойла.#" },
			[23] = { str = "23. Летите в Nethergarde и бегите назад в Swamp of Sorrows." },
			[24] = { str = "24. Идите в точку 26,59 и сдайте задание  #TURNIN“Driftwood”#  берите следующее  #ACCEPT“Deliver the Shipment”#.", x = 26, y = 59, zone = "Swamp of Sorrows" },
			[25] = { str = "25. Идите в Blasted Lands и сдайте задание  #TURNIN“Deliver the Shipment”#  в точке 66,21.", x = 66, y = 21, zone = "Blasted Lands" },
			[26] = { str = "25. Летите в Booty Bay и сдайте задание  #TURNIN“Dream Dust In the Swamp”#  возьмите новое задание  #ACCEPT“Rumors for Kravel”#." },
			[27] = { str = "27. Садитесь на корабль до Rachet и летите в Theramore и сдайте задание  #TURNIN“… and bugs”#  в гостинице." },
			[28] = { str = "28. Летите в Desolace." },
		}
	},

-----------41-42 Desolace
	--[403] = {
	[4142] = {
		title = "41-42 Desolace",
		--n = "41-42 Desolace",
		--pID = 402, nID = 404,
		--itemCount = 16,
		items = {
			[1] = { str = "1. 41-42 Desolace" },
			[2] = { str = "2. Сделайте Nijel’s Point вашим домом." },
			[3] = { str = "3. Берите задание  #ACCEPT“Down the Scarlet Path”#." },
			[4] = { str = "4. Спуститесь ниже и возьмите задание  #ACCEPT“Reagents For Reclaimers Inc pt.3”#" },
			[5] = { str = "5. Идите в точку 47,61 и возьмите задание  #ACCEPT“Ghost-O-Plasm Round Up”#.", x = 47, y = 61, zone = "Desolace" },
			[6] = { str = "6. Убивайте демонов в точке 51,75 для задания  #DOQUEST“Reagents For Reclaimers Inc pt.3”#.", x = 51, y = 75, zone = "Desolace" },
			[7] = { str = "7. Убивайте скелетов в точке 61,90 для задания  #DOQUEST“Down the Scarlet Path”#  и  #DOQUEST“Ghost-O-Plasm Round Up”#.", x = 61, y = 90, zone = "Desolace" },
			[8] = { str = "8. Когда вы выполните задания из пункта выше вы должны быть уже 42 уровня. Если нет можете тут его добить гриндя мобов." },
			[9] = { str = "9. Вернитесь в точку 47,61 и сдайте задание  #TURNIN“Ghost-O-Plasm Round Up”#", x = 47, y = 61, zone = "Desolace" },
			[10] = { str = "10. Жмите Hearth в Nijel’s Point" },
			[11] = { str = "11. Сдайте задание  #TURNIN“Down the Scarlet Path”# следующее задание ПРОПУСТИТЕ." },
			[12] = { str = "12. Идите южнее гостиницы сдайте задание  #TURNIN“Reagents For Reclaimers Inc pt.3”#  возьмите следующее  #ACCEPT“Reagents For Reclaimers Inc pt.4”#." },
			[13] = { str = "13. Летите в Theramore, далее плывите на коробле в Menethil и летите в Ironforge (Стальгорн)." },
			[14] = { str = "14. Сдайте задание  #TURNIN“Reagents For Reclaimers Inc pt.4”# в точке 67,17.", x = 67, y = 17, zone = "Ironforge" },
			[15] = { str = "15. Выучите новые навыки у классового тренера." },
			[16] = { str = "16. Летите в Booty Bay." },
		}
	},
-----------42-43 Stranglethron Vale
	--[404] = {
	[4243] = {
		title = "42-43 Stranglethron Vale",
		--n = "42-43 Stranglethron Vale",
		--pID = 403, nID = 405,
		--itemCount = 30,
		items = {
			[1] = { str = "1. 42-43 Stranglethron Vale" },
			[2] = { str = "2. Зайдите в гостиницу и возьмите задание  #ACCEPT“Tran'Rek”#." },
			[3] = { str = "3. Сделайте Booty Bay своим домом." },
			[4] = { str = "4. Возьмите задания  #ACCEPT“Zanzil's Secret”#  и  #ACCEPT“Whiskey Slim's Lost Grog”#." },
			[5] = { str = "5. Подойдите к банку и возьмите задание  #ACCEPT“Akiris By the Bundle pt.1”#." },
			[6] = { str = "6. Зайдите в дом рядом с гостиницей и возьмите задание  #ACCEPT“Stoley's Debt”#" },
			[7] = { str = "7. Поднимитесь на 2й уровень причала и за углом возьмите задание  #ACCEPT“Keep An Eye Out”#" },
			[8] = { str = "8. Выходите из BB и поворачивайте направо и на юг в точке 31,79 и убивайте пиратов для заданий  #DOQUEST“Up To Snuff”#  и  #DOQUEST“Keep An Eye Out”#", x = 31, y = 79, zone = "Stranglethorn Vale" },
			[9] = { str = "9. Убивайте пиратов вокруг 2х лагерей в точке 29,81 и 27,82 для задания  #DOQUEST“The Bloodsail Buccaneers pt.4”# не забудьте взять 2 записки в лодке и на ящике у палатки", x = 27, y = 82, zone = "Stranglethorn Vale" },
			[10] = { str = "10. Вернитесь в BB и поверните на лево." },
			[11] = { str = "11. Сдайте задание  #TURNIN“Keep An Eye Out”# около кузнецы." },
			[12] = { str = "12. Идите в гостиницу и сдайте задание  #TURNIN“Up To Snuff”#" },
			[13] = { str = "13. Выйдите на улицу и сдайте задание  #TURNIN“The Bloodsail Buccaneers pt.4”#  и возьмите следующее  #ACCEPT“The Bloodsail Buccaneers pt.5”#" },
			[14] = { str = "14. Отправляйтесь убивать наг в точке 25,63 для задания  #DOQUEST“Akiris By the Bundle pt.1”#", x = 25, y = 63, zone = "Stranglethorn Vale" },
			[15] = { str = "15. Гриндите наг пока у вас не будет хотя бы 50% опыта до 43 уровня." },
			[16] = { str = "16. Поднимитесь к Ruins of Aboraz и убейте #NPCChucky# в точке 40,58 для задания  #DOQUEST“Voodoo Dues”#,  убивайте мобов для задания  #DOQUEST“Zanzil's Secret”# вам нужно только 8-10 штук.", x = 40, y = 58, zone = "Stranglethorn Vale" },
			[17] = { str = "17. Поднимитесь к Ruins of Jubawal и убейте #NPCJon-Jon# в точке 34,51 и #NPCMaury# в точке 35,51 для задания  #DOQUEST“Voodoo Dues”# и доделайте задание  #DOQUEST“Zanzil's Secret”#", x = 35, y = 51, zone = "Stranglethorn Vale" },
			[18] = { str = "18. В переди вас ждут дибильные элитные задания с 19 по 23 шаг. Если сервер открылся давно не тратьте время и просто гриндите мобов до условий из 24 шага" },
			[19] = { str = "19. Убейте #NPCTethis# для задания #DOQUEST“Raptor Mastery pt.4”#  за ареной в точке 31,43 затем сдайте его в лагере nessingways в точке 35,10 и возьмите следующее задание  #ACCEPT“Big Game Hunter”#", x = 31, y = 43, zone = "Stranglethorn Vale" },
			[20] = { str = "20. Идите к лагерю повстанцев в точке 38,3 и возьмите задание  #ACCEPT“Colonel Kurzen”#.", x = 38, y = 3, zone = "Stranglethorn Vale" },
			[21] = { str = "21. Идите в пещеру координаты 45,8 в сторону где раньше сундуку сдавали задание, идите дальше в глубь пешеры убивайте нужных мобов в конце элитный моб (если у мобов включится аура отойдите от него) для задания #DOQUEST“Colonel Kurzen”# Kurzen в точке 49,3", x = 49, y = 3, zone = "Stranglethorn Vale" },
			[22] = { str = "22. Специально умрите чтобы оказаться рядом с лагере повстанцев." },
			[23] = { str = "23. Идите в лагерь повстанцев в точку 38,3 и сдайте задание  #TURNIN“Colonel Kurzen”#.", x = 38, y = 3, zone = "Stranglethorn Vale" },
			[24] = { str = "24. Убивайте тролей в точке 44,34 пока у вас не будет хватать 9000 опыта до следующего уровня.", x = 44, y = 34, zone = "Stranglethorn Vale" },
			[25] = { str = "25. Жмите Hearth в Booty Bay" },
			[26] = { str = "26. Сдайте задание  #TURNIN“Zanzil's Secret”#" },
			[27] = { str = "27. Спуститесь к банку и сдайте задание  #TURNIN“Akiris By the Bundle pt.1”#  и возьмите следующее  #ACCEPT“Akiris By the Bundle pt.2”#" },
			[28] = { str = "28. Идите к дому около полулодки и сдайте задание  #TURNIN“Voodoo Dues”#  возьмите следующее  #ACCEPT“Cracking Maury's Foot”#" },
			[29] = { str = "29. Плывите на лодке до Rachet затем летите в Theramore." },
			[30] = { str = "30. Сдайте задание  #TURNIN“Akiris By the Bundle pt.2”#  на пристани и летите в Gadgetzan" },
		}
	},

-----------43-43 Tanaris
	--[405] = {
	[4343] = {
		title = "43-43 Tanaris",
		--n = "43-43 Tanaris",
		--pID = 404, nID = 406,
		--itemCount = 35,
		items = {
			[1] = { str = "1. 43-43 Tanaris" },
			[2] = { str = "2. Возьмите задания  #ACCEPT“Wastewander Justice”# и  #ACCEPT“Water Pouch Bounty”#." },
			[3] = { str = "3. Сделайте Gadgetzan своим домом." },
			[4] = { str = "4. Идите к двери клетки и возьмите 2 задания с таблички  #ACCEPT“WANTED: Caliph Scorpidsting”#  и  #ACCEPT“WANTED: Andre Firebeard”#." },
			[5] = { str = "5. Сдайте задание  #TURNIN“Tran'Rek”# следующее задание ПРОПУСТИТЕ." },
			[6] = { str = "6. С левой стороны города на холме возьмите задание  #ACCEPT“Gadgetzan Water Survey”#" },
			[7] = { str = "7. Идите на север в соседнюю локацию The Shimmering Flats в точку 77,77 и сдайте задание  #TURNIN“Rumors for Kravel”#  и возьмите следующее  #ACCEPT“Back to Booty Bay”#", x = 77, y = 77, zone = "Thousand Needles" },
			[8] = { str = "8. Тут рядом сдайте задание  #TURNIN“News for Fizzle”#" },
			[9] = { str = "9. Идите в точку 80,75 и возьмите задание #ACCEPT“Keeping Pace”#. (Далее нужно активировать скрипт) южнее под навесом должен стоять НПС zamek у него над головой длжен быть синий знак #PICTURE?# не идите за ним идите к дому rizzles в точке 77,77 когда он уйдет троньте чертежи и сдайте задание #TURNIN“Keeping Pace”# и возьмите следующее #ACCEPT“Rizzle's Schematics”# и сдайте его в точке 80,75 (на сервере кронос 5 это задание не работает в 2026 году)", x = 80, y = 75, zone = "Thousand Needles" },
			[10] = { str = "10. Жмите Hearth в Gadgetzan" },
			[11] = { str = "11. Идите в Steamwheedle Port в точку 59,80", x = 59, y = 80, zone = "Tanaris" },
			[12] = { str = "12. Сдайте задание  #TURNIN“Stoley's Debt”#  в южном доме и возьмите задание  #ACCEPT“Stoley’s Shipment”#  и  #ACCEPT“Southsea Shakedown”#" },
			[13] = { str = "13. Идите к северному дому и возьмите задание  #ACCEPT“Pirate Hats Ahoy!”#  и  #ACCEPT“Screecher Spirits”#" },
			[14] = { str = "14. Идите в точку 63,30 и убивайте там мобов для задания  #DOQUEST“Wastewander Justice”#  и  #DOQUEST“Water Pouch Bounty”#  Выслидите моба #NPCCaliph Scorpidsting# и убейте для задания  #ACCEPT“WANTED: Caliph Scorpidsting”#.  У него 2 охранника в инвизе но убить его всеравно довольно легко.", x = 63, y = 30, zone = "Tanaris" },
			[15] = { str = "15. Бегите до пещеры в точке 68,41 и пройдите через ее в бухту.", x = 68, y = 41, zone = "Tanaris" },
			[16] = { str = "16. Начинайте гиноцид пиратов для заданий  #DOQUEST“Southsea Shakedown”#  и  #DOQUEST“Pirate Hats Ahoy!”#" },
			[17] = { str = "17. Убивая пиратов с них выпадают сундуки в которых могут быть 3 части карты верхняя, средняя и нижняя соберите их в единую карту. Так же выпадает #NPCShip Schedule# если собрали карту и свиток берите задания #ACCEPT“Cuergo’s Gold”# и #ACCEPT“Ship Schedules”#" },
			[18] = { str = "18. Выполните задания из предыдущего пункта если они вам выпали предметы. В задании #ACCEPT“Ship Schedules”# нужно поговорить с тролем в Steamwheedle Port в точке 59,80, а в задании #ACCEPT“Cuergo’s Gold”# примерно в точке 53,95 нужно открыть сундук. Если не выбили эти предметы то пропустите этот пункт." },
			[19] = { str = "19. Убейте #NPCAndre Firebeard# в точке 73,47 для задания  #ACCEPT“WANTED: Andre Firebeard”#", x = 73, y = 47, zone = "Tanaris" },
			[20] = { str = "20. Идите в двух этажный дом в точке 72,46 и заберите краденное вино для задания  #DOQUEST“Stoley’s Shipment”#. Оно находится на 2м этаже.", x = 72, y = 46, zone = "Tanaris" },
			[21] = { str = "21. Жмите Hearth в Gadgetzan" },
			[22] = { str = "22. Сдайте задание  #TURNIN“Wastewander Justice”#  и возьмите следующее  #ACCEPT“More Wastewander Justice”#" },
			[23] = { str = "23. Сдайте задание  #TURNIN“WANTED: Caliph Scorpidsting”#  и  #TURNIN“Water Pouch Bounty”#" },
			[24] = { str = "24. Вы должны быть близки к 50% опыта до 44 уровня." },
			[25] = { str = "25. Идите на запад по координатам 39,29 и выполните задание  #DOQUEST“Gadgetzan Water Survey”#  сразу после сбора оброзца на вас нападут мобы 47 и 48 уровня, Бегите.", x = 32, y = 29, zone = "Tanaris" },
			[26] = { str = "26. Вернить назад в Gadgetzan и сдай задание  #TURNIN“Gadgetzan Water Survey”#  и возьмите  #ACCEPT“Noxious Lair Investigation”#" },
			[27] = { str = "27. Выполните задание  #DOQUEST“More Wastewander Justice”#  в точке 60,35", x = 60, y = 35, zone = "Tanaris" },
			[28] = { str = "28. Вернитесь в порт Steamweedle Port в точку 59,80 к южному дому и сдайте задание  #TURNIN“Stoley’s Shipment”#  берите следующее  #ACCEPT“Deliver to MacKinley”#", x = 59, y = 80, zone = "Tanaris" },
			[29] = { str = "29. Сдайте  #TURNIN“WANTED: Andre Firebeard”#  и  #TURNIN“Southsea Shakedown”#" },
			[30] = { str = "30. Идите к соседнему дому и сдайте  #TURNIN“Pirate Hats Ahoy!”#" },
			[31] = { str = "31. Жмите Hearth в Gadgetzan" },
			[32] = { str = "32. Сдайте задание  #TURNIN“More Wastewander Justice”#" },
			[33] = { str = "33. Возьмите задание  #ACCEPT“Handle With Care”# в районе северной части города." },
			[34] = { str = "34. У вас должно быть 75% опыта до следующего уровня." },
			[35] = { str = "35. Летите в Feralas." },
		}
	},

-----------43-45 Feralas
	--[406] = {
	[4345] = {
		title = "43-45 Feralas",
		--n = "43-45 Feralas",
		--pID = 405, nID = 407,
		--itemCount = 43,
		items = {
			[1] = { str = "1. 43-45 Feralas" },
			[2] = { str = "2. В беседке со стороны воды возьмите задание  #ACCEPT“The Mark of Quality”#" },
			[3] = { str = "3. Сделайте Feralas своим домом." },
			[4] = { str = "4. Зайдите в большое здание напротив таверны и возьмите задание  #ACCEPT“The Missing Courier pt.1”#  и  #ACCEPT“The Ruins of Solarsal”#" },
			[5] = { str = "5. Идите к зданию расположенному чуть западнее и возьмите задание  #ACCEPT“In Search of Knowledge”#  и  #ACCEPT“The High Wilderness”#" },
			[6] = { str = "6. Поднимитесь наверх и сдайте задание  #TURNIN“The Missing Courier pt.1”#  и возьмите  #ACCEPT“The Missing Courier pt.2”#" },
			[7] = { str = "7. Идите к беседке в точку 26,52 и сдайте задание  #TURNIN“The Ruins of Solarsal”#  и возьмите  #ACCEPT“Return to Feathermoon Stronghold”#", x = 26, y = 52, zone = "Feralas" },
			[8] = { str = "8. Вернитесь к Feathermoon к большому зданию и сдайте задание  #TURNIN“Return to Feathermoon Stronghold”#  возьмите следующее  #ACCEPT“Against the Hatecrest pt.1”#  сдайте его рядом и возьмите следующее  #ACCEPT“Against the Hatecrest pt.2”#" },
			[9] = { str = "9. Убивайте наг в точке 26,54 для задания  #DOQUEST“Against the Hatecrest pt.2”#", x = 26, y = 54, zone = "Feralas" },
			[10] = { str = "10. Убивайте наг пока до следующего уровня не останется около 2500 опыта. Обычьно до начала гринда в этом месте у меня не хватает около 15000 опыта. За каждое убийство дают в среднем 200-250 опыта." },
			[11] = { str = "11. Вернитесь в Feathermoon к большому зданию и сдайте задание  #TURNIN“Against the Hatecrest pt.2”#  берите следующее  #ACCEPT“Against Lord Shalzaru”#" },
			[12] = { str = "12. Спуститесь в пещеру в точке 26,66 и убейте  #NPCLord Shalzaru#  для задания  #DOQUEST“Against Lord Shalzaru”#", x = 26, y = 66, zone = "Feralas" },
			[13] = { str = "13. Специально умрите что бы оказаться в Feathermoon" },
			[14] = { str = "14. Идите к большому зданию в Feathermoon и сдайте задание  #TURNIN“Against Lord Shalzaru”#  бериет следующее  #ACCEPT“Delivering the Relic”#  сдайте его в этом же здании." },
			[15] = { str = "15. Не топопитесь почените шмот, продайте мусор затем идите на корабль и плывите на материк." },
			[16] = { str = "16. Идите на юг от пристани и убивайте screechers для задания  #DOQUEST“Screecher Spirits”#, после убийства на него нужно заюзать предмет из сумки #NPCYeh'kinya's Bramble#" },
			[17] = { str = "17. Спуститесь в точку 45,65 коснитесь разбитой лодки (под водой) что бы сдать задание  #TURNIN“The Missing Courier pt.2”#  берите следующее  #ACCEPT“Boat Wreckage”#", x = 45, y = 65, zone = "Feralas" },
			[18] = { str = "18. Жмите Hearth в Feathermoon" },
			[19] = { str = "19. Зайдите в небольшое здание напротив гостиницы поднимитесь на второй этаж сдайте задание #TURNIN“Boat Wreckage”# и возьмите следующее  #ACCEPT“The Knife Revealed”#" },
			[20] = { str = "20. Поднимитесь на вершину большой винтовой башни сдайте задание  #TURNIN“The Knife Revealed”# и возьмите следующее #ACCEPT“Psychometric Reading”#" },
			[21] = { str = "21. Зайдите в небольшое здание напротив гостиницы на 2м этаже сдайте задание  #TURNIN“Psychometric Reading”#  и возьмите следующее  #ACCEPT“The Woodpaw Gnolls”#" },
			[22] = { str = "22. Плывите на корабле на материк." },
			[23] = { str = "23. Идите в пещеру йети в точку 56,56 и убивайте их для задания #DOQUEST“The Mark of Quality”#, если вы кожевник то сделаете это задание быстро", x = 56, y = 56, zone = "Feralas" },
			[24] = { str = "24. Если найдете предмет #NPCOOX-22/FE Distress Beacon# возьмите задание #ACCEPT“Find OOX-22/FE!”# и сдайте его в глубине пещеры. Следующее задание на сопровождение ПРОПУСКАЕМ." },
			[25] = { str = "25. Гриндите в восточной части убивая the Brutes в точке 60,56, warlocks и shamans в точке 59,66 для задния  #DOQUEST“The High Wilderness”#. Я убиваю всех подряд", x = 60, y = 56, zone = "Feralas" },
			[26] = { str = "26. Идите в точку 65,45 и возьмите задание  #ACCEPT“Freedom For All Creatures”#. Проведите НПС к клетке и откройте ее убивая всех вокруг пока не появится надпись о выполнении задания.", x = 65, y = 45, zone = "Feralas" },
			[27] = { str = "27. Сдайте задание и возьми  #ACCEPT“Doling Justice pt.1”# противники находятся в этом же лагере." },
			[28] = { str = "28. Сдайте задание  #TURNIN“Doling Justice pt.1”#  в точке 65,45 и возьмите следующее  #ACCEPT“Doling Justice pt.2”#", x = 65, y = 45, zone = "Feralas" },
			[29] = { str = "29. Спуститесь в точку 73,56 и коснитесь сумок которые висят на большом дереве около круглой клетки, сдайте задание #TURNIN“The Woodpaw Gnolls”#  и возьмите задание  #ACCEPT“The Writhing Deep”#", x = 73, y = 56, zone = "Feralas" },
			[30] = { str = "30. Нажмите правой кнопкой на рюкзак который вам только что упал в сумку и возьмите задание  #ACCEPT“Thalanaar Delivery”#, если квест лог полон отмените задание в ульдаман A Sing of Hope" },
			[31] = { str = "31. Спускайтесь к улию в точку 73,63 и идите до самого низа. Войдите в южный тунель и держитесь правой стороны там увидите кокон Zukk’Ash Pod Сдайте задание  #TURNIN“The Writhing Deep”#  и возьмите задание  #ACCEPT“Freed From the Hive”#, дождитесь окончания эвента", x = 73, y = 63, zone = "Feralas" },
			[32] = { str = "32. Жмите Hearth в Feathermoon" },
			[33] = { str = "33. Со стороны воды в беседке сдайте задание  #TURNIN“The Mark of Quality”#  и возьмите новое  #ACCEPT“Improved Quality”#" },
			[34] = { str = "34. Идите в небольшой дом на против гостиницы и сдайте задание  #TURNIN“The High Wilderness”#  затем поднимитесь на верх и сдайте  #TURNIN“Freed From the Hive”#  и возьмите  #ACCEPT“A Hero’s Welcome”#" },
			[35] = { str = "35. Идите в соседнее большое здание сдайте  #TURNIN“A Hero’s Welcome”#  и возьмите  #ACCEPT“Rise of the Silithid”#" },
			[36] = { str = "36. Летите в Thalanaar (полетчик между тысячей игл и фераласом) сдайте  #TURNIN“Thalanaar Delivery”# в точке 89,46", x = 89, y = 46, zone = "Feralas" },
			[37] = { str = "37. Летите в Rut'theran Village (Darnassus)" },
			[38] = { str = "38. Идите по пристани зайдите в дом и сдайте задание  #TURNIN“Handle With Care”#  возьмите следующее #ACCEPT“Favored of Elune?”#" },
			[39] = { str = "39. Поднимитесь наверх и сдайте  #TURNIN“In Search of Knowledge”#  затем пройдите в дальнюю часть дома на втором этаже откройте зеленую книгу и возьмите задание  #ACCEPT“Feralas: A History”#  сдайте задание ей и возьмите  #ACCEPT“The Borrower”#" },
			[40] = { str = "40. Выучите новые навыки" },
			[41] = { str = "41. Идите в храм луны по коодинатам 39,86 на втором этаже сдайте задания  #TURNIN“Rise of the Silithid”#  и  #TURNIN“Doling Justice pt.2”#", x = 39, y = 86, zone = "Feralas" },
			[42] = { str = "42. Купите 2 Elixir of Fortitude для последующего этапа этого задания." },
			[43] = { str = "43. Жмите Hearth в Feathermoon и летите в Gadgetzan и сдайте  #TURNIN“The Borrower”#  и возьмите  #ACCEPT“The Super Snapper FX”#" },
		}
	},

-----------45-46 Uldaman
	--[407] = {
	[4546] = {
		title = "45-46 Uldaman",
		--n = "45-46 Uldaman",
		--pID = 406, nID = 408,
		--itemCount = 9,
		items = {
			[1] = { str = "1. 45-46 Uldaman" },
			[2] = { str = "2. Сейчас выбирайте: гриндить гнолов в Feralas в точке 73,56 (сколько гриндить указано в пункте 6) или пройти ульдаман. Если группу собрать легко то лучше идите в ульдаман вы уже взяли несколько заданий туда еще задания можно взять в IF и Badlands. Сделав это вы должны получить необходимое количество опыта смотри 5 пункт. Не пропускайте этот этап, а то прийдется долго гриндить." },
			[3] = { str = "3. Собрать задания если они вам нужны лучше так: летите в Theramore садитесь на корабль до Menethil далее летите в IF (Стальгорн) и берите задания там, затем летите в Loch Modan и берите задания там, потом уже в Badlands" },
			[4] = { str = "4. Я взял задания в IF (Стальгорн): #ACCEPT“The Lost Dwarves”# в точке 74,11, #ACCEPT“Reclaimed Treasures”# в точке 74,9; в Loch Modan: #ACCEPT“Agmond's Fate”# в точке 65,65, #ACCEPT“Uldaman Reagent Run”# в точке 37,49; и в Badlands: #ACCEPT“A Sign of Hope”# в точке 53,43, #ACCEPT“Power Stones”# в точке 42,52 и #ACCEPT“Solution to Doom”# в точке 51,76. Вам не нужно выполнять их все и опять же это не обязательно просто это веселее чем гриндить. Я не люблю данжи, но у альянса заданий меньше чем у орды и я уже упоминал что на пути к 60 уровню прийдется гриндить 10-15% опыта. Идите группой из гильдии от 45+ уровня." },
			[5] = { str = "5. Смотрите карту Ульдамана с точками необходимыми для выполнения заданий в интернете если есть в этом трудности" },
			[6] = { str = "6. Можно остановиться примерно на 75% опыта до 47 уровня, но все же лучше прокачиваться дальше" },
			[7] = { str = "7. Когда закончите проходить данж сдайте все задания которые выполнили в Uldaman'e в обратном порядке порядке: Badlands, Loch Modan, IF (Стальгорн)" },
			[8] = { str = "8. Летите SW и сдайте задание #TURNIN“In Search of The Temple”# в точке 64,20 и возьмите следующее #ACCEPT“In Search of The Hinterlands”# изучите новые навыки и летите в Southshore", x = 64, y = 20, zone = "Stormwind" },
			[9] = { str = "9. Бегите по тропе в точку 84,33 вы увидите 2х грифонов идите дальше в The Hinterlands", x = 84, y = 33, zone = "Tarren Mill" },
		}
	},

-----------46-47 The Hinterlands
	--[408] = {
	[4647] = {
		title = "46-47 The Hinterlands",
		--n = "46-47 The Hinterlands",
		--pID = 407, nID = 409,
		--itemCount = 29,
		items = {
			[1] = { str = "1. 46-47 The Hinterlands" },
			[2] = { str = "2. Поднимитесь в точку 11,46 и сдайте задание  #TURNIN“In Search of The Hinterlands”#  возьмите  #TURNIN“Gryphon Master Talonaxe”#", x = 11, y = 46, zone = "The Hinterlands" },
			[3] = { str = "3. Откройте полетчика в точке 11,46 на самом верху затем зайдите в пещеру и сдайте  #TURNIN“Gryphon Master Talonaxe”#,  возьмите  #ACCEPT“Rhapsody Shindigger”#  и  #ACCEPT“Witherbark Cages”#", x = 11, y = 46, zone = "The Hinterlands" },
			[4] = { str = "4. Зайдите в гостинницу и поверните на право возьмите 2 задания  #ACCEPT“Skulk Rock Clean-Up”#  и  #ACCEPT“Troll Necklace Bounty”#" },
			[5] = { str = "5. Пройдите внутрь гостинницы в точку 13,41 и сделайте ее своим домом.", x = 13, y = 41, zone = "The Hinterlands" },
			[6] = { str = "6. Двигайтесь на восток в точку 20,48 следуя по тропе и собирая перья на земле для задания  #DOQUEST“Favored of Elune?”#  Вам пока нужны не все перья.", x = 20, y = 48, zone = "The Hinterlands" },
			[7] = { str = "7. Следуйте по тропе в точку 26,48 и сдайте задание  #TURNIN“Rhapsody Shindigger”#  возьмите  #ACCEPT“Rhapsody's Kalimdor Kocktail”#", x = 26, y = 48, zone = "The Hinterlands" },
			[8] = { str = "8. Спуститесь в лагерь тролей и уничтожте большенство из них в точке 23,58 затем откройте 2 клетки для задания  #DOQUEST“Witherbark Cages”#", x = 23, y = 58, zone = "The Hinterlands" },
			[9] = { str = "9. Идите на восток в точку 31,57 и откройте 3ю клетку для задания  #DOQUEST“Witherbark Cages”#", x = 31, y = 57, zone = "The Hinterlands" },
			[10] = { str = "10. Для выполнения #DOQUEST“Troll Necklace Bounty”# вам понадобится 5 ожерелий." },
			[11] = { str = "11. Идите на северовосток в точку 46,42 собирая перья по пути если они вам еще нужны, уничтожайте зеленых слизней для задания  #DOQUEST“Skulk Rock Clean-Up pt.1”#", x = 46, y = 62, zone = "The Hinterlands" },
			[12] = { str = "12. Если вам упал OOX-09/HL Distress Beacon то идите в точку 49,37.", x = 49, y = 37, zone = "The Hinterlands" },
			[13] = { str = "13. Отправляйтесь в точку 56,41 и убивайте Jade Oozes для задания  #DOQUEST“Skulk Rock Clean-Up”#", x = 56, y = 41, zone = "The Hinterlands" },
			[14] = { str = "14. Идите к водопаду в точке 81,46 и нырните в воду затем идите на юг вдоль берега пока не увидите Gammerita для задания  #DOQUEST“The Super Snapper FX”#  так же собирайте бутылки вдоль берега для задания  #DOQUEST“Whiskey Slim's Lost Grog”#", x = 81, y = 46, zone = "The Hinterlands" },
			[15] = { str = "15. Жмите Hearth в Aerie Peak" },
			[16] = { str = "16. Подойдите ко входу в гостинницу и сдайте задание  #TURNIN“Skulk Rock Clean-Up”#  и  #TURNIN“Troll Necklace Bounty”#,  а так же любые 5 ожерелий которые у вас есть." },
			[17] = { str = "17. Пройдите мимо точки входа в пещеру 9,44 и сдайте задание  #TURNIN“Witherbark Cages”#  и возьмите  #ACCEPT“The Altar of Zul”#", x = 9, y = 44, zone = "The Hinterlands" },
			[18] = { str = "18. Поднимитесь на вершину алтаря Altar of Zul в точке 48,68 для задания  #DOQUEST“The Altar of Zul”#", x = 48, y = 68, zone = "The Hinterlands" },
			[19] = { str = "19. Теперь качайтесть на тролях и волках вокруг Altar of Zul пока не останется всего 1 полоска до 47 уровня, к этому моменту у вас должен быть 46 уровень с половиной." },
			[20] = { str = "20. Если вы планируете позже пройти Sunken Temple то возьмите задание  #ACCEPT“Jammal'an the Prophet”# в точке 33,75.", x = 33, y = 75, zone = "The Hinterlands" },
			[21] = { str = "21. Когда вы будете близки к 47 уровню вам уже точно должен выпасть OOX-09/HL Distress Beacon возьмите заадние #ACCEPT“Find OOX-09/HL”#  и сдайте его в точке 49,37  затем возьмите  #ACCEPT“Rescue OOX-09/HL”# и сопроводите в точку 78,61 по дороге будут 2 пака по 3 моба и волки в незаметности будьте осторожны.", x = 49, y = 37, zone = "The Hinterlands" },
			[22] = { str = "22. Когда до 47 уровня останется 1 полоска или 6000 опыта hearth to Aerie Peak" },
			[23] = { str = "23. Сдайте все  #TURNIN“Troll Necklace Bounty”# Прямо перед выходом." },
			[24] = { str = "24. Идите выше полетчика в точку 9,44 и сдайте задание  #TURNIN“The Altar of Zul”#  возьмите следующее  #ACCEPT“Thadius Grimshade”#", x = 9, y = 44, zone = "The Hinterlands" },
			[25] = { str = "25. Летите в Menethil Harbor садитесь на корабль до Auberdine, затем летите Rut’theran Village." },
			[26] = { str = "26. Бегите к дому в точку 55,92 и сдайте задание  #TURNIN“Favored of Elune?”#", x = 55, y = 92, zone = "The Hinterlands" },
			[27] = { str = "27. Поднимитесь на верх и сдайте задание  #TURNIN“The Super Snapper FX”#  возьмите  #ACCEPT“Return to Troyas”#." },
			[28] = { str = "27. Сейчас у вас должен быть 47 уровень и примерно 8000 опыта." },
			[29] = { str = "29. Летите в Feralas." },
		}
	},

-----------47-47 Feralas
	--[409] = {
	[4747] = {
		title = "47-47 Feralas",
		--n = "47-47 Feralas",
		--pID = 408, nID = 410,
		--itemCount = 22,
		items = {
			[1] = { str = "1. 47-47 Feralas" },
			[2] = { str = "2. Сделайте Feathermoon Stronghold своим домом." },
			[3] = { str = "3. Идите от гостиницы к двухэтажному дому и сдайте задание  #TURNIN“Return to Troyas”#  возьмите  #ACCEPT“The Stave of Equinex”#" },
			[4] = { str = "4. Возьмите задание  #ACCEPT“The Sunken Temple”# рядом с ним." },
			[5] = { str = "5. Плывите на восток к причалу." },
			[6] = { str = "6. Рядом с причалом в точке 44,33 возьмите задание  #ACCEPT“Zapped Giants”#  и  #ACCEPT“Fuel for Zapping”#", x = 44, y = 33, zone = "Feralas" },
			[7] = { str = "7. Вынесите на панель Zorbin's Ultra-Shrinker затем идите на юг вдоль берега примените этот итем на гигантов и убивайте их для задания  #DOQUEST“Zapped Giants”#  так же убивайте элементалей для задания  #DOQUEST“Fuel for Zapping”#" },
			[8] = { str = "8. Вернитесь в точку 44,33 и сдайте задания  #TURNIN“Zapped Giants”#  и  #TURNIN“Fuel for Zapping”#.  Повторно делать эти задания не нужно. Теперь вам открыта возможность тут продовать НПС хлам.", x = 44, y = 33, zone = "Feralas" },
			[9] = { str = "9. Бегите в лагерь grimtotem camp в точку 65,45 и возьмите задание  #ACCEPT“An Orphan Looking For A Home”#", x = 65, y = 45, zone = "Feralas" },
			[10] = { str = "10. Спуститесь к пещере иети в точке 56,56 и пропробуйте выполнить задание на сопровоздение если нужно попросите помощи у других или соберите группу.", x = 56, y = 56, zone = "Feralas" },
			[11] = { str = "11. Гриндите до пещеры йети в точке 51,31 медведей и горилл пока не получите по 3 печени каждого из них для задания  #DOQUEST“Rhapsody's Kalimdor Kocktail”#", x = 51, y = 31, zone = "Feralas" },
			[12] = { str = "12. Убейте Rage Scar Yeti’s для задания  #DOQUEST“Improved Quality”#. Если выпадет Pristine Yeti Hide берите задание  #ACCEPT“Pristine Yeti Hide”#" },
			[13] = { str = "13. Идите к Rockbiter в точку 42,22 и возьмите задание  #ACCEPT“The Giant Guardian”#", x = 42, y = 22, zone = "Feralas" },
			[14] = { str = "14. Выполните задание #DOQUEST“The Stave of Equinex”# таким способом. Добудьте эссенцию огня Blytan Essence в точке 38,15. Для задания #DOQUEST“The Stave of Equinex”# Добудьте эсенцию Samha Essence из огня в точке 40,12 (на вершине разрушенной арки) чтобы добраться до нее нужно обойти сзади и забраться на осколки камней (их не легко заметить) вернитесь назад и возьмите эссенцию Imbel Essence из огня в точке 39,9. Добудьте эссенцию Lahassa Essence из огня в точке 37,12 под коричневой беседкой. Спуститесь к монолиту Equinex Monolith расположенному за обрывам. Используйте посох Troya’s рядом с ним. Прикоснитесь к монолите и сдайте задание #TURNIN“The Stave of Equinex”# и возьмите #ACCEPT“The Morrow Stone”#", x = 38, y = 15, zone = "Feralas" },
			[15] = { str = "15. Вернитесь в предыдущее место возгорания по координатам 38,10 и сдайте задание  #TURNIN“The Giant Guardian”#  возьмите следующее задание на сопровоздение  #ACCEPT“Wandering Shay”#", x = 38, y = 10, zone = "Feralas" },
			[16] = { str = "16. Возьмите Grab the bell и вынесите его на панель. Задание похоже на то что мы делали в Darkshore. Отведите ее обратно в Rockbiter в точку 42,21 и сдайте задание  #TURNIN“Wandering Shay”#  (Хитрость в том что бы опережать ее если она будет с вами рядом она будет чаще отходить в сторону, а у колокольчика минутный таймер.", x = 42, y = 21, zone = "Feralas" },
			[17] = { str = "17. Жмите Hearth в Feathermoon Stronghold" },
			[18] = { str = "18. Идите в бесетку у воды рядом с полетчиком и сдайте задания  #TURNIN“Pristine Yeti Hide”#  и  #TURNIN“Improved Quality”#" },
			[19] = { str = "19. У вас должны быть 2 элексира Elixirs of Fortitude." },
			[20] = { str = "20. Идите к двух этажному дому и сдайте задание  #TURNIN“The Morrow Stone”#" },
			[21] = { str = "21. У вас должно быть около 70% опыта до 47 уровня." },
			[22] = { str = "22. Летите в Gadgetzan" },
		}
	},

-----------47-48 Tanaris
	--[410] = {
	[4748] = {
		title = "47-48 Tanaris",
		--n = "47-48 Tanaris",
		--pID = 409, nID = 411,
		--itemCount = 42,
		items = {
			[1] = { str = "1. 47-48 Tanaris" },
			[2] = { str = "2. Сразу за Gadgetzan с права возьмите задание  #ACCEPT“The Thirsty Goblin”#" },
			[3] = { str = "3. Сделайте Gadgetzan своим домом." },
			[4] = { str = "4. Идите за гостиницу и возьмите задание  #ACCEPT“The Dunemaul Compound”#" },
			[5] = { str = "5. Около северного входа возьмите задание  #ACCEPT“Thistleshrub Valley”#" },
			[6] = { str = "6. Идите на юг к скелету на земле в точке 49,36 и 44,39 и 47,45 убивайте птиц для задания  #DOQUEST“Rhapsody's Kalimdor Kocktail”# Если тут много народа сделайте это позже.", x = 49, y = 36, zone = "Tanaris" },
			[7] = { str = "7. Идите до точки 52,45 и сдайте задание  #TURNIN“The Sunken Temple”#  и возьмите задания  #ACCEPT“The Stone Circle”#  и  #ACCEPT“Gahz'Ridian”#", x = 52, y = 45, zone = "Tanaris" },
			[8] = { str = "8. Теперь наденьте шлем детектор Gahz’Ridian Detector Helm и на миникарте будут показываться желтые точки собирайте кучи для задания  #DOQUEST“Gahz'Ridian”#. Все эти предметы разбросаны по всей локации." },
			[9] = { str = "9. Бегите на запад к Dunemaul Compound расчистите путь к точке 40,58 и убейте Gor’Marok для задания  #DOQUEST“The Dunemaul Compound”# вам не нужно убивать 20 огров все делается отсюда.", x = 40, y = 58, zone = "Tanaris" },
			[10] = { str = "10. Идите в точку 47,65 и добейте огров для получения трофея поместья The Dunemaul Compound совместно собирая остальные артефакты для Gahz'Ridian", x = 47, y = 65, zone = "Tanaris" },
			[11] = { str = "11. Гриндите огров примерно 10,000 опыта оставщегося до 48 уровня." },
			[12] = { str = "12. Прокрадитесь по левой стороне Uldum'a и поднимитесь к пьедесталу по координатам 37,81 и сдайте задание  #TURNIN“Seeing What Happens”#", x = 37, y = 81, zone = "Tanaris" },
			[13] = { str = "13. Поговорите с появившимся персонажем и возьмите задание  #ACCEPT“The Stone Watcher”#  и разговаривайте с ним до выполнения задания. Затем коснитесь постамента что бы вернуть его на место." },
			[14] = { str = "14. Прикоснитесь к постаменту еще раз и возьмите задание  #ACCEPT“Return to Ironforge”#" },
			[15] = { str = "15. Отправляйтесь на запад в точку 29,66 и убивайте Gnarled Thistlegrub и Thistlegrub Rootshapers для задания  #DOQUEST“Thistleshrub Valley”#  и сборщиков росы для выполнения задания  #DOQUEST“The Thirsty Goblin”# Тут вы должны получить 48 уровень.", x = 29, y = 66, zone = "Tanaris" },
			[16] = { str = "16. Если найдете черепаху Tooga, то возьмите задание  #ACCEPT“Tooga’s Quest”#  я нашел ее в точке 29,73 около дережабля но вы можете найти его где угодно в этой долине. Она всегда следует за вами.", x = 29, y = 73, zone = "Tanaris" },
			[17] = { str = "17. Идите в логово Noxious Lair в точке 34,46 и убейте Centipaar для задания  #DOQUEST“Noxious Lair Investigation”#  Если не успеете выполнить все задания когда у tooga останется 10 минут идите сдайте задание с тогой затем вернитесь и продолжайте выполнять задания.", x = 34, y = 76, zone = "Tanaris" },
			[18] = { str = "18. Сдайте задание  #TURNIN“Tooga’s Quest”#  рядом с steamwheedle port в точке 66,25", x = 66, y = 25, zone = "Tanaris" },
			[19] = { str = "19. Возьмите задание  #ACCEPT“Yuka Screwspigot”#" },
			[20] = { str = "20. Сдайте задание  #TURNIN“Screecher Spirits”# в точке 66,22 следующее задание отправит нас в ZF ПРОПУСТИТЕ его.", x = 66, y = 22, zone = "Tanaris" },
			[21] = { str = "21. Жмите Hearth в Gadgetzan" },
			[22] = { str = "22. Подойдите ко входу и возьмите задание  #ACCEPT“The Thirsty Goblin”#  затем сдайте его и возьмите следующее  #ACCEPT“In Good Taste”#" },
			[23] = { str = "23. Пройдите за гостиницу к костру и сдайте  #TURNIN“The Dunemaul Compound”#" },
			[24] = { str = "24. Идите в северному входу и сдайте задание  #TURNIN“Thistleshrub Valley”#" },
			[25] = { str = "25. Идите на запад в Sprinkle и сдайте задание  #TURNIN“In Good Taste”#  возьмите следующее  #ACCEPT“Sprinkle's Secret Ingredient”#" },
			[26] = { str = "26. В здании позади сдайте  #TURNIN“Noxious Lair Investigation”#" },
			[27] = { str = "27. Поднимитесь на холм и возьмите задание  #ACCEPT“The Schrimshank Redemption”#" },
			[28] = { str = "27. Идите в точку 52,45 и сдайте задание  #TURNIN“Gahz'Ridian”#", x = 52, y = 45, zone = "Tanaris" },
			[29] = { str = "29. Идите в точку 55,70 идите по спиральной лесницу к северному входу на первой развилке поверните на право после круглой комнаты на следующей развилке поверните на право вы попадете в большую квадратную комнату идите на право в точку 55,71 и возьмите снаряжение для задания  #DOQUEST“The Schrimshank Redemption”#", x = 55, y = 70, zone = "Tanaris" },
			[30] = { str = "30. Специально умрите что бы оказаться в Gadgetzan" },
			[31] = { str = "31. Поднимитесь на холм в западной части города и сдайте задание  #TURNIN“The Schrimshank Redemption”#  и возьмите следующее  #ACCEPT“Insect Part Analysis pt.1”#" },
			[32] = { str = "32. Идите в дом на северо-западной части города и сдайте  #TURNIN“Insect Part Analysis pt.1”#  и возьмите новое  #ACCEPT“Insect Part Analysis pt.2”#" },
			[33] = { str = "33. Вернитесь на холм и сдайте задание  #TURNIN“Insect Part Analysis pt.2”#  возьмите  #ACCEPT“Rise of the Silithid”#" },
			[34] = { str = "34. Бегите на север в соседнюю локацию в Shimmering Flats в точку 78,74 и сдайте задание  #TURNIN“An Orphan Looking For A Home”#  возьмите  #ACCEPT“A Short Incubation”# поскольку у вас уже есть это задание сдайте его обратно и возьмите новое  #ACCEPT“The Newest Member of the Family”# теперь у вас есть час.", x = 78, y = 74, zone = "Thousand Needles" },
			[35] = { str = "35. Отправляйтесь в Theramore достаньте все имеющиеся магические ткани посторайтесь максимально повысить уровень окаазния Первой помощи." },
			[36] = { str = "36. Плывите на корабле Menethil и летите в IF" },
			[37] = { str = "37. Сделайте IF своим домом и выучите новые навыки у тренера." },
			[38] = { str = "38. Идите в точку 77,11 и сдайте  #TURNIN“Return to Ironforge”#  возьмите новые задания  #ACCEPT“A Future Task”#  и  #ACCEPT“Passing the Burden”#", x = 77, y = 11, zone = "Ironforge" },
			[39] = { str = "39. Сдайте в точке 70,18 задание  #TURNIN“A Future Task”#", x = 70, y = 18, zone = "Ironforge" },
			[40] = { str = "40. Идите в точку 31,4 и сдайте задание  #TURNIN“Passing the Burden”#  и возьмите новые задания  #ACCEPT“Arcane Runes”#  и  #ACCEPT“An Easy Pickup”#", x = 31, y = 4, zone = "Ironforge" },
			[41] = { str = "41. Идите в точку 70,93 сдайте задание  #TURNIN“An Easy Pickup”#  и возьмите  #ACCEPT“Signal For Pickup”#  затем сдайте его обратно. Теперь у вас есть сигнальный пистолет что бы подавать сигналы позже.", x = 70, y = 93, zone = "Ironforge" },
			[42] = { str = "42. Летите в the Hinterlands" },
		}
	},

-----------48-48 The Hinterlands
	--[411] = {
	[4848] = {
		title = "48-48 The Hinterlands",
		--n = "48-48 The Hinterlands",
		--pID = 410, nID = 412,
		--itemCount = 8,
		items = {
			[1] = { str = "1. 48-48 The Hinterlands" },
			[2] = { str = "2. Спуститесь в низ в точку 14,43 и сдайте задание #TURNIN“The Newest Member of the Family”# возьмите следующее #ACCEPT“Food For Baby”#", x = 14, y = 43, zone = "The Hinterlands" },
			[3] = { str = "3. Идите в точку 26,48 и сдайте #TURNIN“Rhapsody's Kalimdor Kocktail”# возьмите задание #ACCEPT“Rhapsody's Tale”#", x = 26, y = 48, zone = "The Hinterlands" },
			[4] = { str = "4. Гриндите по пути к озеру в точку 40,59 и найдите на дне гриб Violet Tragan (Mushroom) для задания #DOQUEST“Sprinkle's Secret Ingredient”#", x = 40, y = 59, zone = "The Hinterlands" },
			[5] = { str = "5. Гриндите пока идете в точку 57,47 и убивайте kill Silvermane Stalkers для задания #DOQUEST“Food For Baby”#", x = 57, y = 47, zone = "The Hinterlands" },
			[6] = { str = "6. Вернитесь на вершину Aerie Peak и спуститесь на нижний этаж гостиницы" },
			[7] = { str = "7. Сдайте задание #TURNIN“Food For Baby”# и возьмите #ACCEPT“Becoming A Parent”# и тут же сдайте его тут же" },
			[8] = { str = "8. Жмите Hearth в IF (Стальгорн) и летите в BB (Пиратская бухта)" },
		}
	},

-----------48-49 Stranglethorn Vale
	--[412] = {
	[4849] = {
		title = "48-49 Stranglethorn Vale",
		--n = "48-49 Stranglethorn Vale",
		--pID = 411, nID = 413,
		--itemCount = 27,
		items = {
			[1] = { str = "1. 48-49 Stranglethorn Vale" },
			[2] = { str = "2. Идите в таверну и сделайте ее своим домом" },
			[3] = { str = "3. Сдайте задание #TURNIN“Back To Booty Bay”# и #TURNIN“Whiskey Slim's Lost Grog”#" },
			[4] = { str = "4. Войдите в дом с полукараблем и сдайте задани #TURNIN“Deliver to MacKinley”#" },
			[5] = { str = "5. Под полулодкой возьмите задание #ACCEPT“Stranglethorn Fever”#" },
			[6] = { str = "6. Поднимитесь по пандусу и пройдите к первому дому, сдайте всех роботов куриц которых вы получили в качестве сопровождения. Я не олучил сопровождение из танариса когда писал это руководство по этоу пропустил квест на получение 7100 опыта" },
			[7] = { str = "7. Около причала коробля возьмите задание #ACCEPT“The Captain's Chest”# у капитана" },
			[8] = { str = "8. Убейте горилл в точке 34,63 для #DOQUEST“Stranglethorn Fever”# затем идите в пещеру в точке 35,60 и сдайте его. С горилл нужно выбить 10 gorilla fangs и сдать их в пещере, побегут гарилы 3 волны попробуйте убежать наружу и ждать пока в последней 3 волне не прибежит Mokk запульте его и бегите пока другие мобы отстанут.", x = 35, y = 60, zone = "Stranglethorn Vale" },
			[9] = { str = "9. Идите в точку 38,34 и убейте #NPCKing Bangalash# для #DOQUEST“Big Game Hunter”#, Появятся 2 моба 33 уровня нужно постараться убить до их появления.", x = 38, y = 34, zone = "Stranglethorn Vale" },
			[10] = { str = "10. Идите в точку 48,25 и убивайте элитных огров пока не выпадет ключ Maury’s Key для #DOQUEST“Cracking Maury’s Foot”#. Если вы не выбьете его через час просто отмение задание шанс выподения низкий я прокачиваюсь до того пока не останется 2 полоски до 49 уровня если не получаю ключ. Обычно это занимает около часа (задание максимально дибильное но попробовать можно)", x = 48, y = 25, zone = "Stranglethorn Vale" },
			[11] = { str = "11. Идите в лагерь Nessingways в точку 35,10 и сдайте #TURNIN“Big Game Hunter”#", x = 35, y = 10, zone = "Stranglethorn Vale" },
			[12] = { str = "12. Жмите Hearth в Booty Bay, поднимитесь на полулодку" },
			[13] = { str = "13. Сдайте #TURNIN“Stranglethorn Fever”#" },
			[14] = { str = "14. Бегите по восточному побережью от BB и открывайте маленькие бутылки (их легко не заметить) в бутылке должны быть записка возьмите задание из записки #ACCEPT“Message in A Bottle pt.1”#" },
			[15] = { str = "15. Идите в точку 36,69 и убейте #NPCGorlash# для #DOQUEST“The Captain's Chest”#. Элитный моб 47 уровня. Если сложно убить то попросите о помощи кого-нибудь", x = 36, y = 69, zone = "Stranglethorn Vale" },
			[16] = { str = "16. Идите в точку 38,80 и сдайте #TURNIN“Message in A Bottle pt.1”# ПРОПУСТИТЕ следующее задание если не сможете найти группу для убийства гориллы 51 уровня", x = 38, y = 80, zone = "Stranglethorn Vale" },
			[17] = { str = "17. Идите к пиратским кораблям и убейте командиров на каждом корабле, их можно найти внутри коробля в носовой части. Корабли находятся в точке 33,87 и 30,88 для #DOQUEST“The Bloodsail Buccaneers pt.5”#", x = 33, y = 87, zone = "Stranglethorn Vale" },
			[18] = { str = "18. Найдите на одном из кораблей свиток Cortello's Riddle возьмите у него задание #ACCEPT“Cortello's Riddle pt.1”#" },
			[19] = { str = "19. Жмите hearth, если он на кд то умрите и вы окажетесь в BB (Пиратской бухте)" },
			[20] = { str = "20. Идите к причалу корабля и сдайте #TURNIN“The Captain's Chest”#" },
			[21] = { str = "21. Зайдите в таверну и сдайте #TURNIN“The Bloodsail Buccaneers pt.5”#" },
			[22] = { str = "22. Летите в SW (Шторм) в точке 64,20 сдайте #TURNIN“Rhapsody's Tale”# следующее задание ПРОПУСТИТЕ", x = 64, y = 20, zone = "Stormwind" },
			[23] = { str = "23. С этого момента смотрите на аукционе когда будете проходить мимо Beaststalker Bracers и mithril casing для задания в Un’Goro. Это скоро вам пригодится" },
			[24] = { str = "24. Летите в Duskwood" },
			[25] = { str = "25. Бегите через перевал в Swamp of Sorrows" },
			[26] = { str = "26. Идите по дороге до развилки на левой стороне находится мост в точке 22,48 под мостом находится A Soggy Scroll сдайте задание #TURNIN“Cortello's Riddle pt.1”# и возьмите #ACCEPT“Cortello's Riddle pt.2”#", x = 22, y = 48, zone = "Swamp of Sorrow" },
			[27] = { str = "27. Идите в Blasted Lands" },
		}
	},
	
--------49-50 Blasted Lands
	--[413] = {
	[4950] = {
		title = "49-50 Blasted Lands",
		--n = "49-50 Blasted Lands",
		--pID = 412, nID = 501,
		--itemCount = 30,
		items = {
			[1] = { str = "1. 49-50 Blasted Lands" },
			[2] = { str = "2. Не спешите тут, убивайте все что видите" },
			[3] = { str = "3. Идите в точку 50,14 и возьмите 5 заданий #ACCEPT“The Basilisk's Bite”#, #ACCEPT“Vulture's Vigor”#, #ACCEPT“Snickerfang Jowls”#, #ACCEPT“A Boar's Vitality”# и #ACCEPT“The Decisive Striker”#", x = 50, y = 14, zone = "Blasted Lands" },
			[4] = { str = "4. Для этих заданий потребуется Snickerfang Jowls:5, Blasted Boar Lungs:6, Scorpok Pincers:6, Basilisk Brain:11, Vulture Gizzards:14. Гриндите короче все это пока вы быдете это все выбивать заработаете кучу опыта" },
			[5] = { str = "5. Обойдите локацию по кругу и вы найдете всех нужных мобов. будьте осторожны в южной части там мобы 53 уровня (координаты писать не буду их будет очень много)" },
			[6] = { str = "6. Сейчас у вас должно не хватать около 3 с половиной полосок до 49 уровня" },
			[7] = { str = "7. Гриндите мобов до точки 51,35 там возьмите задание #ACCEPT“Everything Counts In Large Amounts”# задание многоразовое сдавайте этот квест когда будете проходить рядом, Если найдете предмет для другого задания у этого НПС сдайте его тоже", x = 51, y = 35, zone = "Blasted Lands" },
			[8] = { str = "8. Идите в точку 50,14 и сдайте те самы 5 заданий #TURNIN“The Basilisk's Bite”#, #TURNIN“Vulture's Vigor”#, #TURNIN“Snickerfang Jowls”#, #TURNIN“A Boar's Vitality”#, и #TURNIN“The Decisive Striker”# Сдайте квест который дает лучший баф для вашего класса последним", x = 50, y = 14, zone = "Blasted Lands" },
			[9] = { str = "9. Идите в крепость Nethergarde Keep поднимитесь на вершину башни в точке 66,19 и сдайте задание #TURNIN“Thadius Grimshade”# следующее заадние ПРОПУСТИТЕ", x = 66, y = 19, zone = "Blasted Lands" },
			[10] = { str = "10. Сейчас у вас должно быть около 70% опыта до 49 уровня. Можете пройти ZF и апнуть там 50 уровень или гриндить тут пока не останется 13 000 опыта до 50 урвня. Если хотите пройти ZF то переходите к следующему шагу" },
			[11] = { str = "11. Жмите Hearth в Booty Bay" },
			[12] = { str = "12. Возьмите задания #ACCEPT“Zanzil's Mixture”# и #ACCEPT“A Fool's Stout”#" },
			[13] = { str = "13. Плывите на корабле до Ratchet" },
			[14] = { str = "14. Возьмите задание #ACCEPT“Volcanic Activity”# в первом доме у причала" },
			[15] = { str = "15. Прямо перед этим домом находится зеленый сундук откройте его и возьмите задание #DOQUEST“The Stone Circle”#" },
			[16] = { str = "16. Летите в Tanaris" },
			[17] = { str = "17. Идите к северо-западному входу сдайте задание #TURNIN“Sprinkle's Secret Ingredient”# и возьмите следующее #ACCEPT“Delivery For Marin”#" },
			[18] = { str = "18. Вернитесь к южному входу и сдайте заадние #TURNIN“Delivery For Marin”#, возьмите следующее задание #ACCEPT“Noggenfogger Elixir”# затем сдайте его обратно. Вы получите 5 элексиров и в дальнейшем сможете покупать их у торговца" },
			[19] = { str = "19. Бегите на север в соседнюю локацию Shimmering Flats в точке 77,77 сдайте задания #TURNIN“Zanzil's Mixture”# и #TURNIN“A Fool's Stout”#, возьмите следующее #ACCEPT“Get the Goblins Drunk”# и сдайте его в точке 79,76", x = 77, y = 77, zone = "Thousand Needles" },
			[20] = { str = "20. Вернитесь в точку 77,77 и возьмите задание #ACCEPT“Report Back to Fizzlebub”#", x = 77, y = 77, zone = "Thousand Needles" },
			[21] = { str = "21. Идите в точку 52,45 сдайте задание #TURNIN“The Stone Circle” следуюшие задания ПРОПУСТИТЕ если вы не планируете пройти Sunken Temple.", x = 52, y = 45, zone = "Thousand Needles" },
			[22] = { str = "22. Сейчас вам осталось добить около 30 000 опыта до 50 уровня идите в ZF, но лучше бы вы гриндили мобов в Blasted Lands" },
			[23] = { str = "23. Если вы проходите ZF вам нужно выполнить минимум 2-3 задания из следующих #DOQUEST“Troll Temper”#, #DOQUEST“Divino-matic Rod”#, #DOQUEST“Gahz'rilla”#, #DOQUEST“The Prophecy of Mosh'Aru”# я рекомендую выполнить #ACCEPT“Divino-matic Rod”# и #ACCEPT“Gahz'rilla”# вы получите кольцо и тринбку на увеличение скорости маунта" },
			[24] = { str = "24. Если вы прошли ZF вам нужно добить 1-2 клетки до 50 уровня. Прокачка с 45 до 50 уровеня это головная боль дальше будет интересней" },
			[25] = { str = "25. Жмите Hearth в BB и сдайте задание #TURNIN“Report Back to Fizzlebub”#" },
			[26] = { str = "26. Летите в IF и выучите новые навыки и возьмите задание #ACCEPT“The Hunter's Charm”#" },
			[27] = { str = "27. Убедитесь что у вас есть 15 шт. Silk Cloth если нет купите ткань на аукционе" },
			[28] = { str = "28. Сделайте IF своим домом, возьмите задание #ACCEPT“Assisting Arch Druid Staghelm”#" },
			[29] = { str = "29. Летите в Thelsamar" },
			[30] = { str = "30. Идите на юг в Badlands и по локации на запад в точке 1,62 через ущелье пройдите в Searing Gorge", x = 1, y = 62, zone = "Badlands" },
		}
	},
}
